### ISSUE TITLE
typing error

### ISSUE THREAD

**Issue by tondji** [mml-book/mml-book.github.io#100]
**Describe the mistake**
In chapter 6, page 22, On equation 6.71, It's written P_x(Y^{1/2}) .

**Location**
Please provide the 
1. version (bottom of page) 2018-07-04
2. Chapter 6
3. page 22
4. line number/equation number ;  Equation number 6.71

**Proposed solution**
I think it's should be F_x(Y^{1/2}) 

**Additional context**

**Comment by chengsoonong** [comment]
Thanks!

**Comment by chengsoonong** [comment]
Fixed in 3fa732f8b4890d35ff8c777c89449b43c798a0d3
