### ISSUE TITLE
The remarks in the margin of Chapter 9 are incomplete

### ISSUE THREAD

**Issue by tondji** [mml-book/mml-book.github.io#101]
**Describe the mistake**
In chapter 9 , at the page number 5, the remark in the margin are incomplete , they were moved to the left.

**Location**
Please provide the 
1. version (bottom of page) 2018-08-30
2. Chapter 9
3. page 5
4. line number/equation number ; On the margin

**Proposed solution**
We can put it on the right because there is enough space on the right of the document

**Additional context**

**Comment by mpd37** [comment]
Thanks for pointing this out. We will fix all typesetting issues in the final version only. The template breaks too regularly.
