### ISSUE TITLE
typo on Example 9.2 (Polynomial Regression)

### ISSUE THREAD

**Issue by tondji** [mml-book/mml-book.github.io#102]
**Describe the mistake**
In chapter9, on page 7, you wrote : 
We are concerned with a regression problem ....... where x belong to R ..........

**Location**
Please provide the 
1. version (bottom of page) 2018-08-30
2. Chapter 9
3. page 7
4. line number/equation number ; above equation 9.13

**Proposed solution**
I think it's should be x belong to R^D.

**Additional context**

**Comment by mpd37** [comment]
In this example, the input is actually only one-dimensional. This allows us to plot things easily.
