### ISSUE TITLE
Definition of Null Space

### ISSUE THREAD

**Issue by p-christ** [mml-book/mml-book.github.io#103]
Chapter 2, line 1385 says the Null Space is the set of vectors for which the mapping of the vector produces the **neutral element**. But if you read about the null space on wikipedia it says the mapping should produce **0** and not the neutral element.  Which one is correct?

**Comment by mpd37** [comment]
The neutral element (w.r.t. the standard vector addition) is the 0 vector. Therefore, it's identical in that case. 

"let f be a homomorphism of that type from A to B. If eB is the neutral element of B, then the kernel of f is the preimage of the singleton set {eB}"

from https://en.wikipedia.org/wiki/Kernel_(algebra)
