### ISSUE TITLE
Chapter 4, draft 2018-09-21, pg. 110, line 2229, there is an extra "p" in mappping

### ISSUE THREAD

**Issue by idoamihai** [mml-book/mml-book.github.io#104]
Chapter 4, draft 2018-09-21, pg. 110, line 2229, there is an extra "p" in mappping

**Comment by Antymon** [comment]
2397 redundant "we"

**Comment by Antymon** [comment]
2408 collecting -> connecting?

**Comment by Antymon** [comment]
2480 missing "than" after "rather"
2496 over -> cover
2508 is -> as
2544 pseude -> pseudo
