### ISSUE TITLE
Suggestions/Errors in Chapters 1, 2, 3, 5 and 7

### ISSUE THREAD

**Issue by RagibZaman** [mml-book/mml-book.github.io#105]
[MML Book Suggestions.pdf](https://github.com/mml-book/mml-book.github.io/files/2417983/MML.Book.Suggestions.pdf)

I've attached a pdf with some errors I found and some suggestions. In the future I will make sure to submit these in a more similar format to the other github issues. If my suggestions seem inappropriate or incompatible with the intended nature of the book, please let me know how so that I can adjust accordingly in future suggestions. Thanks.

**Comment by chengsoonong** [comment]
Fixes to Chapter 7 will be included in the next update.
