### ISSUE TITLE
Example 4.9: Small bug in intermediate result

### ISSUE THREAD

**Issue by Phlogiston90** [mml-book/mml-book.github.io#106]
**Describe the mistake**
(2-λ)²-1 = λ²-2λ+3 is wrong.

**Location**
Please provide the 
1. version 2018-09-21
2. chapter 4
3. page 113
4. equation 4.63

**Proposed solution**
(2-λ)²-1 = λ²-4λ+3

**Comment by AceCoooool** [comment]
1. "step3: Compute the diagomalizing matrix P" should change to "step3: Compute the diagomalizing matrix D"
2. (4.70) "A=PAP^T" should change to "A=PDP^T"

**Comment by chengsoonong** [comment]
Thanks for the careful reading.
