### ISSUE TITLE
Mistakes in SVD proof

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#107]
**Describe the mistake**
Mentioned part of SVD proof mistakenly uses left multiplication of matrix A instead of its transpose. Error cascades few lines down, including reference to irrelevant product of transpose. Although we indeed end up with eigen equation, statement contradicts with equation shown and mentions AA^T rather than A^TA. Ultimately correct conclusion is made on equality of eigen values.

**Location**
1. version 2018-09-21
2. Chapter 4
3. page 121
4. line before equation 4.91, equations 4.91, 4.92, irrelevant reference to property 2.30 on transpose of product in between equations, reference to AA^T on line 2388, claim that Ax is an eigenvector on line 2389.

**Proposed solution**
Starting line before equation 4.91 left multiplication of transpose of A needs to be mentioned, otherwise dimensions wouldn't match (A is rect matrix). Then equations 4.91 and 4.92 need to be modified accordingly. Reference to 2.30 needs to be removed or replaced with matrix multiplication associativity. Ultimately conclusion on eigen equation needs to refer to A^TA, and eigenvector is represented by A^Tx

**Comment by chengsoonong** [comment]
Thanks for the careful reading.
