### ISSUE TITLE
Figures 4.6 and 4.7 both describe non-existent transition

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#108]
**Describe the mistake**
There is no bottom left to upper left transition: right side was mistakenly taken for left in this case (end of the description).

**Location**
Please provide the 
1. version 2018-09-21
2. Chapter 4
3. page
4. Figures 4.6 and 4.7

**Proposed solution**
Change description of last transition from left to right.

**Comment by chengsoonong** [comment]
Thanks for the careful reading.
