### ISSUE TITLE
Issues with figures 4.10, 4.11, 4.12

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#109]
**Describe the mistake**

Suggested changes for figures:

4.10 "middle left" should be "top middle"
4.11 "middle left" should be "top middle"
4.11 dimensions 280 and 350 are not consistently used across calculations; coincidentally final value is correct though
4.12 figure does not exist even though being mentioned at line 2535

**Location**
1. version 2018-09-21)
2. Chapter 4

**Comment by chengsoonong** [comment]
Thanks for the careful reading.
