### ISSUE TITLE
line 1218: example seems to wrongly imply that independence is orthogonality

### ISSUE THREAD

**Issue by chriswebers** [mml-book/mml-book.github.io#11]
The London-Munich example seems to imply that orthogonal vectors are independent while a third (non-orthogonal) is not. Of course, any pair is independent here, and a third one makes it dependent. Maybe, use East and Southeast as the first pair and South as the third. (A more natural non-orthogonal coordinate system would be even better, but none comes to mind.)

**Comment by mpd37** [comment]
![image](https://user-images.githubusercontent.com/5500569/44519757-4374c500-a6ce-11e8-87ce-3b776e390f88.png)

Good point. Do you think this example is better?
