### ISSUE TITLE
Missing or extra text

### ISSUE THREAD

**Issue by agaier** [mml-book/mml-book.github.io#113]
**Describe the mistake**
Text: "On the contrary, if b,g _were al and lie_ along the canonical coordinate axes"

**Location**
Chapter 4, page 95, bottom of Example 4.2
Please provide the 
1. version (bottom of page)
2. Chapter
3. page
4. line number/equation number

**Proposed solution**
Could be:
"On the contrary, if b,g were aligned along the canonical coordinate axes"
or
"On the contrary, if b,g lie along the canonical coordinate axes"

**Comment by chengsoonong** [comment]
Thanks.
