### ISSUE TITLE
Ambiguity of exercise 4.8

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#114]
**Describe the mistake**
Exercise requests finding "best rank-1 approximation" of a given matrix. As per definition 4.109, for a given rank and matrix there is only one possible approximating matrix, thus 'best' becomes meaningless.

**Location**
Please provide the 
1. version 2018-09-21
2. Chapter 4
3. page 134
4. exercise 4.8

**Proposed solution**
If intent was to find best approximation of A using rank-1 matrices defined at 4.107, rephrasing is needed. This case would probably also benefit from clarification if those matrices should be weighted by singular values.

**Comment by AnalogAldo** [comment]
Rephrased and removed  “best”
