### ISSUE TITLE
Issues with SVD example 4.11

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#115]
**Describe the mistake**
Equation 4.98 - inner factor has incorrectly transposed matrices, should be other way around.

Comment below 4.105 - eigenvalue decomposition was used for A^TA in example 4.99 for right singular vectors, I believe poor numerical stability should refer to not using eigen decomposition for AA^T

**Location**
Please provide the 
1. version 2018-09-21
2. Chapter 4
3. page 122

**Additional context**
Would be nice to know why we can't simply use AA^T for left singular values. Is it just demonstration of link between left and right singular vectors? Aside from greater numerical stability (claim by author) I believe it's simpler to execute set of same steps on 2nd input data rather than introduce new steps depicting the link.

**Comment by AnalogAldo** [comment]
That is good point, that should have been now made clear. In terms of numerical comments it remains a balance between detail and flow for the non numerically interested reader.
