### ISSUE TITLE
Consistency issues between section 4.6 and previous material

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#116]
**Describe the mistake**

- lacking definition of outer product
- subscripted norm notation not explained
- subscripting largest singular value with 1 feels against remark on convention at line 2041

**Location**
Please provide the 
1. version 2018-09-21
2. Chapter 4
3. pages 126-131

**Proposed solution**
Adding clarifications. Following or removing notes on ordering conventions.

**Comment by AnalogAldo** [comment]
* lacking definition of outer product
Outer product is defined in Figure 5.13 (this needs to be changed in another chapter)

* subscripted norm notation not explained
Now explained.

* subscripting largest singular value with 1 feels against remark on convention at line 2041
So the subscribting the largest singular is actually consistent. (often we also subscribt the largest eigenvalue with 1).
