### ISSUE TITLE
Chapter 4 Matrix Multiplication Mistake

### ISSUE THREAD

**Issue by p-christ** [mml-book/mml-book.github.io#118]
Around line 2411, chapter 4, I believe the matrix multiplication (4.98) is incorrect. 

1) What is written out is A * A transpose rather than  A transpose * A 
2) I think the resulting matrix should have a 0 in row 2 column 3 instead of a 2.  Otherwise the resulting matrix is not symmetric

**Comment by AnalogAldo** [comment]
Good spot, this is now fixed in new PDF.
