### ISSUE TITLE
The spectral norm of A is its largest singular value proof

### ISSUE THREAD

**Issue by p-christ** [mml-book/mml-book.github.io#119]
On page 128 line (4.112) with the numerator you go from  (xA)_T (Ax)  to  x_T (A_T  A) x   but I don't think this is possible because   (xA)_T  =  A_T x_T  not  x_T A_T  unless i'm missing something?

**Comment by Antymon** [comment]
First factor in nominator under first sqrt of equation 4.112  being (Ax)^T, rather than (xA)^T would probably solve the problem.

**Comment by AnalogAldo** [comment]
That's correct, and now corrected
