### ISSUE TITLE
Rank-k approximation remark issue

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#122]
**Describe the mistake**
Remark says that rank-k approximation can be interpreted as projection of original matrix onto space of rank "at-most-k matrices". Isn't word "matrices" redundant in this case?

**Location**
Please provide the 
1. version 2018-09-21
2. Chapter 4
3. page 129
4. line number 2508-2509

**Comment by AnalogAldo** [comment]
thank you for this, I suppose you are referring to a syntactic not a mathematical issue here.  This is how i fixed it:

Remark. We can interpret the rank-k approximation obtained with the SVD *as* a projection of the full rank matrix A onto the lower-dimensional space of rank at-most-k matrices.

**Comment by Antymon** [comment]
Thank you. I must have misunderstood something then, since I wasn't pointing at syntactical issue. I am happy note helped with something all the same. Please assume no issue then. If upon revisiting I am further troubled I shall make another note.
