### ISSUE TITLE
Missing Group Operation Example 2.10

### ISSUE THREAD

**Issue by danielwo** [mml-book/mml-book.github.io#124]
**Describe the mistake**
A clear and concise description of what the mistake is:
(\mathbb{R} \backslash \{0\}) is missing the group operation

**Location**
Please provide the 
1. version (bottom of page): Draft (2018-09-21)
2. Chapter: 2
3. page: 36
4. line number/equation number: After line 1065, Example 2.10, 5th bullet point

**Proposed solution**
A clear and concise description of what you would like to change.
(\mathbb{R} \backslash \{0\}) should be (\mathbb{R} \backslash \{0\}, \cdot)

**Comment by mpd37** [comment]
Good catch. Will be fixed when we update the chapter next time.

**Comment by OlyDLG** [comment]
This also appears to be an undefined first use of the notation S\S' for the set S excluding the elements of S'; mathematicians will be familiar with that notation, but it's likely, I believe, others will not; regardless, I believe definition should be provided, both here, e.g., in the margin or in a footnote, and in the Table of Symbols, especially as this notation is also used in the Exercises.

**Comment by mpd37** [comment]
can you please raise a separate github issue for this?

**Comment by OlyDLG** [comment]
Yup!
