### ISSUE TITLE
Summation of marginal probabilities for 6.4 incorrectly bounded

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#125]
**Describe the mistake**
Equation 6.4 has summation bounds flipped. Taking figure 6.2 for source of truth, index i runs from 1 to 5 and j from 1 to 3, not other way around.

**Location**
Please provide the 
1. version 2018-07-04
2. Chapter 6
3. page 171
4. Equation 6.4

**Proposed solution**
Flip bounds around once more.

**Comment by chengsoonong** [comment]
Thanks.

**Comment by chengsoonong** [comment]
Fixed in 3fa732f8b4890d35ff8c777c89449b43c798a0d3
