### ISSUE TITLE
typo error in chapter 9 

### ISSUE THREAD

**Issue by ireneraissa** [mml-book/mml-book.github.io#127]
**Describe the mistake**

typing problem, it is written **we way want** 

**Location**
Please provide the 
1. version (bottom of page): Draft (2018-08-30) from Mathematics for Machine Learning
2. Chapter 9
3. page 268
4. line number/equation number:  5067-5068 on Uncertainty modeling.

**Proposed solution**
I think , we wanted to write  **we may want**

**Additional context**

**Comment by mpd37** [comment]
will be fixed in next revision of the chapter
