### ISSUE TITLE
Blatantly Issue in chapter of probability: event space, state space

### ISSUE THREAD

**Issue by PatWie** [mml-book/mml-book.github.io#128]
as recommended in the reddit-thread.

**Describe the mistake**
You mix up the "sigma-algebra" it self with the  "sample space".

**Location**
Please provide the 
1. version 
`Draft (2018-07-04)`
2. Chapter
`6.1.2`
3. page
`169`
4. line number
`3029`

I just glanced over the chapter.

Summing over all elements of the sigma algebra is >=1 (since $\Omega \in \mathcal{A}$) in your case: coin-toss, $P(A)_{A\in\mathcal{A}}=2$, since we adding ${h},{w}, \Omega$.

You probably mean $P(w)_{w\in \Omega} = 1$. But be careful, this is only valid for countable sets $\Omega$. Ask somebody with a proper math-background to get this chapter correct. There is a reason of measure theory to exists and being quite complex. There are a lot of snares. 
See, e.g. the extension theorem of Carathéodory for the case of uncountable sets.
Good luck!

**Comment by chengsoonong** [comment]
We made a choice in this book to not define continuous mathematical structures, e.g measures, functions, Hilbert spaces. However, you are correct to point out that there are serious problems with the introductory part of Chapter 6. We've tried to tidy things up, and added a remark pointing to the other concepts in the continuous probability section. Also added a few more thoughts in the further reading section.

Avoiding the explicit construction of continuous structures does not mean that we can be wrong about things we say that include continuous structures. So thanks for your feedback, and if you are not frustrated by our first draft, we hope you can have a look at the next version.

**Comment by PatWie** [comment]
Even in the coin toss example, the equation does not hold, should be 1 + 0.5 + 0.5 = 2 = P(omega) + P({h}) + P({t}) + P(emptyset)

**Comment by chengsoonong** [comment]
In the just revised version, we do not mention total probability in the introduction any longer. If you are looking at another version, please re-download.

**Comment by PatWie** [comment]
The revised version doesn't make it better:

> This association random variable 3084 or mapping from \Omega to \mathcal{A} is called a random variable.

(see line 3084)
The random variable X is not a mapping to \mathcal{A} (elements here are sets, of course one could construct a bizarre sigma-Algebra here). Consider your coin-toss, The mapping

```
Y -> {pizza, bread}, Y({head}) |-> pizza, Y({tail}) |-> bread
```

is a random variable. Because the pair of the set {pizza, bread} and its sigma Algebra is a measurable space. Btw. This is far from being nitpicking.

**Comment by chengsoonong** [comment]
Thanks. It is a mistake to overload the image of $\Omega$ under random variable $x$. And I do not consider your comments to be nitpicking. Please keep them coming.

Apart from trying to force the output of random variables into the event space, what other egregious errors did we make?

**Comment by chengsoonong** [comment]
We've updated the front part of Chapter 6 to no longer avoid talking about the sigma algebra. We do not actually define the sigma algebra, but the concept is there.

Does this satisfactorily address your concerns about event space?

**Comment by PatWie** [comment]
I did a quick glance over the first few parts. Since you never directly use the sigma algebra (discrete sets), it should be fine by just stick to subsets of Omega without ever mention the sigma algebra. The mathematics is the same. But the snares are less when only talking about subsets.
