### ISSUE TITLE
lines 1277 to 1280: why the focus on (sub)spaces here?

### ISSUE THREAD

**Issue by chriswebers** [mml-book/mml-book.github.io#13]
I don't see the purpose of the additional complexity by mentioning subspaces here.

**Comment by mpd37** [comment]
There's a bit of notation sloppiness going on. I'll fix this. The point here was more that we are talking about subsets of vectors in the vector space and not subspaces of vector spaces. We will make the distinction between sets and subspaces clearer. But here is already a preview (mathcal for sets):

![image](https://user-images.githubusercontent.com/5500569/36640591-e70cc3e4-1a19-11e8-9236-4614f62156f5.png)
