### ISSUE TITLE
Empirical covariance matrix labelled as empirical covariance

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#130]
**Describe the mistake**
Terminology is inherently confusing, but I think the relationship goes:

- Multivariate variance is represented as covariance matrix.
- Multivariate covariance is represented as cross-covariance matrix.

https://en.wikipedia.org/wiki/Multivariate_random_variable

Thus potentially, we should not use term "empiric covariance" in the sense of matrix, but rather plainly use term "empiric covariance matrix"?

**Location**
Please provide the 
1. version 2018-07-04
2. Chapter 6
3. page 180
4. line above equation 6.38

**Suggestion**

Rename term "empiric covariance" to "empiric covariance matrix"

**Comment by chengsoonong** [comment]
Tried to clarify. As you pointed out, the terminology in literature is unfortunately messy.

**Comment by chengsoonong** [comment]
Fixed in 3fa732f8b4890d35ff8c777c89449b43c798a0d3
