### ISSUE TITLE
Wrong expression of posterior

### ISSUE THREAD

**Issue by SuperYuLu** [mml-book/mml-book.github.io#135]
**Describe the mistake**
The posterior should be p(y|x) instead of p(x|y), according to equation (6.21), although this equation is wrong, as issued by #126 

**Location**  

1. version (bottom of page): Draft 2018-07-04
2. Chapter: 6
3. page: 177
4. line number/equation number: 3207

**Proposed solution**
Change "The posterior p(x|y) ...." to "The posterior  p(y|x)..."

**Additional context**
None

**Comment by chengsoonong** [comment]
Fixed in 3fa732f8b4890d35ff8c777c89449b43c798a0d3
