### ISSUE TITLE
Typo in Example 6.6

### ISSUE THREAD

**Issue by pat676** [mml-book/mml-book.github.io#139]
**Describe the mistake**
Example 6.6 on page 187, formula 6.71 has a minor typo. It says $P_x(Y^{1/2})$, but it should be $F_x(Y^{1/2})$ since it's a cdf.

**Location**
Please provide the 
1. 2018-07-04
2. 6.5.1
3. 187
4. 6.71

**Proposed solution**
Change to $F_x(Y^{1/2})$

**Additional context**

**Comment by chengsoonong** [comment]
Fixed in 3fa732f8b4890d35ff8c777c89449b43c798a0d3
