### ISSUE TITLE
Det of inverted matrix should be inverted for eq 6.97 and 6.99

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#142]
**Describe the mistake**
Equation 6.97 should show inverted det of matrix A, that is 1/(ad-bc). Reciprocal quoted instead. That cascades to 6.99.

**Location**
Please provide the 
1. version 2018-07-04
2. Chapter 6 
3. page 191

**Comment by chengsoonong** [comment]
Fixed in 4eb1c41941e94e1e7d7356fc25f7125f7d948b37
