### ISSUE TITLE
Beta distribution wrongly plotted for a=b=2

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#144]
**Describe the mistake**
Middle plot with parameters a=b=2 for Beta distribution clearly doesn't have property of symmetry. Guesstimating it looks more like b=1, a=10. It would be also nice if plot lines were thicker and colors more varied, for the sake of readability - perhaps that contributed to the issue.

**Location**
Please provide the 
1. version 2018-07-04)
2. Chapter 6
3. page 201
4. figure 6.9

**Comment by chengsoonong** [comment]
Well spotted.

**Comment by chengsoonong** [comment]
Colour choice is tricky, and we have to balance the ability to allow color blind people to distinguish the colours, and to allow for good monochrome printing.
