### ISSUE TITLE
Correlation Equation

### ISSUE THREAD

**Issue by gthd** [mml-book/mml-book.github.io#145]
**Describe the mistake**
In the book the correlation between two variables is given as the product of the covariance of the two variables with the variance of each of the two variables.

**Location**
Please provide the 
1. version 2018-10-12
2. Chapter 6
3. page 186
4. line number/equation number 3381/6.35

**Proposed solution**
Should include a square root over the two variances.

**Comment by chengsoonong** [comment]
Thank you.
