### ISSUE TITLE
Expression for the empirical Covariance matrix

### ISSUE THREAD

**Issue by gthd** [mml-book/mml-book.github.io#146]
**Describe the mistake**
Since the Covariance matrix is a D x D matrix, then should there been the Σ in the expression. I would expect to have only the multiplication to define the matrix.

**Location**
Please provide the 
1. version 2018-10-12
2. Chapter 6
3. page 188
4. line number/equation number 3415/6.41

**Proposed solution**
Remove the Σ from the expression.

**Additional context**
I am not sure if it a mistake or something that I have not understood correctly.

**Comment by chengsoonong** [comment]
Equation 6.41 looks correct to me. Each term (xx^\top) in the sum is a DxD matrix. Summing up over N matrices (each of size DxD) gives the covariance.
