### ISSUE TITLE
Error in expression for the variance of the mixture

### ISSUE THREAD

**Issue by gthd** [mml-book/mml-book.github.io#147]
**Describe the mistake**
When calculating the integral to prove the expression for the variance of the mixture, there is a typo that instead of p(x) there is p(z).

**Location**
Please provide the 
1. version 2018-10-12
2. Chapter 6
3. page 199
4. line number/equation number 3581/6.91

**Proposed solution**
Change the p(z) to p(x).

**Comment by chengsoonong** [comment]
Thank you. This derivation will be updated, as it is confusing.
