### ISSUE TITLE
Inconsistency in defining expectation value in Chapter 6

### ISSUE THREAD

**Issue by KamilDre** [mml-book/mml-book.github.io#149]
**Describe the mistake**
Equation 6.27 on page 183 and equation 6.30 on page 184 (discrete case) seem to be inconsistent. 

**Location**
1. Draft (2018-10-12) 
2. Chapter 6
3. Pages 183 & 184
4. Equations 6.27 & 6.30

**Proposed solution**
In equation 6.30, inside the sum,  should the probability p(x_d = i) be multiplied by the value i ? The value that the random variable is taking? This is implied by equation 6.27 with g(x) = x.

**Comment by ap8415** [comment]
+1, this appears to be a mistake - the probability should indeed be multiplied by i:
https://en.wikipedia.org/wiki/Expected_value#Finite_case
