### ISSUE TITLE
Some minor typos and suggestions for Chapter 4

### ISSUE THREAD

**Issue by alasdairtran** [mml-book/mml-book.github.io#152]
I had a look at Chapter 4. Some minor typos/style suggestions:

Version (2018-09-21)

* p93, final line: "Recall that a_ij be" -> "Recall that a_ij is" [or are you using the subjunctive mood?]
* p94, line 1954: "Before provide" -> "Before we provide" or "Before providing"
* p94, line 1957: "points already at" -> "points at" ["already" doesn't mean anything here]
* p97, line 1974: "product of the determinant" -> "product of the determinants"
* p100, line 2032: "and, its" -> "and its"
* p101, line 2060: Add a comma to the end
* p102, line 2078: "is eigenvalue" -> "is an eigenvalue"
* p103, Theorem 4.10: "obtain a S" -> "obtain an S"
* p104, Figure 4.4, central column, first graph: Missing value for `det(A_1)`
* p104, line 2123: "\lambda)2" -> "\lambda_2"
* p104, line 2124: "and the hence" -> "and hence"
* p105, line 2125: "This indicating" -> "This indicates"
* p105, line 2129: "Note, that" -> "Note that"
* p105, line 2131: "Note, that the while" -> "Note that while"
* p106, second line: "Key to understanding" -> "The key to understanding"
* p108, line 2183: "captures therefore" -> "therefore captures"
* p108, example 4.7 line 4: "came up up was" -> "came up was" [Actually the whole sentence sounds strange. 'Who' came up with the idea - the PageRank algorithm, or Larry/Sergey?]
* p108, example 4.7 line 8: "PageRank also take" -> "PageRank also takes"
* p109, line 2203: "6.6" -> "(Section 6.6)"
* p110, line 2233: "The following results parallels" -> "The following results parallel"
* p116, line 2326: "confront" -> "compare" ? ["confront" is a strange choice of verb]
* p116, line 2326: You never close the brackets after "(confront..."
* p117, line 2354: "Note, how" -> "Note how" [It feels very strange to have to pause after "Note". I think you probably can replace all "Note, " with "Note " in the book]
* p124, Example 4.12, second line: "analysing" -> "analyzing" [Are you using US or UK spellings?]
* p132, line 2556: "than the matrix" -> "then the matrix"
* p132, line 2584-2592: This paragraph consists of two very long sentences. Consider rewriting.
* p133, line 2618: "origin , but" -> "origin, but"
* p134, line 2636: "in, so called, tensors" -> "in so-called tensors"
* p134, line 2637: "low-rank approximation s" -> "low-rank approximation" ?
* p134, line 2637-9: It's difficult to parse this sentence. Maybe add a comma after "dimensional arrays".
* p134, Ex 4.1: "using the the first row" -> "using the first row"
* p134, Ex 4.3 and 4.7: "Let us compute" -> "Compute" ["Let us" seems to imply that the solution is right below]

**Comment by AnalogAldo** [comment]
Thank you, done. Some have phrasings are bi-balent btw Note, that vs Note that.
