### ISSUE TITLE
Determinants Problem 2.20

### ISSUE THREAD

**Issue by danielwo** [mml-book/mml-book.github.io#153]
**Describe the mistake**
I don't know if this is a mistake exactly, but I noticed you ask to prove a set of vectors is a basis using determinants without saying what a determinant is and then relying on making a connection like Determinant -> invertible -> full rank -> basis. Also you use notation P_1 and P_2 for describing change of basis matrices in the problem; are the numbers here meant to indicate which basis you are changing to? Something like P_{B \gets B'} or P_{B' \to B}?

**Location**
Please provide the 
1. version (bottom of page): 2018-09-21
2. Chapter: 2
3. page: 66-67
4. line number/equation number: 1520, problem 2.20

**Proposed solution**
Perhaps reference Chapter 4 or just ask to prove the vectors form a basis without determinants. Or leave it as is if you expect students to have some familiarity already (or for more advanced students? idk).

**Comment by mpd37** [comment]
Thanks for highlighting this. I added a forward reference to chapter 4, and we say that an example of how to show this is to use determinants. Other options are fine, too.

The indices in the matrices P_1 and P_2 do not indicate a change from basis 1 to basis 2.
