### ISSUE TITLE
Clarification of inverse for functions in identities of 5.5

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#154]
**Is your feature request related to a problem? Please describe.**
First time I read identities mentioned it was natural for me to think that function with inverse operator is an inverse of a function, and not inverse of an output. Apparently that's not the case in this context. I think it would be reasonable to add a line of clarification on impact of this ambiguity.

**Comment by mpd37** [comment]
The functions are supposed to be inverses (if they exist), not pre-images.

**Comment by mpd37** [comment]
Good point. Is this better?

![image](https://user-images.githubusercontent.com/5500569/47616153-98afc700-dac1-11e8-8080-637d4d9f99e5.png)

**Comment by Antymon** [comment]
Yes, much clearer in my opinion. Are there any restrictions on properties of f(X) worth mentioning?

**Comment by mpd37** [comment]
The implicit assumption is always that that inverse exists.

**Comment by Antymon** [comment]
I guess it's fair not mention that, thanks.
