### ISSUE TITLE
Typo in chapter 6 page 182 line 3318

### ISSUE THREAD

**Issue by versatran01** [mml-book/mml-book.github.io#156]
**Describe the mistake**
Typo in chapter 6 page 182 line 3318

**Location**
Please provide the 
1. version (bottom of page)

Draft (2018-10-12) from Mathematics for Machine Learning

2. Chapter

6

3. page

182

4. line number/equation number

3318

**Proposed solution**

leas to leads

**Additional context**

**Comment by chengsoonong** [comment]
Thanks
