### ISSUE TITLE
Chapter 4 Typo "ew" and others  line 2332

### ISSUE THREAD

**Issue by danielwo** [mml-book/mml-book.github.io#157]
**Describe the mistake**
Not sure if anyone caught this one: "we" is mispelled as "ew"
Also the entire line:
"than ew have then for the eigendecomposition"
is a bit confusing.

**Location**
Please provide the 
1. version (bottom of page): 2018-09-21
2. Chapter: 4
3. page: 116
4. line number/equation number: 2332

**Proposed solution**
Change "ew" to "we", consider changing the entire sentence. Maybe something like "than we did for eigendecomposition". Idk, I'm sure you can come up with better phrasing!

**Comment by Antymon** [comment]
Duplicate. Those were flagged before.
