### ISSUE TITLE
chapter 5: page 152

### ISSUE THREAD

**Issue by HorizonP** [mml-book/mml-book.github.io#161]
There is a rendering typo in the left column: there are some other words overlapping with "of the least squares". Please see the image below

![image](https://user-images.githubusercontent.com/8879138/47272503-c1c9d800-d554-11e8-835f-7d796986e3ba.png)

**Comment by mpd37** [comment]
we will fix layout issues in the final version

**Comment by mpd37** [comment]
we will fix formatting and layout issues in the final version
