### ISSUE TITLE
May "marginal p(x, z)" should be "marginal p(x)" ?

### ISSUE THREAD

**Issue by SmirkCao** [mml-book/mml-book.github.io#163]
**Describe the mistake**
> In the following, we will discuss the prior p(z), the marginal p(x, z) and the posterior p(z|x)
marginal p(x, z) should be p(x)?

**Location**
Please provide the 
1. version: Draft (2018-08-23)
2. Chapter: CH11
3. page: 342
4. line number: 6074

**Proposed solution**
A clear and concise description of what you would like to change.

**Additional context**
This just a question. Because I found some representation like marginal p(x, y). I am confused about this point.

I think that marginal distribution should have only one random variable and p(x, z) is a joint distribution.

**Comment by mpd37** [comment]
Thanks! This is a typo. It should read p(x) for the marginal. Will be fixed in next revision.

Does this remove the confusion?
