### ISSUE TITLE
"cross validation" cross referenced to different sections

### ISSUE THREAD

**Issue by SmirkCao** [mml-book/mml-book.github.io#166]
**Describe the mistake**
There are two locations use cross-referenced "cross validation", but they referenced to different sections of this book.

I think that P345L6139 should be "nested cross validation" for `to find good models`, this is from model selection view.
and for P346L6182 use "cross validation" from hyper-parameter selection view.

**Location**
Please provide the 
1. version: Draft(2018-08-23)
2. Chapter: 11
3. page: P346L6182 and P345L6139
4. --

**Proposed solution**
Just a suggestion

**Additional context**

**Comment by mpd37** [comment]
Good point. This needs fixing in the other chapters as well.

**Comment by chengsoonong** [comment]
Added reference to nested cross validation for choosing kernels and their parameters.
