### ISSUE TITLE
Chapter 5, Ambiguity in Equation 5.168.

### ISSUE THREAD

**Issue by adesam146** [mml-book/mml-book.github.io#168]
In the equation for the general term in a Taylor series, the letter _k_ is used both as the order of the derivative and an index in the summation.

![error_chapter_5_taylor_term](https://user-images.githubusercontent.com/20574978/47622133-3c689980-daf9-11e8-9753-351744009d26.png)

**Location**
1. Chapter 5
2. page 165
3. Equation 5.168

**Proposed solution**
The sum could be done over a_1 to a_k instead.

**Comment by mpd37** [comment]
Good catch. I changed the indices to i_1, ...., i_k:
![image](https://user-images.githubusercontent.com/5500569/50052204-77667100-0129-11e9-9301-93dbcc4947ca.png)
Does this make more sense now?

**Comment by adesam146** [comment]
Yeah, it's clearer now.
