### ISSUE TITLE
Unclear what example 2.22 demonstrates (incomplete example?)

### ISSUE THREAD

**Issue by jmhsi** [mml-book/mml-book.github.io#170]
**Describe the mistake**
Example 2.22 (pg. 52) is supposed to be of change of basis, but 2.114 and Example 2.23 (pg. 55) are much clearer/needed to understand Example 2.22

![screen shot 2018-10-29 at 1 07 44 pm](https://user-images.githubusercontent.com/12853718/47677197-b0e41c80-db7b-11e8-8ff6-6faa3f7412b9.png)

**Location**
Please provide the 
1. version (bottom of page) 2018-10-22
2. Chapter 2
3. page 52
4. line number/equation number 1332-1333

**Proposed solution**
Clarify what the example is supposed to be showing? Relocate it until after relevant discussion?

**Additional context**

**Comment by mpd37** [comment]
The idea of 2.22 is to give a preview of what we can do with a basis change. Its purpose is not to clarify or explain basis change because we haven't even discussed it at this point.
