### ISSUE TITLE
Typo in Chapter 6 page 199, Equation 6.91

### ISSUE THREAD

**Issue by tondji** [mml-book/mml-book.github.io#172]
**Describe the mistake**
In Chapter 6 on equation 6.91, in the first part of the sum you wrote p(z).
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version Draft (2018-10-12)
2. Chapter 6
3. page 199
4. line number/equation number Equation number  6.91

**Proposed solution**
Instead of p(z) in the first term , I think it is should be p(x)
A clear and concise description of what you would like to change.

**Additional context**

**Comment by mpd37** [comment]
Good catch. This entire section will need some re-writing. We are on it.
