### ISSUE TITLE
Typo in definition of Mean (Chapter 6)

### ISSUE THREAD

**Issue by mdpedersen** [mml-book/mml-book.github.io#173]
Version: Draft (2018-10-12).

Page 184, Eq. 6.30: missing factor ($i$) in the discrete case.

**Comment by jiayiliu** [comment]
Same comment, in the definition 6.4,  $x\inR^D$ is conflict with x in discrete domain if using $x_d=i$ directly.  Thus, it is preferred to use the Eq 6.27 notation as:

\sum_{x\in A} x_d p(x_d) if x_d in A event space.

**Comment by chengsoonong** [comment]
Thanks.
