### ISSUE TITLE
Unclosed parentheses in eq 9.46b

### ISSUE THREAD

**Issue by Amakri1020** [mml-book/mml-book.github.io#176]
**Describe the mistake**

Equation 9.46b has an unclosed parentheses

**Location**
1. Draft (2018-08-30)
2. Chapter 9
3. page 284
4. Equation number 9.46b

**Proposed solution**
Add a closing parentheses before the constant term

**Comment by mpd37** [comment]
This should be fixed in the current version

![image](https://user-images.githubusercontent.com/5500569/50762024-85189d80-1274-11e9-9e1e-848cedb43c87.png)
