### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by AmrKhalifa** [mml-book/mml-book.github.io#180]
**Describe the mistake**
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version (bottom of page)
Draft chapter (November 1, 2018)
2. Chapter 6
3. page 200
4. line number/equation number equation 6.82

**Proposed solution**
A clear and concise description of what you would like to change.
the covariance matricies must be multplied by a^2 , b^2 instead of a,b 

**Additional context**

**Comment by chengsoonong** [comment]
Thanks.
