### ISSUE TITLE
Typo (6.115b)

### ISSUE THREAD

**Issue by danielwo** [mml-book/mml-book.github.io#181]
**Describe the mistake**
Exponent isn't formatted correctly.

**Location**
Please provide the 
1. version (bottom of page): 2018-11-01
2. Chapter: 6
3. page: 207
4. line number/equation number: 6.115b

**Proposed solution**
(1-\mu)^(N-h) should be something like (1-\mu)^{(N-h)}

**Comment by chengsoonong** [comment]
Thanks.
