### ISSUE TITLE
Odd Verbiage Ch 6.7 remark

### ISSUE THREAD

**Issue by danielwo** [mml-book/mml-book.github.io#182]
**Describe the mistake**
Referencing previous section with future tense: "We will see in Section 6.5 that the density ..."

**Location**
Please provide the 
1. version (bottom of page): 2018-11-01
2. Chapter: 6
3. page: 220
4. line number/equation number: 3952

**Proposed solution**
Change "We will see" to "We saw" or something similar.

**Comment by chengsoonong** [comment]
Thanks.
