### ISSUE TITLE
Minor: incorrectly placed comma

### ISSUE THREAD

**Issue by nbgl** [mml-book/mml-book.github.io#184]
**Describe the mistake**
There is an unnecessary comma in the sentence:

> The Cholesky decomposition is used as a computationally more efficient and numerically more stable way to solve systems of equations that form symmetric positive definite matrices, than computing the inverse of such a matrix, and is thus used under the hood in numerical linear algebra packages.

The comma before ’than’ should not be there.

**Location**
1. version November 3, 2018
2. Chapter 4
3. page 111
4. line number 2210

**Proposed solution**
Remove the comma. Maybe split the whole sentence into two—it’s getting a bit long.

**Comment by AnalogAldo** [comment]
Done
