### ISSUE TITLE
Share the source 

### ISSUE THREAD

**Issue by Pensarfeo** [mml-book/mml-book.github.io#202]
Hi

Would you guys be willing to share the source (I guess latex) too?

I am making a presentation for a book reading event we run; we are all just not professionals, and we are simply trying to learn more about ML. For my presentation, I would like to make a pretty copy of the content of the book for my slides and copying theorems and definitions by hand has been taking ages.

Of course, we are fully opened to people about where the content for the presentation comes from!

Thanks in advance!

**Comment by mpd37** [comment]
Sorry, but we aren't allowed to do this.
