### ISSUE TITLE
Chapter2 Matrix Computation Mistake

### ISSUE THREAD

**Issue by JerryQiang** [mml-book/mml-book.github.io#203]
**Describe the mistake**
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version (bottom of page):2
2. Chapter:chapter02
3. page:47
4. line number/equation number:(2.83)

**Proposed solution**
second row of the matrix using  Gaussian elimination should be [0 1 3]，just computation.

**Additional context**
The book is really good,i like it.

**Comment by mpd37** [comment]
which chapter version do you have? the date should be at the bottom of every 2nd page.

**Comment by JerryQiang** [comment]
line number/equation number between 1254 and 1255

**Comment by JerryQiang** [comment]
Draft (2018-10-22), may this version

**Comment by JerryQiang** [comment]
Draft (2018-10-22), may this version? And line number/equation number between 1254 and 1255.

**Comment by mpd37** [comment]
got it. will be fixed with the next revision
