### ISSUE TITLE
chapter02:understanding of  injective

### ISSUE THREAD

**Issue by JerryQiang** [mml-book/mml-book.github.io#204]
**Describe the mistake**
If Φ is injective then it can also be “undone”, i.e., there exists a mapping
Ψ : W → V so that Ψ◦Φ(x) = x . 

**Location**
Please provide the 
1. version (bottom of page):2
2. Chapter:02
3. page:48
4. line number/equation number:1264

**Proposed solution**
I think you can't write in this way, because it is possible that some elements in W can't map in this way.
so you may name elements that can map W' - subspace of W. 

**Additional context**
I finish my BB.

**Comment by mpd37** [comment]
It just says that there exists a mapping W->V ...
If this mapping takes all elements in W that are in the image of $\Phi$ and maps it to their "pre-image", we are in good shape. If we want to be more precise, this would only be a mapping from a subspace of W.
I'm not sure whether this addresses the issue?

**Comment by mpd37** [comment]
I changed injective -> bijective because this is easier to explain without any restrictions to subspaces:
![image](https://user-images.githubusercontent.com/5500569/50052370-a5e54b80-012b-11e9-9645-842dfd48dbee.png)
Does this resolve this issue?

**Comment by mpd37** [comment]
Given I haven't heard back in a while, I'm closing this issue with the newest commit.
