### ISSUE TITLE
share the full pdf

### ISSUE THREAD

**Issue by cs-mailist** [mml-book/mml-book.github.io#205]
hi

could you share the full pdf file of the book, which i think is more convenient to read.

**Comment by mpd37** [comment]
Yes. It will come in a few weeks


On Nov 15, 2018 at 13:31, <cs-mailist<mailto:notifications@github.com>> wrote:


hi

could you share the full pdf file of the book, which i think is more convenient to read.

**Comment by cs-mailist** [comment]
could you share an intermediate version now?

i merged all the pdf files today,
but internal links don't work in the output pdf file,
and i don't know how to solve the problem.

**Comment by mpd37** [comment]
Not right now - chapters are changing daily at the moment. Once there's a stable version, we'll put it up
