### ISSUE TITLE
Some more typos in Chapter 4

### ISSUE THREAD

**Issue by tbuehler** [mml-book/mml-book.github.io#207]
Version: 2018-11-03

Page 105, line 2121: “the square grid of points are contained” -> “is contained”
Page 107, line 2141: additional “the” between “that” and “while”
Page 107, line 2158: double “space”
Page 111, line 2213: bracket missing in reference to section 6.5
Page 113, line 2265: “must has” -> “must have”
Page 115, line 2289: “.” or “:” missing
Page 118, line 2336: closing bracket missing
Page 121, end of example 4.10: closing bracket missing
Page 121, line 2377: “Computing the SVD (..) its existence” - wrong grammar
Page 123, between (4.90) and (4.91): wrong grammar
Page 123, line 2402: wrong grammar
Page 124, Example 4.11 after (4.100): “due to (..) implies” -> wrong grammar
Page 126, line 2452: “to” missing after “equal”
Page 128, line 2489-2491: wrong grammar
Page 130, Figure 4.11 caption: “in the a 6-rank approximation” -> “a” too much
Page 131, first line: double “and”
Page 134, line 2584: double “a unique”
Page 135, line 2602: gap between text and reference missing
Page 135, line 2642: ) missing after “n x m”
Page 136, Exercise 4.1: double “ the”
Page 136, line 2661: should be“the following four matrices if they are”

**Comment by AnalogAldo** [comment]
Thank you very much, done!
