### ISSUE TITLE
Small mistakes in Chapter 6

### ISSUE THREAD

**Issue by tbuehler** [mml-book/mml-book.github.io#211]
**CHAPTER 6
Version 2018-11-14**

_Page 180, line 3201:_ “the” missing in front of second “probability”

_Page 181, line 3241:_ “a Borel algebras” -> “Borel algebras”

_Page 182, first side note:_ closing bracket wrong

_Page 186, eq. (6.26):_ expected value is used here but is only defined on Page 188, Definition 6.3

_Page 187, line 3371:_ additional “the”

_Page 196, last side note:_ $0 \leftrightarrow x=0$ should be $cov(x,x)  = 0 \leftrightarrow x=0$  

_Page 208, line 3752:_ Reference (Agarwal and III, 2010) should be (Agarwal and Daumé III, 2010)

_Page 214, Example 6.15:_ comparing (6.128) with the general form in (6.126), there is an additional factor $n_0$ in the first term in the exponent of (6.128)

_Page 222, line 4002:_ “probabilisitic” -> “probabilistic”

_Page 223, line 4050:_ “is” -> “as”

**Comment by chengsoonong** [comment]
Thanks for the careful reading.
