### ISSUE TITLE
A Typo in Example 2.7 

### ISSUE THREAD

**Issue by kudo23** [mml-book/mml-book.github.io#213]
**Describe the mistake**
It should be "the third column" but not "the third pivot column".

**Location**
1. version (Draft 2018-10-22)
2. Chapter 2.3.2
3. page 31
4. Between equation 2.48 and 2.49, there are 18 lines, and the typo is in line 14

**Proposed solution**
A clear and concise description of what you would like to change.

**Additional context**

**Comment by mpd37** [comment]
Thanks! Good catch. Will be fixed in the next revision.
