### ISSUE TITLE
Clarification on applicability of chain rule in vector calculus Chapter 5

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#215]
**Is your feature request related to a problem? Please describe.**

After reading chapter 5/lecture/notes I naively believed that chain rule is of universal applicability in vector calculus. It took me considerable amount of time to get to this line of Wikipedia article "The chain rule applies in some of the cases, but unfortunately does not apply in matrix-by-scalar derivatives or scalar-by-matrix derivatives". Not being aware of this is rather wide-spread issue among audience and, unfortunately, beyond.

**Describe the solution you'd like**
Please incorporate that note in visible way in the book. It would be even better to know what approaches are recommended in such, not that rare, cases.

**Additional context**
Line quoted from https://en.wikipedia.org/wiki/Matrix_calculus

**Comment by Antymon** [comment]
Interesting, although I have more tangible issue with application of chain rule in following example:
![image](https://user-images.githubusercontent.com/641005/50392693-5238ba80-0748-11e9-8454-83bbcc345f8e.png)
So multiplication of those at the bottom will yield a matrix. I heard a suggestion I should use double dot product between partial derivatives rather than  regular matrix multiplication, but I see no justification why I would need to do so (aside from not knowing what the definition of that operation is). If application of chain rule is correct then where is the problem in the presented example?

**Comment by mpd37** [comment]
dg/dh is 1x(NxN) or 1x(N^2) if you vectorize h. 
dh/da is NxNx1 or (N^2)x1 if you vectorize h

Using the vectorized versions makes it easier, and you will get a 1x1 results because we just need to talk about an inner product.
If you don't use the vectorized version, you will need to sum out both dimensions.

**Comment by Antymon** [comment]
Looking at book examples, shouldn't then 5.107 be NxNx1?

**Comment by mpd37** [comment]
Yes, this is correct. Having thought of this, I removed this line in the chapter because it is not needed later on. Leaving it in (with NxNx1) would not be overly instructive.
