### ISSUE TITLE
Chapter 4, Theorem 4.21 is incomplete

### ISSUE THREAD

**Issue by empet** [mml-book/mml-book.github.io#217]
The Theorem 4.21 states that the matrix P in the spectral factorization of a symmetric matrix,  S=PDP^T, consists in orthogonal eigenvectors, but its columns should be orthonormal vectors (i.e. pairwise othogonal and of norm 1).  

Here is a notebook that illustrates that the stated  decomposition is  false:
[http://nbviewer.jupyter.org/gist/empet/0281fad0a664bc470c8f6c045a9b5503](http://nbviewer.jupyter.org/gist/empet/0281fad0a664bc470c8f6c045a9b5503)

**Location**
 Chapter 4
 page 114
Theorem 4.21

**Proposed solution**
I suggest to formulate it as follows:

**Theorem 4.21.** *Any symmetric matrix, $S\in \mathbb{R}^{n\times n}$, can be decomposed as $S=PDP^T$, where $D$ is the diagonal matrix of its eigenvalues, and $P$ is the matrix whose columns are the orthonormal  eigenvectors corresponding to the eigenvalues recorded in the same column in D.*

**Comment by AnalogAldo** [comment]
That is correct, and we have restructured this and the previous section to have theorems/definitions using a clear distinction between orthonormal (normalised to 1) and orthogonal vectors.
