### ISSUE TITLE
Chapter 4, The eigen-decomposition of a symmetric matrix isn't  always its SVD

### ISSUE THREAD

**Issue by empet** [mml-book/mml-book.github.io#218]
In

- Chapter 4
- page 121
- line: 2374 
is stated:  *the SVD of symmetric matrices is their eigenvalue decomposition*.

The singular values are positive or zero, while a symmetric matrix can have negative eigenvalues, too.
Example: this eigen-decomposition of a symmetric matrix S:

![eigen-decomp](https://user-images.githubusercontent.com/3627253/50057615-b02c3780-0175-11e9-9ff2-90b45b238093.png)

cannot be its SVD.

ONLY *The eigenvalue decomposition of a (symmetric) positive definite  matrix  coincides with its singular value decomposition*.

This Jupyter Notebook [http://nbviewer.jupyter.org/gist/empet/77e9d32348a6c24ea8406f273f8b1014](http://nbviewer.jupyter.org/gist/empet/77e9d32348a6c24ea8406f273f8b1014) 
illustrates how we can get the SVD from the eigenvalue decomposition of a symmetric matrix that has negative eigenvalues.

**Comment by AnalogAldo** [comment]
Point taken. We have restricted the case to SPD matrices to make this watertight.
