### ISSUE TITLE
Chapter 6, A linear combination of Gaussian distributions that isn't a mixture

### ISSUE THREAD

**Issue by empet** [mml-book/mml-book.github.io#219]
Exercise 6.1 gives a linear combination of Gaussian distributions with the weights 1 and 1.5. This isn't a mixture, as it's stated,  because the sum 1+1.5 is different from 1.

**Location**
1. version: November 14, 2018
2. Chapter 6
3. page 223
4. line number 4028

**Comment by chengsoonong** [comment]
Would the wording weighted mixture be better?

**Comment by empet** [comment]
@chengsoonong  Only for p_1, p_2>0, p_1+p_2=1, the function f(x,y)=p_1 f_1(x,y)+p_2 f_2(x,y), where f_1, f_2 are the pdfs of the given Gaussian distributions, is also a pdf, because its integral over R^2 is p_1+p_2.  Hence only in this case the exercice makes sense.

**Comment by chengsoonong** [comment]
Ah. Misunderstood your first comment. What you say makes sense.
