### ISSUE TITLE
Minor typo Chpt.4

### ISSUE THREAD

**Issue by ATanggara** [mml-book/mml-book.github.io#221]
Looked at previous chapter 4 issues, did not found this reported.

**Location**
version (2018-11-03)
Chapter 4

1. page 97 - last line on the page in the example box
**Describe the mistake**
"...**b**,**g** were a1 and lie along..."
**Proposed solution**
"...**b**,**g** were linearly independent and lie along..."

2. page 106 - line number 2133
subscripting typo
**Describe the mistake**
&lambda;<sub>1</sub> = 1 = &lambda;)2
**Proposed solution**
&lambda;<sub>1</sub> = 1 = &lambda;<sub>2</sub>

3. page 107 - bottom of page
**Describe the mistake**
figure description and example title is not on the same page with the figure and example
**Proposed solution**
move example title and figure description to the next page

4. page 110 - Example 4.7, second sentence
**Describe the mistake**
"...Sergey Brin in 1996, came up up was that..."
**Proposed solution**
"...Sergey Brin in 1996, was that..."

5. page 110 - Example 4.7, fifth sentence
sentence structure
**Describe the mistake**
"PageRank also take the importance of the website into account that links to a website to a<sub>i</sub>."
**Proposed solution**
"PageRank also take into account the importance of the website that links to the website a<sub>i</sub>."

**Comment by AnalogAldo** [comment]
Thank you for these:
1. Done.

2. Done.

3. Done (this is a latex compile issue we have have only limited control over in the non-print version)

4. Done.

5. Done.
