### ISSUE TITLE
chapter 01 line 802 a space is needed

### ISSUE THREAD

**Issue by seungheonbaek** [mml-book/mml-book.github.io#225]
**Describe the mistake**
vector calculusand details 
-> vector calculus and details
A space is needed between "calculus" and "and".

**Location**
Please provide the 
1. version (bottom of page) : Draft (2018-12-24)
2. Chapter : 01
3. page : 17
4. line number/equation number : line 802

**Proposed solution**
vector calculusand details 
-> vector calculus and details
A space is needed between "calculus" and "and".

**Additional context**
-

**Comment by mpd37** [comment]
thanks - will be fixed in next revision
