### ISSUE TITLE
Chapter 07, Example 7.1, Equation 7.8 error in gradient

### ISSUE THREAD

**Issue by antoinetlc** [mml-book/mml-book.github.io#226]
**Describe the mistake**
In Example 7.1, equation 7.8 of Chapter 7, there is a missing factor 2 in the gradient of the function f.

**Location**
Please provide the 
1. version (bottom of page) : Draft chapter (November, 12, 2018)
2. Chapter 7
3. page 227
4. line number/equation number : Equation 7.8

**Proposed solution**
In equation 7.8 the gradient of f should be equal to **2***[[2, 1], [1, 20]]*[x_1, x_2] - [5, 3] (the factor 2 in bold is currently missing).

**Comment by chengsoonong** [comment]
Thanks for the careful reading.
