### ISSUE TITLE
Chapter 05 error in figure 5.4

### ISSUE THREAD

**Issue by victorBigand** [mml-book/mml-book.github.io#227]
The figure 5.4 with the representation of the function f(x) = cos(x) + sin(x) in black gives 0 in x=0 but i think it should give 1.

**Location**
Please provide the 
1. version 2018-12-24
2. Chapter 5
3. Page 147
4. figure 5.4 (top of the page)

Thank you for this amazing book

**Comment by chengsoonong** [comment]
I think the figure is correct, and does show that f(0) = sin(0)+cos(0) = 1. The horizontal blue dashed line is at y=1. It can be misunderstood to be the y=0 axis I'm guessing.

**Comment by mpd37** [comment]
The horizontal blue line is the 0th-order Taylor polynomial, which is constant 1. We didn't draw a line for y=0 because this would be more confusing than helpful.
