### ISSUE TITLE
Small typo Fig 4.1

### ISSUE THREAD

**Issue by wilfreddesert** [mml-book/mml-book.github.io#232]
**Describe the mistake**
A typo in the word 'diagonalization'. 'Diagonlization' is written instead. 

**Location**
Please provide the 
1. 03-11
2. Chapter 4
3. page 95
4. Figure 4.1

**Proposed solution**
Correct the typo in 'diagonalization'

**Comment by AnalogAldo** [comment]
Thank you and done.
