### ISSUE TITLE
A issue with formula 4.88

### ISSUE THREAD

**Issue by 17SKYE** [mml-book/mml-book.github.io#233]
**Describe the mistake**
> <a href="https://www.codecogs.com/eqnedit.php?latex=A$\mathbf{A}^\top$&space;=(U\Sigma&space;$\mathbf{U}^\top$)$\mathbf{(U\Sigma&space;$\mathbf{U}^\top$)}^\top$=U$\mathbf{\Sigma}^\top$&space;$\mathbf{V}^\top$V\Sigma$\mathbf{U}^\top$" target="_blank"><img src="https://latex.codecogs.com/gif.latex?A$\mathbf{A}^\top$&space;=(U\Sigma&space;$\mathbf{U}^\top$)$\mathbf{(U\Sigma&space;$\mathbf{U}^\top$)}^\top$=U$\mathbf{\Sigma}^\top$&space;$\mathbf{V}^\top$V\Sigma$\mathbf{U}^\top$" title="A$\mathbf{A}^\top$ =(U\Sigma $\mathbf{U}^\top$)$\mathbf{(U\Sigma $\mathbf{U}^\top$)}^\top$=U$\mathbf{\Sigma}^\top$ $\mathbf{V}^\top$V\Sigma$\mathbf{U}^\top$" /></a>

should be:
> <a href="https://www.codecogs.com/eqnedit.php?latex=A$\mathbf{A}^\top$&space;=(U\Sigma&space;$\mathbf{U}^\top$)$\mathbf{(U\Sigma&space;$\mathbf{U}^\top$)}^\top$=U\Sigma&space;$\mathbf{V}^\top$&space;V&space;$\mathbf{\Sigma}^\top$&space;$\mathbf{U}^\top$" target="_blank"><img src="https://latex.codecogs.com/gif.latex?A$\mathbf{A}^\top$&space;=(U\Sigma&space;$\mathbf{U}^\top$)$\mathbf{(U\Sigma&space;$\mathbf{U}^\top$)}^\top$=U\Sigma&space;$\mathbf{V}^\top$&space;V&space;$\mathbf{\Sigma}^\top$&space;$\mathbf{U}^\top$" title="A$\mathbf{A}^\top$ =(U\Sigma $\mathbf{U}^\top$)$\mathbf{(U\Sigma $\mathbf{U}^\top$)}^\top$=U\Sigma $\mathbf{V}^\top$ V $\mathbf{\Sigma}^\top$ $\mathbf{U}^\top$" /></a>

**Location**

1. Chapter 4
2. Page 120
3. Formula 4.88

**Comment by AnalogAldo** [comment]
Well spotted, and now corrected.
