### ISSUE TITLE
Problematic statement on diagonalization of matrices with distinct eigenvalues

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#235]
**Describe the mistake**

> Theorem 4.11 (Hogben (2006)). Consider a square matrix A ∈ Rn×n
> with distinct eigenvalues λ1, . . . , λn and corresponding eigenvectors x1, . . . , xn.
> Then the eigenvectors x1, . . . , xn are linearly independent.

> Theorem 4.11 tells us when
> A is diagonalizable by having n independent eigenvectors, namely in only
> those cases where A has n distinct eigenvalues.

What about symmetric matrices of rank n-2. They are singular with repeated eigenvalue 0. It was stated that all symmetric matrices are diagonalizable which is contradicting with the lower quote. It feels lower quote is over-interpretation of theorem. Theorem seems to imply independence providing distinct eigenvalues but not converse.

**Location**
Please provide the 
1. version 2018-11-03
2. Chapter 4
3. page
4. line 2253

**Comment by AnalogAldo** [comment]
This ambiguity should have now been resolved with the reordering of the theorem presentations and the expanded explanation.
