### ISSUE TITLE
chapter02: Typo while adding two equations

### ISSUE THREAD

**Issue by wasimaftab** [mml-book/mml-book.github.io#238]
**Describe the mistake**
addition of equations (1) and (2) in example 2.2 should yield 2x1+3x3=5. x1 is missing.

**Location**
Please provide the 
1. version (2018-10-22)
2. Chapter 02
3. page 20
4. equation number 2.5

**Proposed solution**
just type x1 where it is missing.

**Additional context**

**Comment by mpd37** [comment]
I don't see where x1 is missing. Can you elaborate? (2.5) and (2.4) are different systems.
