### ISSUE TITLE
Chapter04: Wrong matrix dimension in eq. 4.19

### ISSUE THREAD

**Issue by mhmoodlan** [mml-book/mml-book.github.io#241]
**Problem**
In equation 4.19, matrix A has wrong number of columns.

**Proposed solution**
Matrix A should have dimensions of `A ∈ R^(a×l)` instead of `A ∈ R^(a×k)` so that the multiplication is permissible.

**Location**
1. version: Draft (2019-01-22)
2. Chapter: 4
3. page: 104
4. line number: 2199/related equation number: 4.19

**Comment by mpd37** [comment]
This should fix it:
![image](https://user-images.githubusercontent.com/5500569/53122526-b6140f80-354e-11e9-91a8-4f263e4b0c2b.png)

**Comment by mpd37** [comment]
Let's leave this issue open until the pdf is updated. I'll close it with the corresponding commit.
