### ISSUE TITLE
Chapter 06 Minor Typo in Joint probability

### ISSUE THREAD

**Issue by JiteshSindhare** [mml-book/mml-book.github.io#244]
**Describe the mistake**

1.) in (6.9) P(X = xi; Y = **yi**) 
and in line number 3390 same.

2.)  there is an extra " random" written here => If we look at the angle  **between random two random** variables X; Y , -

**Location**
Please provide the 
1. Draft (2019-01-29)
2. Chapter 6
3. page- 181 and 182 , 199
4. equation number (6.9) and line number 3390 , line number 3734

**Proposed solution**

1.) it should be P(X=xi ;  Y= **yj**)

2.) it should be - If we look at the angle  **between two random** variables X; Y ,

**Additional context**

**Comment by chengsoonong** [comment]
Thanks.
