### ISSUE TITLE
Chapter 6: Example 6.6 & Figure 6.9 inconsistent?

### ISSUE THREAD

**Issue by kromydas** [mml-book/mml-book.github.io#247]
**Describe the mistake**
It seems like the use of x1 and x2 in Figure 6.9 is inconsistent with the description in Example 6.6. Example 6.6 refers to Figure 6.9, but example 6.6 uses x and y where as Figure 9 uses x1 and x2.

**Location**
Please provide the 
1. version: Draft (2019-01-290
2. Chapter: 6
3. page: 203
4. Line number is N/A

**Proposed solution**
I think (?) Figure 6.9 should probably use x and y instead of x1 and x2.

**Additional context**

**Comment by chengsoonong** [comment]
Changed the example to $x_1$ and $x_2$.
