### ISSUE TITLE
Chapter 6: Section 6.5.3 (M >= M)?

### ISSUE THREAD

**Issue by kromydas** [mml-book/mml-book.github.io#248]
**Describe the mistake**
There is a condition described for an mxn matrix A. "where M >= M"

**Location**
Please provide the 
1. version: Draft (2019-02-29)
2. Chapter: 6
3. page: 207
4. line number/equation number: no line numbers listed in this area, but it's located right before equation (6.89)

**Proposed solution**
It seems that "M >= M" should read "M >= N"

**Additional context**

**Comment by chengsoonong** [comment]
Thanks.
