### ISSUE TITLE
after eq. 3.11 : "This implies that the inner product is uniquely determined through A." ???

### ISSUE THREAD

**Issue by chriswebers** [mml-book/mml-book.github.io#25]
According to eq. 3.11 the inner product <x, y> (LHS) is defined by both the co-ordinates of x and y (\hat{x} and \hat{y}) and A (RHS).

**Comment by mpd37** [comment]
I believe that the function <., .> is uniquely determined by A if A_ij = <b_i, b_j> where the b_i are basis vectors. I omitted the x,y in the sentence, which I hope resolves this issue.
