### ISSUE TITLE
Chapter 3 (typo in section 3.7.2)

### ISSUE THREAD

**Issue by kromydas** [mml-book/mml-book.github.io#250]
**Describe the mistake**
The first sentence of the paragraph says “higher-dimensional” and I believe (?) that it should say “lower-dimensional”

**Location**
Please provide the 
1. version: Draft (2018-09-21)
2. Chapter: 3
3. page: 82
4. 1773

**Proposed solution**
Change  “higher-dimensional” to “lower-dimensional”

**Additional context**

**Comment by mpd37** [comment]
Good catch! This will be fixed with the next revision.
