### ISSUE TITLE
Chapter 4 (typo in section 4.2)

### ISSUE THREAD

**Issue by kromydas** [mml-book/mml-book.github.io#251]
**Describe the mistake**
The first sentence at the top of page 109 looks truncated. It starts with “ orem states….”

**Location**
Please provide the 
1. version: Draft (2019-01-22)
2. Chapter: 4
3. page: 109
4. line number/equation number: 2291

**Proposed solution**
The first sentence at the top of page 109 should start as "Theorem 4.11 states"

**Additional context**

**Comment by mpd37** [comment]
I can 't find this. Are you sure page and line number are correct?

**Comment by mpd37** [comment]
I assume this is fixed with the recent commit.
