### ISSUE TITLE
Chpt.7 - Incompatible/inconsistent Vector Dimension

### ISSUE THREAD

**Issue by ATanggara** [mml-book/mml-book.github.io#252]
**Describe the mistake**
Example 7.1, equation 7.8, \nabla f([x_1, x_2]) should be in 1\*2 dimension to be later transposed to 2\*1 dimension (as written in equation 7.6), so that it is compatible for subtraction from x_i.
This would also make this gradient of a function (which is a Jacobian) consistent with the definition of derivative of a multivariate function in equation 5.56 (and Jacobian matrix in equation 5.57), where the partial derivative with respect to each variable is formed as a row instead of a column.

**Location**
Please provide the 
1. version 2018-11-12
2. Chapter 7
3. page 227
4. equation number 7.8

**Proposed solution**
\nabla f ([x_1, x_2]) = [x_1, x_2]^T [[2, 1], [1, 20]] - [5, 3]^T

**Comment by chengsoonong** [comment]
Thanks.
