### ISSUE TITLE
Draft 2019-02-11 Page 33 Line 698: Please learn that vs. which

### ISSUE THREAD

**Issue by shawnberry** [mml-book/mml-book.github.io#253]
Hello Authors/Editors,

You are writing an excellent book.  I have accumulated several small errata that I can overlook, but Page 33 Line 698 has a major error and should read "The the columns on augmented A that contain -1 as pivots ..."  To be precise, remove ", which" and type "that" with no comma.

Explanation that you can verify with Max Morenberg's wonderful 'Doing Grammar' (2nd or 3rd edition):
The construction "Noun that" starts a restrictive relative clause, which takes a subset.  Here's an example. Dogs that bite scare people.  Of course, not all dogs bite so we use "that" to indicate the subset.
In contrast, the construction "Noun, which" starts a non-restrictive relative clause, which does NOT take a subset.  Here's another doggy example.  Dogs, which are canines, were domesticated tens of thousands of years ago. 

Best,
Shawn
shawnberry121@gmail.com
twice scored 800 on GMAT-CAT, which includes Sentence Correction
;-)

**Comment by mpd37** [comment]
thanks for catching this. will be fixed in next revision.
