### ISSUE TITLE
Draft 2019-02-11 Page 36 Within Example 2.10 Groups (R mxn is NOT a group)

### ISSUE THREAD

**Issue by shawnberry** [mml-book/mml-book.github.io#254]
Using either your definition of a Group (line 761) or the more precise I. N. Herstein 'Topics in Algebra' (2nd Edition) pages 27-28 definition, R mxn is NOT a Group, much less an abelian group.

Using your definition on Page 36 Line 761: Neutral element (Identity element): There exists e in G such that for all x in G, xe = ex = x.  Of course if you allow for a minute your conjecture that there is a left-neutral element I-m  and a right-neutral element I-n, then you FAIL Closure.  That is, for all x, y in G, xy and yx are in G.  Of course, I-m and I-n don't have the same shape and CANNOT be added.

Shawn Berry

BS, Mathematics
MS, Mathematics (passed PhD qualifying exams in Abstract Algebra, Real Variables, and Mathematical Statistics
Passed 7 Actuarial exams (roughly the equivalent of MS Statistics)
Duke MBA
MS, Computer Science (in progress)

shawnberry121@gmail.com
Landline: 4152594662
Mobile: 6507767373
Landline rings to Mobile
Available 8:00 am to 8:00 pm Pacific

**Comment by mpd37** [comment]
Read the example again. You can close the issue yourself if you are happy. We specify that the operation is + and not times.

**Comment by shawnberry** [comment]
Hi Mark,

You cannot add or multiply a nxn matrix with a mxm.  I hope you understand that last sentence.  I am surprised that none of the three of has even a Bachelor of Science in Mathematics, much less a Master of Science in Mathematics.  Again, determining whether something constitutes a Group is Day 1 stuff.  Also, here’s a hint: the identity element, which you are calling the neutral element, is unique.  Can you prove it?  If you can’t, you probably shouldn’t try to write a book about Mathematics.

Best,
Shawn

Landline: 4152594662
Mobile: 6507767373
Landline rings to Mobile

**Comment by shawnberry** [comment]
Marc,

Yes, (R mn, +) is a Group.  The confusion arose from your note to the immediate right that “I n is a right-neutral element and I m is a left-neutral element.  A set with both I n and I m does not satisfy Closure.  

Also, your Group immediately below (R nn, *) should be limited to non-singular matrices.  Using “the set of nxn matrices”, as you wrote, has elements without inverses.  The “if” later is not enough to correct matters.

Best,
Shawn

Landline: 4152594662
Mobile: 6507767373
Landline rings to Mobile

**Comment by mpd37** [comment]
There are multiple points here:

a) (R^{mxn}, +) is a group.
b) I see that the comment in the margin is misleading, and I will remove this in the revision.
c) The part with (R^{n x n), *) and the inverse matrices will be made a bit clearer.

**Comment by shawnberry** [comment]
Hi Marc,

(R^{nxn} that are non-singular, *) is a Group.

Best,
Shawn

Landline: 4152594662
Mobile: 6507767373
Landline rings to Mobile

**Comment by mpd37** [comment]
Yes, this is the general linear group, which immediately follows Example 2.10 (see Definition 2.7)
