### ISSUE TITLE
Notation clarification request for chapter 5

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#255]
**Is your feature request related to a problem? Please describe.**
When in wild, novice reader can get easily confused with differences of matrix calculus notations.

**Describe the solution you'd like**
I would appreciate explicit statement that book uses numerator layout for matrix calculus, that denominator layout exists and brief information on conversion.

In particular I think chain rule can be used as an example by being written in reverse order, then via properties of matrix non-commutativity as well as transposition of product, chain rule could be shown equivalent despite order under assumption of respective notation.

**Comment by mpd37** [comment]
Would this work?
![image](https://user-images.githubusercontent.com/5500569/53512571-faf1f600-3aba-11e9-8810-2d0aba9336a2.png)

**Comment by mpd37** [comment]
The chain-rule will be very difficult when you work with tensors. Transposing a tensor is not really defined (transpose only for vectors/matrices), and you will need to be specific what dimensions to permute. Alternatively, you re-shape things.

**Comment by Antymon** [comment]
Thanks. That's great. As for examples... I have seen for instance backprop written in this way:

![image](https://user-images.githubusercontent.com/641005/53518465-00eed380-3ac9-11e9-9ac8-735daa46e316.png)

But perhaps that would be too much of diverging from what the book is about...

**Comment by mpd37** [comment]
Yes - it's a bit too tangential. I'll add the remark with the next push. Thanks for highlighting this!
