### ISSUE TITLE
Typo in Chapter 2

### ISSUE THREAD

**Issue by armasog** [mml-book/mml-book.github.io#257]
**Describe the mistake**
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version (bottom of page) Draft (2019-02-11)
2. Chapter 2
3. page 24
4. line number/equation number 582

**Proposed solution**
Inverse is misspelled

**Additional context**

**Comment by mpd37** [comment]
good catch! will be fixed in the next revision
