### ISSUE TITLE
Add Universal Quantifier to notation

### ISSUE THREAD

**Issue by armasog** [mml-book/mml-book.github.io#258]
**Is your feature request related to a problem? Please describe.**
I am not very familiar with mathematical notation.

**Describe the solution you'd like**
Add the universal quantifier - as shown for the first time in equation 2.18 on page 24 to the Notation section of the book. 

**Describe alternatives you've considered**

**Additional context**
It is hard to find the meaning of a symbol online because it is hard to type if you don't know what it's called - therefore I think we should err on the side of including too much in the notation section rather than too little.

**Comment by mpd37** [comment]
Yes, we should add \forall and \exists to the table of symbols
