### ISSUE TITLE
Typo chapter 2

### ISSUE THREAD

**Issue by armasog** [mml-book/mml-book.github.io#259]
**Describe the mistake**
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version (bottom of page) Draft 2019-02-11
2. Chapter 2
3. page 61
4. line number/equation number 1143

**Proposed solution**
Clarify the bullet. I'm not sure what is meant by the sentence - I think it may be missing a word. 

**Additional context**

**Comment by mpd37** [comment]
It's a three-way equivalence: injective <-> surjective <-> bijective

Does this make more sense now?

**Comment by armasog** [comment]
Yes it does! I would explicitly say "three-way equivalence" like you did in your reply which cleared it up for me.
