### ISSUE TITLE
Typo in Chapter 5

### ISSUE THREAD

**Issue by shengxue** [mml-book/mml-book.github.io#262]
**Describe the mistake**
The equation should be:  d**K**/d**R** = **R**<sup>(N x N) x (M x N )</sup>, instead of d**K**/d**R** = **R**<sup>(N x N) x (M x M )</sup>

**Location**
1. version (bottom of page):  2019-02-11
2. Chapter 5
3. page 158
4. equation number 5.93

**Comment by mpd37** [comment]
good catch!

**Comment by shengxue** [comment]
Can you explain why in first 3 lines of page 157

> For example, if we compute the gradient of an m × n matrix A with respect to a p × q matrix B, the resulting Jacobian would be (p×q)×(m×n) ?

It looks to me that it should be (m x n ) x (p x q).  what's the dimension of the resulting Jacobian's transpose?

**Comment by mpd37** [comment]
This is a bit tricky because we cannot directly transpose a 4-dimensional tensor. But you could reshape a matrix into a long vector. Then your Jacobian would be (mn) x (pq) and you have a normal matrix that you could transpose.
