### ISSUE TITLE
Chapter 3: More general definition of Inner Product Bilinearity

### ISSUE THREAD

**Issue by ATanggara** [mml-book/mml-book.github.io#263]
**Describe the mistake**
Slightly different definition of Bilinearity of Inner Product taken from discussion on https://math.stackexchange.com/questions/85660/bilinearity-what-does-it-mean
Useful in proving equation 3.11

**Location**
Please provide the 
1. version 2018-09-21
2. Chapter 3
3. page 71
4. equation number 3.7 and 3.8

**Proposed solution**
$\Omega (\lambda x + \psi y , z) = \lambda \Omega (x, z) + \psi \Omega (y, z)$
$\Omega (x, \lambda y + \psi z) = \lambda \Omega (x, y) + \psi \Omega (x, z)$
where
$\lambda , \psi$ are real number

**Comment by mpd37** [comment]
Good suggestion - this is then also consistent with linear mappings from chapter 2. I'll change this with the next revision.
