### ISSUE TITLE
Chapter 4 Typos

### ISSUE THREAD

**Issue by armasog** [mml-book/mml-book.github.io#264]
**Describe the mistake**
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version (bottom of page) Draft February 6, 2019
2. Chapter 4

**Proposed solution**
Page 128, end of example 4.12 - missing word at the end of sentence
page 134, line 2710 - should read "lengthened by the difference matrix is determined by its" (add by)
page 134, theorem 4.25 - the word "and" is repeated

**Comment by mpd37** [comment]
thanks! will be fixed in the next revision
