### ISSUE TITLE
Chapter 9 Grammatical Error, Incorrect pdf Bookmark, Figure reference

### ISSUE THREAD

**Issue by ATanggara** [mml-book/mml-book.github.io#265]
1. Bookmarking  

**Describe the mistake**
Bookmark in chapter 9 shows chapters of chapter 5

2. Grammatical error  

**Describe the mistake**
"... 2, 5, 6, and 7 to solving linear regression ..."
"to solve" instead of "to solving"

**Location**
Please provide the 
1. version December 16, 2018
2. Chapter 9
3. page 289
4. line number 5546

**Proposed solution**
"... 2, 5, 6, and 7 to solve linear regression ..."

3. Figure name mistake  

**Describe the mistake**
"... Figure 9.3(a) shows ..."
description fits Figure 9.2(a) instead

**Location**
Please provide the 
1. version December 16, 2018
2. Chapter 9
3. page 292
4. Example 9.1, last line

**Proposed solution**
"... Figure 9.2(a) shows ..."

**Comment by mpd37** [comment]
thanks. will be fixed with the next revision.
