### ISSUE TITLE
Example 4.12 numerical errors

### ISSUE THREAD

**Issue by Sand-Deep** [mml-book/mml-book.github.io#267]
I think Example 4.12 on pg 127 could use a bit of attention. 

I think the normalisation of the third column of $A^{T}A$ should be 1/sqrt(6) and not 1/sqrt(2)

Also, it is a little confusing for me why you compute AA^{T} at step 1 rather than A^{T}A.

Maybe more of the steps could just be written out in this example.

**Comment by mpd37** [comment]
could you check the current version, please? there have been some significant changes yesterday.

**Comment by mpd37** [comment]
Example 4.13 in the current version

**Comment by mpd37** [comment]
thanks for finding this! should be fixed in a minute.
