### ISSUE TITLE
Example 4.13 missing corrections

### ISSUE THREAD

**Issue by Sand-Deep** [mml-book/mml-book.github.io#268]
Thanks for updating my last issue request, just a quick follow up:

1) You may still want to change the normalisation coefficient in 4.86.
2) In step 1 you have changed the notation to say A^{T}A but the matrices are still AA^{T} and the second row third column in the final matrix should be 0 not 2 if you actually multiply A^{T}A.

**Comment by mpd37** [comment]
forgot to change the V matrix... 

anything else?

**Comment by Sand-Deep** [comment]
Looks good.

Thanks for the useful textbook!

**Comment by mpd37** [comment]
without people like you it would only be half as good. we really appreciate the feedback!
