### ISSUE TITLE
Expand Groups subsection (2.4.1)

### ISSUE THREAD

**Issue by Kaixhin** [mml-book/mml-book.github.io#269]
**Is your feature request related to a problem? Please describe.**
Groups are introduced quickly in 2.4.1 and then utilised a reasonable amount. For a reasonable part of the audience (those having done a bit of linear algebra to use ML but not studied maths more broadly at this level/for a long time), this section is perhaps too brief to convey enough of an (intuitive) appreciation for these concepts.

**Describe the solution you'd like**
Another example of a group (beyond real-valued n x n matrices) with more detail, ideally also pictorial (for the visual learners among us). Either a "toy" example - perhaps another one listed in Example 2.10 - or something a bit more applied, e.g., a symmetry group. Symmetry groups have connections to various methods in ML, for example in [computer vision](https://www.nowpublishers.com/article/Details/CGV-008).

**Comment by mpd37** [comment]
The suggestion is good, but we decided against this: A worked practical example in this early part of the book will require us to introduce a lot of additional material, which (we think) is not justified given that the section on groups is only a page long. There are some exercises that deal with groups.
