### ISSUE TITLE
Unclear reference to fundamental theorem of calculus in chapter 6

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#270]
**Is your feature request related to a problem? Please describe.**

I was looking at transition between 6.145 and 6.146 not understanding where does det come from. Does formulation of fundamental theorem of calculus in multivariate context makes use of determinant? If you ask Wikipedia or Wolfram for fundamental theorem of calculus you will usually get 2-3 formulations of univariate case.

**Describe the solution you'd like**
Please clarify. Either you are referring to formulation of theorem which is not easy to find in its general form or there is more happening between the lines than actually stated. In former case mentioning theorem explicitly before use or pointing at resource would be helpful.

**Additional context**
ver 2019-02-19

**Comment by empet** [comment]
In formula 6.145 is  a modulus, not a determinant!!!  Its proof  is incomplete, because   only the case when the function U is increasing is considered.  Here [https://github.com/empet/mml-book.github.io/blob/master/Myfiles/mml-book-formula-6_145.pdf](https://github.com/empet/mml-book.github.io/blob/master/Myfiles/mml-book-formula-6_145.pdf) I detailed both cases, U - increasing and decreasing, and pointed out how the modulus was involved.

**Comment by chengsoonong** [comment]
@empet is right. This is the modulus (absolute value). We do say just below (6.146) that we introduce the absolute value of the differential.

Also, this is a univariate random variable. 

The proof for the multivariate case (which results in the absolute value of the determinant) is not shown. We refer to Billingsley.

Will tidy up the presentation a bit, to make it a bit more clear that U is an increasing function.

**Comment by empet** [comment]
@chengsoonong  The function U can be decreasing, too. Both cases should be treated.

**Comment by chengsoonong** [comment]
I agree that U can be decreasing. I will make it clearer that U is increasing in the discussion. However, I am going to not show the derivation for the decreasing function, but will only have the sentence saying that for decreasing functions, we have a negative sign.
