### ISSUE TITLE
Equation 5.95 transpose missing

### ISSUE THREAD

**Issue by Sand-Deep** [mml-book/mml-book.github.io#272]
Currently the RHS of 5.95 sums two different columns of the same matrix. For dot product this should either be the transpose of the first R or swap the indicies m and p in the first R so you sum the a row with a column.

**Comment by mpd37** [comment]
The dot product 
`K[p,q] = R[:,p].T @ R[:,q]`
can be written as 
`K[p,q] = np.sum(R[:,p]*R[:,q])`
so this looks fine to me. Or do I misunderstand the question?

**Comment by Sand-Deep** [comment]
Hi, you are correct. I wrote this out again and it makes sense to me.

Sorry.

**Comment by mpd37** [comment]
perfect. thanks for checking!
