### ISSUE TITLE
Chapter 6 Error

### ISSUE THREAD

**Issue by armasog** [mml-book/mml-book.github.io#273]
**Describe the mistake**
P(Y|X) should describe the likelihood of Y (given X). If this is not the case - the language around the notation is confusing and should be explained 

**Location**
Please provide the 
1. version (bottom of page) Draft 2019-02-19
2. Chapter 6
3. page 189
4. line number/equation number 3526

**Proposed solution**
A clear and concise description of what you would like to change.

**Additional context**

**Comment by mpd37** [comment]
p(y|x) is the likelihood of x, not of y. It is a probability distribution of y given x, but not the likelihood of y. Have a look at page 29:
http://www.inference.org.uk/itprnn/book.pdf
