### ISSUE TITLE
Chapter 6 Typo

### ISSUE THREAD

**Issue by armasog** [mml-book/mml-book.github.io#274]
**Describe the mistake**
Sentence is a fragment. 

**Location**
Please provide the 
1. version (bottom of page) Draft 2019-02-19
2. Chapter 6
3. page 187
4. line number/equation number 3485

**Proposed solution**
Rewrite to - "When we think of probability theory as an extension to logical reasoning, as we discussed in section 6.1.1, the rules of probability..."

**Additional context**

**Comment by mpd37** [comment]
do you have a concrete suggestion?

**Comment by mpd37** [comment]
thanks - will be fixed with the next update
