### ISSUE TITLE
Possible typo in equation 6.104a & 6.104b

### ISSUE THREAD

**Issue by Sand-Deep** [mml-book/mml-book.github.io#279]
I think that the equality and \propto in 6.104a and 6.104b should be swapped. The second equation drops the normalisation coefficients whereas the first equation looks exact to me.

**Comment by chengsoonong** [comment]
Actually, the first equation is also a \propto. Because the posterior is not just the likelihood times the prior, but there is also the normalization term (think Bayes theorem).

**Comment by chengsoonong** [comment]
But thanks for catching that the second equation is a \propto.
