### ISSUE TITLE
Chapter 6, Definition reference incorrect

### ISSUE THREAD

**Issue by JeanKaddour** [mml-book/mml-book.github.io#280]
**Describe the mistake**
"By using the linearity of expectations, the expression in Definition 6.5
can be rewritten as [...]" should refer to Definition 6.35

**Location**
Please provide the 
1. Draft (2019-02-19)
2. Chapter 6
3. page 19
4. between 3620 and 3621

**Proposed solution**
 Definition 6.35

**Additional context**

**Comment by chengsoonong** [comment]
This is correct. It refers to "Definition 6.5", and not equation (6.35).
