### ISSUE TITLE
Possible typo in question 7.1

### ISSUE THREAD

**Issue by Sand-Deep** [mml-book/mml-book.github.io#281]
You may have intended this but question 7.1 asks the reader to find the stationary points of a function that does not have any stationary points. Is there a sign error somewhere?

I have plotted the function
[question_7.1.pdf](https://github.com/mml-book/mml-book.github.io/files/2923212/question_7.1.pdf)

**Comment by Sand-Deep** [comment]
Also, a slightly pedantic point related to the phrasing in this question. I think a saddle point is only possible where there is more than 1 independent variable, so that you get a min in one direction and a max in another, whereas the function in the question is univariate.

**Comment by mpd37** [comment]
Saddle points also exist in 1D. Example: f(x) = x^3
https://en.wikipedia.org/wiki/Saddle_point

**Comment by Sand-Deep** [comment]
I see, thanks for pointing that out. 

I guess I didn't think of x^3 looking much like a saddle in my mind.
