### ISSUE TITLE
Calling contributors again - last chance

### ISSUE THREAD

**Issue by chengsoonong** [mml-book/mml-book.github.io#282]
Starting a new list, related to #209 

Please send us your real name if you would like to be acknowledged with it.

- @Neytirix
- @SamDataMad
- @bumptiousmonkey 
- @idoamihai
- @deepakiim
- @xiaonanchong
- @insad
- @HorizonP
- @cs-maillist
- @kudo23
- @empet
- @marsggbo
- @victorBigand
- @wilfreddesert
- @17SKYE
- @Nouman97
- @zhfkt
- @shengxue

**Comment by wilfreddesert** [comment]
Hi!

I am @wilfreddesert. My real name is Timur Sharapov. I am happy to have
contributed even the tiny bid that I did :)

Best regards,
Tim

**Comment by marsggbo** [comment]
My name is He Xin @marsggbo. Very glad to make contributions to your book.



> Starting a new list, related to #209
> 
> Please send us your real name if you would like to be acknowledged with it.
> 
> * @Neytirix
> * @SamDataMad
> * @bumptiousmonkey
> * @idoamihai
> * @deepakiim
> * @xiaonanchong
> * @insad
> * @HorizonP
> * @cs-maillist
> * @kudo23
> * @empet
> * @marsggbo
> * @victorBigand
> * @wilfreddesert
> * @17SKYE
> * @Nouman97
> * @zhfkt
> * @shengxue

**Comment by shengxue** [comment]
Thanks for the great book!

@shengxue -->  Sheng Xue

**Comment by zhfkt** [comment]
@zhfkt --> Fengkuangtian Zhu .

Very glad to make contributions to the book.
Best Regards

**Comment by Nouman97** [comment]
Hey,

I am @Nouman97, my real name is Syed Nouman Hasany.

Regards.
