### ISSUE TITLE
Chapter 9 - No Shaded Area

### ISSUE THREAD

**Issue by armasog** [mml-book/mml-book.github.io#286]
**Describe the mistake**
Example 9.7 references shaded areas in the figure but there are no shaded areas when printed, viewed on Chrome, or viewed in Acrobat. Shading in other figures shows up accurately. 

**Location**
Please provide the 
1. version (bottom of page) Draft 2019-03-04
2. Chapter 9 
3. page 309
4. line number/equation number Example 9.7

**Comment by mpd37** [comment]
We'll discuss with the publisher.

**Comment by mpd37** [comment]
this is with the copy-editor; I assume this will get fixed in the printed version
