### ISSUE TITLE
Question:  Availability of Jupyter Notebook Tutorials

### ISSUE THREAD

**Issue by dankaygit** [mml-book/mml-book.github.io#289]
In Section 1.3 Exercises and Feedback, it is stated that you will 

> provide tutorials (jupyter notebooks) to explore some properties ...

I was wondering what the timeline is on those tutorials and when you will be uploading them.

PS: thanks a lot for the very well written book!

**Comment by mpd37** [comment]
I pushed the first two notebooks. The next one on PCA should show up at some point next week.

**Comment by mpd37** [comment]
The PCA notebook is also online now.

**Comment by dominikandreas** [comment]
Hi Marc, thank you very much for making this book available, initial impression is really good! As a related suggestion, I'd propose to not only provide download links to the notebooks, but also to an online viewer [eg like this](https://nbviewer.jupyter.org/github/mml-book/mml-book.github.io/blob/master/tutorials/tutorial_linear_regression.ipynb) or even an interactive link using google colab (https://colab.research.google.com, google account required)
