### ISSUE TITLE
Is it possible to get an information theory chapter?

### ISSUE THREAD

**Issue by falconair** [mml-book/mml-book.github.io#29]
I appreciate that the authors are being careful about the scope of the book, but in my own studies of ML, I've noticed that basic information theory would go a long way in helping understand some important concepts. I'm thinking of KL-Divergence, information gain, AIC, cross entropy and other concepts which show up even in basic ML.

Some books which do introduce ML start talking about coding theory and communication channels which may have been what motivated information theory but seem like the wrong approach to teach information theory to data scientists or ML practitioners. 

This paper takes an interesting approach, they start with KL Divergence before even entropy.
Divergence, Entropy, Information 
[https://arxiv.org/abs/1708.07459](https://arxiv.org/abs/1708.07459)

**Comment by mpd37** [comment]
It will not be in the main book as we don't really need information theory for the applications we've chosen. Our aim is to keep the book fairly short, and we decided not to discuss topics that are not essential for the applications.
