### ISSUE TITLE
wrong reference to the picture

### ISSUE THREAD

**Issue by angelocarbone** [mml-book/mml-book.github.io#292]
**Describe the mistake**
Wrong reference to the picture: "[...] plane in the **bottom** right of Figure 4.8."

**Location**
1. version: latest
2. Chapter: 4
3. page: 121
4. line number: 20

**Proposed solution**
"[...] plane in the **top** right of Figure 4.8."

**Comment by mpd37** [comment]
The current text is ambiguous. I rephrased it as follows:

![image](https://user-images.githubusercontent.com/5500569/54882747-2e733680-4e55-11e9-8228-a6b618ad8657.png)

Does this resolve the issue?

**Comment by angelocarbone** [comment]
Now it is correct for me.
