### ISSUE TITLE
The matrices dimension in the SVD figure is wrong 

### ISSUE THREAD

**Issue by Rezar** [mml-book/mml-book.github.io#293]
**Describe the mistake**
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version (bottom of page)
2. 4
3. 129
4. 4.64

**Proposed solution**
The matrices dimension in the SVD figure is wrong 

**Additional context**

**Comment by mpd37** [comment]
Can you be more specific? What do you mean by "wrong"?

**Comment by Rezar** [comment]
I mean the A dimension should be m.n., The U dimensions should be 'm'.'r'(or something different than 'n' or 'm'), then Sigma dimensions should be r.r and V^T dimensions should be r.n.

**Comment by mpd37** [comment]
A is m x n. 
We consider the SVD where U and V are square, so they need to be m x m and n x n, respectively. This leaves Sigma as an m x n matrix.

Please also have a look here:
https://en.wikipedia.org/wiki/Singular_value_decomposition#Statement_of_the_theorem
