### ISSUE TITLE
Not an error just a suggestion (request)

### ISSUE THREAD

**Issue by sai-krishna-msk** [mml-book/mml-book.github.io#294]
Before every chapter you have provided a mind map (which I loved it) similarly at the end of each chapter it would be nice to have a section how exactly is what I have learnt going to for in into that mind map or how exactly what I have learnt is useful to spesefic technique( something along those lines....)

**Comment by mpd37** [comment]
We can no longer make changes like this before printing, I'm afraid.

**Comment by sai-krishna-msk** [comment]
I understand but really appreciate your efforts, please let me know if
there is any kind of contribution I can do as a novice who is interested in
your book and ML

Thank you
