### ISSUE TITLE
Feel confused with the notation in the book

### ISSUE THREAD

**Issue by eeyrw** [mml-book/mml-book.github.io#295]
**Describe the mistake**
What does R\{0} really mean? Or just some LaTex commands that are not rendered properly.

**Location**
Please provide the 
1. Draft (2019-03-17)
2. Chapter 2 Linear Algebra
3. 36
4. Example 2.10

**Proposed solution**
No idea.

**Additional context**
![image](https://user-images.githubusercontent.com/2088817/54969581-a2c6ea80-4fb9-11e9-9750-dd2153e8e916.png)

**Comment by chengsoonong** [comment]
The backslash "\" means set difference. So $\RR \ {0}$ means the real line, without the point 0.

**Comment by eeyrw** [comment]
> The backslash $\$ means set difference. So $\RR \ {0}$ means the real line, without the point 0.

Thank you. I see.
