### ISSUE TITLE
Chapter 6, formula (6.84d)

### ISSUE THREAD

**Issue by shengxue** [mml-book/mml-book.github.io#302]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I thought 
![image](https://user-images.githubusercontent.com/6092790/55644541-82c3d200-57d6-11e9-87a6-5e53a4ef474c.png)
, but it is 
![image](https://user-images.githubusercontent.com/6092790/55644583-a71fae80-57d6-11e9-8ffd-fdd8ab35dbe5.png)

 in formular (6.84d)

**Describe the solution you'd like**
An explicit formula of 
![image](https://user-images.githubusercontent.com/6092790/55655284-0fc95400-57f4-11e9-9823-f0ec9c7abd35.png)
 , would be very helpful for readers like me to understand the formular (6.84d)

**Comment by chengsoonong** [comment]
This is now updated to
![Screen Shot 2019-04-08 at 8 58 28 pm](https://user-images.githubusercontent.com/709424/55719244-22849880-5a41-11e9-8ce2-70e5c5f52f74.png)
