### ISSUE TITLE
Ebook Translation for Portuguese-Brazilian

### ISSUE THREAD

**Issue by firebitsbr** [mml-book/mml-book.github.io#313]
I would like to translate this ebook into Portuguese-Brazilian, could you authorize me to do so?

Kind regards.

Mauro Risonho de Paula Assumpção
https://www.linkedin.com/in/firebitsbr/

**Comment by mpd37** [comment]
contacted @firebitsbr directly about this

**Comment by acmlira** [comment]
Helo! I liked the initiative, can you tell us the result or only if I get in direct contact with you?
