### ISSUE TITLE
Section 4.5.1 maybe exist a wrong right bracket

### ISSUE THREAD

**Issue by naiixeel** [mml-book/mml-book.github.io#316]
Describe the mistake
Section 4.5.1 maybe exist a wrong right bracket.

Location
1. version: Draft (2019-04-16)
2. Chapter: 4
3. page:120
4. line number: the second line from the bottom

Proposed solution
remove the right bracket

Additional context
the text that contains the mistake:  the SVD performs a basis change via V )followed by

**Comment by mpd37** [comment]
good catch!
