### ISSUE TITLE
Not an issue (as such) but ...

### ISSUE THREAD

**Issue by jp-uom** [mml-book/mml-book.github.io#32]
When am I going to be able to buy and review this book?

Also the link https://www.mml-book.com/ gives me an a "site cannot be reached" error ...

**Comment by mpd37** [comment]
Try http not https. This solves this issue for me.

Book can be reviewed now (at least the chapters that are online). We aim for June to have all chapters ready.



On Apr 4, 2018 at 14:56, <JP<mailto:notifications@github.com>> wrote:


When am I going to be able to buy and review this book?

Also the link https://www.mml-book.com/ gives me an a "site cannot be reached" error ...

**Comment by dotmanish** [comment]
Google Chrome by default tries for https:// (rightly) when I just type mml-book.com.

The redirection should be fixed asap if, as per the request in the first paragraph, "Please link to this site using mml-book.com.".

**Comment by jp-uom** [comment]
Great thanks -- please fix the link on the front page (https://mml-book.github.io/ links to https://mml-book.github.io/)
