### ISSUE TITLE
Incoherent use of Index 

### ISSUE THREAD

**Issue by XiaoleiZ** [mml-book/mml-book.github.io#320]
**Describe the mistake**
Incoherent use of index

**Location**
Please provide the 
1. 2019-04-25
2. 5
3. 160
4. line 3-4, Line 7, equation 5.113 and Figure 5.8 

**Proposed solution**
In equation 5.113, the index of A_i and b_i starts from 0. But in the Figure 5.8, the index starts from 1 (it should be 0 from description). In Line 3-4 and Line 7, the index starts from 1. Would it be more clear if all start from the same index? 

**Additional context**
If Figure 5.8 updates, so as Figure 5.9

**Comment by mpd37** [comment]
Well spotted! I'll fix this with the next update.
