### ISSUE TITLE
Example 6.2

### ISSUE THREAD

**Issue by zhouchiji** [mml-book/mml-book.github.io#321]
this part of the marginal probability formula. Why divide by the total number of events N? ps the formula is (6.10) @chengsoonong @mpd37

**Comment by zhouchiji** [comment]
![image](https://user-images.githubusercontent.com/33052516/56876601-2ffad480-6a7b-11e9-8f11-6062e242b73b.png)

**Comment by chengsoonong** [comment]
I'm not sure I understand this question. Could you try to rephrase "Why divide by the total number of events N?".

**Comment by chengsoonong** [comment]
Perhaps it is worth recalling the axioms of probability, as described in Section 6.1.2.
"The probability of a single event must lie in the interval [0, 1], and the total probability over all outcomes in the sample space Ω must be 1, i.e., P (Ω) = 1."
The total number of outcomes is N, and therefore we divide by N to make sure that the total probability over all outcomes is 1.

**Comment by kazemihabib** [comment]
Thank you for your explanation, but I am confused. The summation of marginal probability should always be equal to 1 without that division by N. I checked several sources and couldn't find this division by N.
