### ISSUE TITLE
Mistake in Section 2.8.1

### ISSUE THREAD

**Issue by JayGwod** [mml-book/mml-book.github.io#326]
**Describe the mistake**

The solution of the linear equation seems incorrect.

**Location**

Chapter 2
page 62
the *Remark* paragraph

**Proposed solution**

"In particular, the solution of the linear equation $\lambda_1 x_1 + ... + \lambda_n x_n = b$", it seems that this equation should be equal to 0, because the particular solution $x_0$ should satisfy $Ax_0 = b$, and therefore $A(x_0 + \lambda_1 x_1 + ... + \lambda_{n-1} x_{n-1} ) = b$.  If $\lambda_1 x_1 + ... + \lambda_{n-1} x_{n-1} \neq 0$, the original equation $Ax = b$ cannot be satisfied.

**Comment by mpd37** [comment]
We are looking at the general solution,  which is the particular solution Ax_0 = b and all solutions of Ax = 0. 
The solution space of Ax = 0 gives you a vector space, and any solution x_0 with Ax_0 = b gives you the offset. This will turn the general solution into an affine space. 

Does this make more sense?

**Comment by JayGwod** [comment]
I mean from the book readers cannot distinguish which is the particular solution Ax_0 = b and which are the solutions of Ax = 0, because if any x_n is a particular solution, the corresponding coefficient must be equal to 1. However, the book does not list this condition. If the book can specify which is the solution space of Ax = 0 and which is the offset, it would be more clear?

**Comment by mpd37** [comment]
I'm not entirely sure I can identify the problem/confusion with the remark to be honest.

A particular solution always solves Ax=b. Have you had a look at Section 2.3? The solutions Ax=0 define a subspace, and any x_0 that solves Ax_0 = b translates this subspace away from 0.

**Comment by JayGwod** [comment]
Yes, I have read Section 2.3, and the problem is that there is not any statement about x_0 that solves Ax_0 = b appearing in the remark:

![image](https://user-images.githubusercontent.com/20216509/57970465-1848a900-79b4-11e9-9605-b11341d63181.png)

Have you said anything about x_0? If any x_n can be the particular solution of Ax = b, the corresponding lambda must be equal to 1, but this condition isn't given in the "where" statement.

**Comment by mpd37** [comment]
There are two points  in this remark. 
(i) The general solution of Ax = b is given in the form x_0 + U, where U is a subspace (solving Ax = 0) and x_0 solves Ax=b (particular solution). 

(ii) The second part states that if A = \lambda^T then the solution is a hyperplane (the nullspace is of dimension n-1).

**Comment by JayGwod** [comment]
(ii) is the key point. Where does the vector \lambda^T come from? Is that mentioned anywhere before? A is a matrix and \lambda^T is a vector, why the equation holds? It confuses me a lot. (i) is trivial, I have no questions about that.

**Comment by mpd37** [comment]
It's a special case (a vector is an nx1 matrix) of A. That is what we wanted to indicate when we wrote "specifically". But maybe that is not clear enough.

**Comment by JayGwod** [comment]
Well, I get your idea eventually. Thank you very much.
