### ISSUE TITLE
incorrect matrix dimensions

### ISSUE THREAD

**Issue by xiaohanhuang** [mml-book/mml-book.github.io#328]
**Describe the mistake**
incorrect matrix dimensions. m x n and p x q should switch.
<img width="474" alt="Screen Shot 2019-05-24 at 10 26 36 PM" src="https://user-images.githubusercontent.com/8962558/58365056-8d642480-7e73-11e9-8e77-37c3c99d5976.png">

**Location**
Please provide the 
1. version (bottom of page)
Draft (2019-05-21) of “Mathematics for Machine Learning”. Feedback to https://mml-book.com
2. Chapter
5
3. page
156
4. line number/equation number
first paragraph

**Proposed solution**
A clear and concise description of what you would like to change.

**Additional context**

**Comment by mpd37** [comment]
thanks for this.
