### ISSUE TITLE
independence of more than two random variables not properly described

### ISSUE THREAD

**Issue by teixeira96** [mml-book/mml-book.github.io#329]
**Describe the mistake**
"The word “independent” refers to Definition 6.10, i.e., any pair of random variables Xi and Xj are independent." While independence implies the statement, the correct definition (for more than two random variables) requires more.

**Location**
Please provide the 

1. version (bottom of page) - Draft (2019-05-29) 
2. Chapter - 6
3. page -194
4. line number/equation number - Last line

**Proposed solution**
Change definition 6.10 to account for more than two random variables or point out that independent means more than what was stated

**Additional context**
https://en.wikipedia.org/wiki/Independence_(probability_theory)#More_than_two_random_variables

**Comment by teixeira96** [comment]
I don't think this issue should be closed.

"The word “independent” refers to Definition 6.10, i.e., any pair of random variables Xi and Xj are independent" is still not properly described. When we say independent in iid, usually we assume mutually independent.

The proposed solution involves stating that this use of independence (namely the independence of X_1, ... X_n) requires more than pairwise independence. The side note added does note help the reader understand that.

thanks

**Comment by chengsoonong** [comment]
@teixeira96 Do you have a suggestion for one sentence (about 10 words) that fit in a margin comment, that will indicate that independence of a set of random variables is more complex than independence between two random variables?

**Comment by teixeira96** [comment]
Not really. I think the way is written is very good. I'm sorry, i think that i've mixed issues. 
What i really think should be added now is a side note when independence is explained in iid. Something along the lines of "Here, what is usually assumed is mutual independence, not pairwise"
Should i open a new issue?
Thanks!

**Comment by chengsoonong** [comment]
I've changed the sentence after iid to:
For more than two random variables, the word “independent” (Definition 6.10) usually refers to mutually independent random variables, where all subsets are independent (see Pollard (2002, chap- ter 4) and Jacod and Protter (2004, chapter 3)).

**Comment by teixeira96** [comment]
Great!
