### ISSUE TITLE
Add a table of notations

### ISSUE THREAD

**Issue by chrissherlock** [mml-book/mml-book.github.io#33]
From [Hacker News](https://news.ycombinator.com/item?id=16751261):

> Not sure if the authors will read this or not but I beg of you, please put a table of notation in the forward. The Sutton and Barto Reinforcement Learning book did that for basically every notation that wasn't basic algebra and it's been extremely helpful.
> Just labeling things I had never seen before, like indicator functions, was extremely valuable.
> 
> Especially for this kind of book that is introducing mathematics to people from a broad background - I think it's important to understand how much of an impediment not knowing notation is by sight. Trying to Google or search for notation is a nightmare.

**Comment by chengsoonong** [comment]
Here is an attempt at putting together a table of symbols. I'm pretty sure we are missing on a whole bunch, if you find any, please add comments below.

[mml-book-symbols.pdf](https://github.com/mml-book/mml-book.github.io/files/2137544/mml-book-symbols.pdf)

**Comment by gingertom** [comment]
This is a great start. But there are a few others that I've hit:

- "∈" element of symbol
- The arrow definition of functions, for example in definition 5.5 for partial differentiation.
- The combination notation as used in example 5.1 (Derivative of a Polynomial) line 5.7

I'll add more if I find them.

**Comment by chengsoonong** [comment]
Resolved in b5acfa73bbaf0a35ed3810ac4f1a1f116e1dde59

Table of notation [here](https://mml-book.github.io/book/notation.pdf)
