### ISSUE TITLE
Chapter 3 inner product

### ISSUE THREAD

**Issue by ajclaros** [mml-book/mml-book.github.io#330]
**Describe the mistake**
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version (bottom of page) - Draft(2019-5-30)
2. Chapter - 3
3. page - 78
4. line number/equation number - (3.28)

**Proposed solution**
The result should be -(1/2) ≈ 2.09 rad =120 deg instead of -(1/3)

**Comment by mpd37** [comment]
You need to compute the inner product using the A matrix. The result should be as stated in the chapter.
