### ISSUE TITLE
Hat missing in equation 3.11

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#331]
In equation (3.11) page 74, "hat" are missing on top of x in the last part of the equation.
It should be written like equation 3.10, with x^ the column vector of coordinates of the vector x.
There is the same issue at the 4th line before end of the page:
"The null space (kernel) of A consists only of 0 because x*Ax > 0 ..."

**Location**
1. version: Draft (2019-05-30)
2. Chapter: 3.2.3 Symmetric, Positive Definite Matrices
3. page: 74
4. line number/equation number:

**Comment by mpd37** [comment]
I would leave the \hat notation out here because this statement is independent of the choice of the basis, and, therefore, the coordinate representation of x
