### ISSUE TITLE
Angle between vectors

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#332]
**Describe the mistake**
For $\cos(\omega )$ to be equal -1, $pi$ must be included in the interval. 

**Location**
Please provide the 
1. version: Draft (2019-05-30)
2. Chapter: 3.4
3. page: 76
4. line number/equation number: Figure 3.4 and line between equation (3.24) and (3.25)

**Proposed solution**
Let $\omega \in \[0,\pi\]$ rather than $\[0, \pi)$

**Additional context**

**Comment by mpd37** [comment]
Good catch!
