### ISSUE TITLE
Characteristic polynomial of I

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#335]
**Describe the mistake**
In Example 4.4 (The Case of the Identity Matrix) it is written $p(\lambda) = det(**I** - \lambda)$ instead of $p(\lambda) = det(**I** - \lambda**I**)$ 

**Location**
1. version (bottom of page): Draft (2019-06-02)
2. Chapter: 4
3. page: 106
4. line number/equation number: 1st-2nd line of Example 4.4 (The Case of the Identity Matrix)

**Proposed solution**
Replace $p(\lambda) = det(**I** - \lambda)$ by $p(\lambda) = det(**I** - \lambda**I**)$ 

**Additional context**

**Comment by mpd37** [comment]
Good catch
