### ISSUE TITLE
Distinct **unit** eigenvector

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#336]
**Describe the mistake**
"The eigenvalue has, however, only one distinct eigenvector" is not correct.
All vectors collinear to [1 0]^T are eigenvectors. For example, [2 0]^T is distinct from [1 0]^T and is also an eigenvector of A. 

**Location**
1. version (bottom of page): Draft (2019-06-02)
2. Chapter:4
3. page: 108
4. line number/equation number: Example 4.6

**Proposed solution**
"The eigenvalue has, however, only one distinct eigenvector" could be replaced by:
* "The eigenvalue has, however, only one distinct unit eigenvector"
or
* E_2=span([1 0]^T)

**Additional context**

**Comment by mpd37** [comment]
thanks!
