### ISSUE TITLE
Boldface

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#337]
**Describe the mistake**
Boldface missing for a vector.
Last "x_2" in the equation (4.40) is not in bold.

**Location**
1. version (bottom of page): Draft (2019-06-02)
2. Chapter: 4
3. page: 112
4. line number/equation number: Equation (4.40)

**Proposed solution**
A clear and concise description of what you would like to change.

**Additional context**

**Comment by mpd37** [comment]
Good catch. I'll fix this in the new pdf
