### ISSUE TITLE
Eigenvalues of A'A and AA'

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#338]
**Describe the mistake**
Page 124 it is written "Since AA' and A'A have the same non-zero eigenvalues (see page 106)".
I'm sorry but I see nothing in page 106 that proves this.

**Location**
Please provide the 
1. version (bottom of page): Draft (2019-06-03)
2. Chapter: 4
3. page: 124
4. line number/equation number: Line 13

**Proposed solution**
Add a theorem.
Theorem:
Let A∈Rm×n.  Then AA' and A'A have identical non-zero eigenvalues.  Further, if q is an eigenvector of AA' then A'q is an eigenvector of A'A.

Proof: 
Let λ be a non-zero eigenvalue of AA' and q be the eigenvector corresponding to λ. Then (AA')q=λq. Thus, (A'A)(A'q) = A'(AA')q = λA'q. Hence, λ is an eigenvalue of A'A with A'q as the corresponding eigenvector.

Remark:
Assuming λ≠0 guaranty that A'q≠0.
Indeed, suppose A'q=0, then (AA')q=0, that is λq=0 and λ=0. 

**Additional context**

**Comment by mpd37** [comment]
Thanks for this. We saw this recently as well. We refer to a bullet point on the corresponding page. Your suggestion would have been cleaner, but we can no longer make these (significant) changes to the chapters.

**Comment by mpd37** [comment]
I started working on additional exercises and added this proof as well. 
https://www.overleaf.com/read/jvnwngmkpckc

**Comment by CL-BZH** [comment]
Hi Mark,

I think in your proof you have to mention that

**Comment by mpd37** [comment]
If q is eigenvector of AA' and A'q = 0 then it would also follow that  AA'q = 0, so that the corresponding eigenvalue would be 0, which violates the assumption we have. Is there any other way to arrive at A'q = 0 without lambda=0?

**Comment by CL-BZH** [comment]
Hi Mark,
This is exactly my remark.
I think it should be mentioned it in the proof.
My point is that before concluding from (A'A)X= λX that λ is an eigenvalue, one has to prove that X is not 0. Here, we prove by contradiction that A'q != 0.
For example, rather than writing "Therefore,λ is an eigenvalue of A'A with A'q as the corresponding eigenvector.", maybe you could write something like:
Since A'q != 0, otherwise we would have (AA')q=0, that is λq=0 hence λ=0 which contradicts the hypothesis on λ, λ is an eigenvalue A'A with A'q as the corresponding eigenvector.

**Comment by CL-BZH** [comment]
Also, I think the proof is not complete.
It proves that if λ is an eigenvalue of AA' then it is an eigenvalue of A'A.
It should be added that by a similar argument one can prove that if λ is an eigenvalue of A'A then it is an eigenvalue of AA' (with eigenvector Aq).

**Comment by CL-BZH** [comment]
Also, I think the proof is not complete.
It proves that if λ is an eigenvalue of AA' then it is an eigenvalue of A'A.
It should be added that by a similar argument one can prove that if λ is an eigenvalue of A'A then it is an eigenvalue of AA' (with eigenvector Aq).

**Comment by mpd37** [comment]
Thanks for this. I agree. I made some changes to the document.

**Comment by CL-BZH** [comment]
Hi Marc,

Sorry but there are some errors (typos) in your new proof.
"We now need to show that q != 0 before we can conclude that λ is an eigenvalue of A'A."
should be
"We now need to show that A'q != 0 before we can conclude that λ is an eigenvalue of A'A."
That is, replace "q != 0" by "A'q != 0".
And, similarly "Therefore, q != 0." should be "Therefore, A'q != 0."
And the same is true for the second part of the proof with "p" to be replaced by "Ap":
"Assume p = 0" should be "Assume Ap = 0"
and 
"Therefore p! = 0." should be ""Therefore Ap != 0.""

**Comment by mpd37** [comment]
Thanks - can you have a quick look again?

**Comment by CL-BZH** [comment]
Okay. Now it is perfect!
