### ISSUE TITLE
{Av_i} is a basis 

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#339]
**Describe the mistake**
"it holds that {Av_1 , . . . , Av_r } are a basis".
Shouldn't it be:
"it holds that {Av_1 , . . . , Av_r } is a basis"

**Location**
1. version (bottom of page): Draft (2019-06-03)
2. Chapter: 4
3. page: 124
4. line number/equation number: First line below equation (4.77)

**Proposed solution**
Replace "are" by "is".

**Additional context**

**Comment by mpd37** [comment]
I think it depends on how you read it. If you read it "Av1, Av2, .." then it should be "are" because you have >1 elements. If you read it as "the set Av1, Av2, ... " then it would be "is" (commonly)

**Comment by chengsoonong** [comment]
I'm going to go with "is" and check with the copy editor.
