### ISSUE TITLE
( n − k )-dimensional null space Z

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#340]
**Describe the mistake**
"at least" missing.
If matrix B has rank less or equal k then, dim(Z=Null(B)) is greater or equal to n-k.

**Location**
1. version (bottom of page): Draft (2019-06-04)
2. Chapter: 4
3. page: 132
4. line number/equation number: 12

**Proposed solution**
Replace "there exists an ( n − k )-dimensional null space Z" 
by "there exists an at least ( n − k )-dimensional null space Z"
or by "there exists an ( n − rk(B) )-dimensional null space Z" 

**Additional context**

**Comment by mpd37** [comment]
Good point.
