### ISSUE TITLE
rank k approximation

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#341]
**Is your feature request related to a problem? Please describe.**
For the SVD rank k approximation, it is stated that rk(Ak)=k (page 130, line below equation (4.92)) with no proof.

**Describe the solution you'd like**
I think there should be a proof of that (or maybe as an exercise).
After all, it is not obvious from equation (4.92) that Ak is of rank k.

**Describe alternatives you've considered**

**Additional context**

**Comment by mpd37** [comment]
We decided not to include the proof here for the following reasons:
- we wanted to keep the book relatively short
- the chapter is already long and (compared to the others) proof heavy
- the proof is not essential for the understanding of the SVD
