### ISSUE TITLE
Word missing?

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#342]
**Describe the mistake**
The first sentence of Theorem 4.25 is "Consider a A..."
Shouldn't it be either:
 "Consider a matrix A..."
or
 "Consider A..."

**Location**
1. version (bottom of page): Draft (2019-06-04)
2. Chapter: 4
3. page: 131
4. line number/equation number: Theorem 4.25

**Proposed solution**
Add the word "matrix". i.e. "Consider a matrix A..."

**Additional context**

**Comment by mpd37** [comment]
thanks for careful reading. will be fixed with the next pdf update.
