### ISSUE TITLE
Mistake in 10.2.2

### ISSUE THREAD

**Issue by JayGwod** [mml-book/mml-book.github.io#346]
**Describe the mistake**
![image](https://user-images.githubusercontent.com/20216509/59553079-5be9ff00-8fc2-11e9-957c-23b43c645199.png)
The vector outer product cannot be commutative, and I have written codes to check it, finding it's indeed incorrect.

**Location**

1. Draft(June 12, 2019)
2. Chapter 10
3. page 323
4. equation number 10.20

**Comment by mpd37** [comment]
Excellent catch! The argument is indeed a bit more complicated. The problematic term is the sum where x_n x_n^T is on the right-hand side. But we identify the sum of the outer product as a projection matrix onto the subspace spanned by b_1, ..., b_{m-1} so that the result is orthogonal to b_m.

Does this work better now?

![image](https://user-images.githubusercontent.com/5500569/59553834-fd595c80-8f92-11e9-8efa-370053193388.png)

**Comment by JayGwod** [comment]
The result of $b_i b_i^T x_n$ is orthogonal to $b_m$, but $b_i b_i^T x_n x_n^T$ is not. Actually, it is a matrix, which multiplying $b_m$ is not equal to zero. I have written programs to check it and verified this term can not be ignored.

**Comment by JayGwod** [comment]
```python
import numpy as np
from numpy import linalg as LA

X = np.random.randn(5, 100)    # generate random data set
cov = np.cov(X)    # compute co-variance matrix
_, b = LA.eigh(cov)    # get every basis of all principle components
b1 = b[:, 4]    # b[:, 4] is the eigenvector with the maximum eigen value
b2 = b[:, 3]    # check the situation of m = 2
print(np.outer(b1, b1) @ X @ X.T @ b2)    # print the value of the term
```

The result is `[ 0.92006373 -0.99287112 -0.15549391  0.94529039  0.19436114]`, not zero vector.

**Comment by mpd37** [comment]
Good point. Thanks for sharing this. I've given this another try:

![image](https://user-images.githubusercontent.com/5500569/59564663-541d6f80-9041-11e9-815f-b073f0543bae.png)

The last term in (10.21) is 0 because b_m is orthogonal to b_1, .., b_{m-1}.
Does this make more sense now?

**Comment by JayGwod** [comment]
![image](https://user-images.githubusercontent.com/20216509/59566198-34ad3380-908f-11e9-8cf6-27bf900e58c1.png)
In your book, you want to prove $b_m$ is an eigenvector of $S$, however, in your modified version, (10,21) directly uses this proposition. In other words, we don't know  $b_m$ is an eigenvector of $S$, which is what we want to prove. Therefore, at the step (10.21), we cannot think $Sb_m$ is equal to $\lambda_m b_m$. It looks like a circular reasoning, doesn't it?

**Comment by JayGwod** [comment]
In your modified version, you still try to prove  the term $b_i b_i^T x_n x_n^T b_m$ is equal to zero. But I have write a program to prove this is impossible. Maybe you should try another way.

**Comment by mpd37** [comment]
I should have posted the full part... Equation 10.19 has changed (you caught this correctly), and equation 10.20 shows that \hat S b_m = S b_m. Since b_m is an eigenvector of \hat S, it also must be one of S:

![image](https://user-images.githubusercontent.com/5500569/59567308-f2223180-9063-11e9-8b6e-1fd9c51df003.png)

**Comment by JayGwod** [comment]
![image](https://user-images.githubusercontent.com/20216509/59567435-6d093d80-90a0-11e9-93cf-a53f3f8a20f4.png)
You haven't gotten my idea. The key point is why the two red circle parts are equal. If these two parts are to be equal, the condition is that $S b_m$ must be equal to $\lambda_m b_m$. But we don't know this condition is true, this is what we want to prove. Are you clear now? In addition, my program has proven this part cannot not be zero, unless you can point out my program is incorrect.

**Comment by mpd37** [comment]
Got the misunderstanding. Your program is correct. I'll look into this.

**Comment by JayGwod** [comment]
Thank you, expect your reply.

**Comment by mpd37** [comment]
OK, here's my next attempt.

First, regarding the code. There's a small mistake in the sense that the data needs to be centered. Here's an updated version of the code:

```python
import numpy as np
from numpy import linalg as LA

N = 100 # number of data points
D = 5   # dimensionality of data

X = np.random.randn(D, N)        # generate random data set
X = X - np.mean(X, axis=1).reshape(-1,1) # center the data 
S = 1/N * X@X.T                  # compute co-variance matrix
_, b = LA.eigh(S)                # get every basis of all principle components
b1 = b[:, 4].reshape(-1,1) / LA.norm(b[:,4])   # b[:, 4] is the eigenvector with the maximum eigen value; ensure unit length
b2 = b[:, 3].reshape(-1,1) / LA.norm(b[:,3])   # check the situation of m = 2
b3 = b[:, 2].reshape(-1,1) / LA.norm(b[:,2])
b4 = b[:, 1].reshape(-1,1) / LA.norm(b[:,1])
b5 = b[:, 0].reshape(-1,1) / LA.norm(b[:,0])

# choose 3 principal components
P = np.hstack([b1, b2, b3]) # concatenate principal components
P = P @ P.T # projection matrix

print(P  @ S @ b4)
```

The result is [[ 1.80411242e-16]
 [ 2.77555756e-17]
 [-2.77555756e-17]
 [-1.11022302e-16]
 [ 1.38777878e-17]]


Regarding the proof, it may be easier to show that the sets of eigenvectors of both matrices are identical. Here's a sketch:

<img width="643" alt="Screen Shot 2019-06-29 at 09 09 10" src="https://user-images.githubusercontent.com/5500569/60381501-984f3d80-9a4d-11e9-94c4-d4a835394894.png">

**Comment by chriswebers** [comment]
The goal seems to be to show that b_m is an eigenvector not only of \hat{S} but also S. So write down
 \hat{S} b_m = ... according to formula 10.19b. The first term on the right-hand-side gives you S b_m. The second and third term both end with sum_{i=1}^{m-1} b_i^T b_m. For i < m, all b_i are orthogonal to b_m and therefore all those terms result in zero. q.e.d.
By the way: Always use different indices (like i and j) for sums in equations like eq 10.19a ff. The current novation is ambiguous.

**Comment by chriswebers** [comment]
There seems to be still a problem for m>1 because then S-hat has multiple eigenvalues zero. That means, the set of eigenvectors with eigenvalues zero is only defined up to an orthogonal matrix. And that means that showing equivalence of those eigenvectors as in case (b) is showing 'too much'.

**Comment by chriswebers** [comment]
By the way: Using the same index for multiple sums like in 10.19a can easily lead to mistakes when shifting the summation operator to the left in order to massage such expressions. (I would even go so far to say, that the last expression of 10.19b is ambiguous because it is not clear to which summation the last b_i b_i^T belong).
