### ISSUE TITLE
Typo Chapter 4 Page 129

### ISSUE THREAD

**Issue by takeitallsource** [mml-book/mml-book.github.io#347]
**Describe the mistake**
There’s a typo in 4.6: “cheaper to compute than **e** full SVD”

**Location**
Please provide the 
1. April 29
2. Chapter 4, 4.6
3. 129
4. Last paragraph.

**Proposed solution**
Should be “cheaper to compute than **a** full SVD”

**Additional context**

**Comment by mpd37** [comment]
This typo should already be fixed in the most recent version.
