### ISSUE TITLE
Marginal likelihood BLR

### ISSUE THREAD

**Issue by rm4216Ric** [mml-book/mml-book.github.io#348]
**Typo in equation 9.64b describing in short form the marginal likelihood in the Bayesian Linear Regression section**

The covariance in equation (9.64b) is described as:
$\mathbf{S}_0 + \sigma \mathbf{I}$
**Location**
1. version : 2019
2. Chapter: 9
3. page: 313
4. line number/equation number: 9.64b

**Proposed solution**
Instead the correct covariance matrix should be the following:
$\mathbf{X} \mathbf{S}_0 \mathbf{X}^T + \sigma \mathbf{I}$

Thanks,
Riccardo

**Comment by mpd37** [comment]
Thanks for pointing this out. Will be fixed with the next version.
