### ISSUE TITLE
Chapter 6.7, side note on page 217 top is misplaced+cropped

### ISSUE THREAD

**Issue by ruslanasa** [mml-book/mml-book.github.io#349]
Chapter 6.7, side note on page 217 top left side is misplaced+cropped.

I assume that this side note should be on the right side top and not cropped - see link below:

[Page 217 top shot](https://drive.google.com/file/d/1cY9-cpz-Wb28iJ9NO6O0saX5Wz6EgUbW/view?usp=sharing)

**Comment by chengsoonong** [comment]
Thanks. Will be fixed in the next version.
