### ISSUE TITLE
Missing transpose in (7.51), (7.52)

### ISSUE THREAD

**Issue by MatthewJA** [mml-book/mml-book.github.io#350]
**Describe the mistake**
Equations (7.51) and (7.52) are missing a transpose after the first parentheses set (and a vector bold).

**Location**
1. Version 2019-06-12
2. Chapter 7
3. 241/242
4. 7.51/7.52

**Proposed solution**
Add ^T before Q to both equations
Bold the A in 7.5.1

**Comment by chengsoonong** [comment]
Thanks
