### ISSUE TITLE
Alternative names for Injective & Surjective

### ISSUE THREAD

**Issue by aliunlu97** [mml-book/mml-book.github.io#351]
In definition 2.16 on pg 48, where Injective, Surjective, and Bijective linear mappings are defined, it might be nice to mention the alternative names for Injective (One-to-one) and Surjective (Onto) just as "linear mapping (or vector space homomorphism/ linear transformation)" is given previously. I hope it is not too late to make such amendments as the book is on its way for publication. I have just wanted to make a suggestion. Have a nice day.

Sincerely,

**Location**

Version 2019-06-12
Chapter 2
48
2.16

**Proposed solution**

Add _Injective (One-to-one)_ and _Surjective (Onto)_

**Comment by mpd37** [comment]
Good suggestion, but it's too late now, I'm afraid.
