### ISSUE TITLE
Theorem 2.20, bases positions can be confusing

### ISSUE THREAD

**Issue by lostspirt0** [mml-book/mml-book.github.io#352]
**Describe the mistake**
![equation](https://latex.codecogs.com/gif.latex?%24B%3D%28b_%7B1%7D%2C%20%5Cdots%2C%20b_%7Bn%7D%29%2C%20%5Chat%7BB%7D%20%3D%20%28%5Chat%7Bb_%7B1%7D%7D%2C%5Cdots%2C%5Chat%7Bb_%7Bn%7D%7D%29%24)
of V and
![equation](https://latex.codecogs.com/gif.latex?%24C%3D%28c_%7B1%7D%2C%20%5Cdots%2C%20c_%7Bn%7D%29%2C%20%5Chat%7BC%7D%20%3D%20%28%5Chat%7Bc_%7B1%7D%7D%2C%5Cdots%2C%5Chat%7Bc_%7Bn%7D%7D%29%24)
of W
I suppose B and C should correspond to V and ![equation](https://latex.codecogs.com/gif.latex?%5Chat%7BB%7D) and ![equation](https://latex.codecogs.com/gif.latex?%5Chat%7BC%7D) should correspond to W.

**Location**
Please provide the 
1. Draft(2019-06-12)
2. 2
3. 54
4. Theorem 2.20

**Proposed solution**
![equation](https://latex.codecogs.com/gif.latex?%24B%3D%28b_%7B1%7D%2C%20%5Cdots%2C%20b_%7Bn%7D%29%2C%20C%3D%28c_%7B1%7D%2C%20%5Cdots%2C%20c_%7Bn%7D%29%24)
of V and
![equation](https://latex.codecogs.com/gif.latex?%5Chat%7BB%7D%20%3D%20%28%5Chat%7Bb_%7B1%7D%7D%2C%5Cdots%2C%5Chat%7Bb_%7Bn%7D%7D%29%2C%20%5Chat%7BC%7D%20%3D%20%28%5Chat%7Bc_%7B1%7D%7D%2C%5Cdots%2C%5Chat%7Bc_%7Bn%7D%7D%29)
of W

**Additional context**
I am not sure about it.
Thank you for the wonderful book!

**Comment by mpd37** [comment]
No, B and \tilde B are bases of V, C and \tilde C are bases of W.
