### ISSUE TITLE
Improve Illustration

### ISSUE THREAD

**Issue by AxleMaxGit** [mml-book/mml-book.github.io#355]
**Is your feature request related to a problem? Please describe.**

Page 17. Diagram 2 (a) shows the addition of vectors. 

I think it can be made more illustrative if you use the format like the first graphic on this page. Where the added vectors are shown in sequence highlighting the additive effect.

http://emweb.unl.edu/Math/mathweb/vectors/vectors.html

A tiny point but I think it can help learners. :-)

**Comment by chengsoonong** [comment]
Unfortunately it is too late to introduce such major changes to the book.
