### ISSUE TITLE
Incorrect Factorization

### ISSUE THREAD

**Issue by aliunlu97** [mml-book/mml-book.github.io#357]
**Describe the mistake**
In example 4.8, there is a mistake in the factorization of the characteristic polynomial of A. When we factor the characteristic polynomial using Rational Root Theorem:

p_{A}(\lambda) = 7-15\lambda+9\lambda^{2}-\lambda^{3}
{\lambda=1 is a root of this. After dividing this polynomial by (\lambda-1)}
p_{A}(\lambda) = (\lambda-1)(-\lambda^{2}+8\lambda-7)
{Factorizing (-\lambda^{2}+8\lambda-7)}
p_{A}(\lambda) = (\lambda-1)(\lambda-7)(1-\lambda)
{(\lambda-7)(1-\lambda) = (-1)(\lambda-7)(\lambda-1) = (7-\lambda)(\lambda-1)}
p_{A}(\lambda) = (\lambda-1)(7-\lambda)(\lambda-1)
p_{A}(\lambda) = (\lambda-1)^{2}(7-\lambda)

In the example, instead of the last factorization, we are given the following:
p_{A}(\lambda) = (\lambda-1)^{2}(\lambda-7)
which is actually (-1)p_{A}(\lambda).

Fortunately, it does not affect the eigenvalues, they are still 1 and 7 respectively.

Sincerely,

**Location** 
1. 2019-07-13
2. 4
3. 112
4. 4.38

**Proposed solution**
Change the characteristic polynomial p_{A}(\lambda) = (\lambda-1)^{2}(\lambda-7) to p_{A}(\lambda) = (\lambda-1)^{2}(7-\lambda)

**Comment by mpd37** [comment]
Thanks for catching this.
