### ISSUE TITLE
2.7 Linear Mappings - Special Cases

### ISSUE THREAD

**Issue by ParikhKadam** [mml-book/mml-book.github.io#358]
**Is your feature request related to a problem? Please describe.**
In this section, the book introduces various special types of linear mapping as:
```
Isomorphism: Φ : V → W linear and bijective
Endomorphism: Φ : V → V linear
Automorphism: Φ : V → V linear and bijective
We define id V : V → V , x 7→ x as the identity mapping or identity
automorphism in V .
```
First, those are special types of **linear** mapping. Hence, I think there's no need to write **linear** for each of these types. But that's only a minor thing.

The actual problem I am facing is, I can't find out the use cases of these special categories and hence, I can't develop an intuition of what they can do and in which way will these types be useful.

**Describe the solution you'd like**
I would like a more descriptive section on this along with a few usecases to understand them clearly.

Finally, thank you for this great book.. Everything is at its place and the examples you provide clears the queries.

**Comment by chengsoonong** [comment]
Unfortunately it is too late to include such major changes to the book.
