### ISSUE TITLE
Mistake in formular (10.42b)

### ISSUE THREAD

**Issue by shengxue** [mml-book/mml-book.github.io#359]
**Describe the mistake**
one "=" is missing in the cyclic permutation on trace operator

**Location**
Please provide the 
1. version (2019-06-12)
2. Chapter: 10
3. page: 331
4. line number/equation number: 10.42b

**Proposed solution**
A clear and concise description of what you would like to change.

**Additional context**

**Comment by mpd37** [comment]
Thanks. In the current version, this is (10.43b).
