### ISSUE TITLE
Mistake in 11.32(b)

### ISSUE THREAD

**Issue by shengxue** [mml-book/mml-book.github.io#361]
Describe the mistake
There should be a \pi_k at the very beginning of the formular 11.32(b)?

Location
Please provide the

version (2019-06-12)
Chapter: 11
page: 356
line number/equation number: 11.32b
Proposed solution
A clear and concise description of what you would like to change.

Additional context

**Comment by mpd37** [comment]
Yes, this is correct. We'll fix this with the next PDF upload.
