### ISSUE TITLE
Am I missing something about Hessian and trace?

### ISSUE THREAD

**Issue by daoo1** [mml-book/mml-book.github.io#364]
**Is your feature request related to a problem? Please describe.**
formula. 5.153, 154, 155
Does  [i1, i2, i3, i4, .... , ik] in formular 5.155 means indices of the tensor delta^k?

formula. 5.158
I do not know why tr(...) is displayed. Am I missing something?

This book is so useful to me. The mathematical materials that I have to learn for machine learning are scattered here and there, but it takes a lot of time to find them and actually study them. I think I am able to save a lot of time with this book. I have never seen English books because I do not speak English. I have already read more than half of this book. I really like it. Thanks!

**Comment by mpd37** [comment]
i1 etc. refer to the entries of delta. See (5.153) for example.

The trace in (5.158) allows us to write (5.159) in a more compact form. (5.159) is of the form (5.155)
