### ISSUE TITLE
Possible Inconsistency on pg. 160

### ISSUE THREAD

**Issue by aliunlu97** [mml-book/mml-book.github.io#366]
**Describe the mistake**
At the top of the pg. 160, in the lines 1 and 2, it is stated that
f_{i}(x_{i−1}) = σ(A_{i}x_{i−1} + b_{i})
, where A_{j}, b_{j} are model parameters for j = 1,...,K and σ() denotes the activation function.

However, in the eq. 5.113, it is stated that
f_{i} = σ_{i}(A_{i-1}f_{i−1} + b_{i-1}) for i = 1,...,K

I think there is an indexing inconsistency which can be solved by amending eq 5.113 such that
f_{i} = σ_{i}(A_{i}f_{i−1} + b_{i}) for i = 1,...,K

This would also make it more inline with the equation given on the pg. 6 of Justin Domke’s lecture notes since it is stated in those notes that:
v_{i} = σ_{i}(􏰀w_{i} · v_{Pa(i)})
, where w_{i} are the weights which correspond to our A_{i} here.􏰁

However, this would have some ramifications. It would require editing Figure 5.8 and Figure 5.9 since there would no longer be A_{0} and b_{0} but rather As and bs whose indices are incremented by 1. Additionally, subsequent equations would need to be altered to reflect this as well, such as incrementing all θ_{i} to θ_{i+1} since there would no longer be θ_{0} as well.

An easy alternative approach might be to alter lines 1 and 2 instead since that would require only very small local changes ( f_{i}(x_{i−1}) = σ(A_{i}x_{i−1} + b_{i}) becomes f_{i}(x_{i−1}) = σ(A_{i-1}x_{i−1} + b_{i-1}) ) but I think it would not be as elegant since it would not match the referenced lecture notes.

Sincerely,

**Location**
Please provide the 
1. 2019-07-27
2. 5.6.1
3. 160
4. 5.113

**Proposed solution**
Change f_{i} = σ_{i}(A_{i-1}f_{i−1} + b_{i-1}) for i = 1,...,K to f_{i} = σ_{i}(A_{i}f_{i−1} + b_{i}) for i = 1,...,K and amend subsequent equations/figures to reflect this.

**Additional context**
I am not 100% confident about this. Hence the title states _Possible_. Sorry about the inconvenience if this is not the case.

**Comment by mpd37** [comment]
I agree there's an inconsistency. I suggest changing the top of p 160 to $f_i(x_{i-1}) = \sigma(A_{i-1}x_{i-1} + b_{i-1})$

Would this resolve the issue as well?

**Comment by aliunlu97** [comment]
Yes, it would. That is indeed what I meant as an easier alternative.
