### ISSUE TITLE
Target Space = Outcome Space?

### ISSUE THREAD

**Issue by aliunlu97** [mml-book/mml-book.github.io#368]
**Is your feature request related to a problem? Please describe.**
On pg. 178, at the beginning of section 6.2 Discrete and Continuous Probabilities, T is mentioned as the outcome space rather than the target space it has so far been referred to as.

**Describe the solution you'd like**
I think it may be nice to make the following amendment on pg. 175 when T is first introduced:

"... we refer to T as the _target space_ (outcome space) ..."

**Additional context**
It is ok if it is too late to make such big changes.

Sincerely,

**Comment by chengsoonong** [comment]
Will replace the two instances of outcome space T with target space T.
