### ISSUE TITLE
Consider formally defining homomorphism in section 2.7

### ISSUE THREAD

**Issue by gwtaylor** [mml-book/mml-book.github.io#369]
Section 2.7  makes extensive use of the term homomorphism without really explaining what it is. It is clear that a linear mapping is also called a "vector space homomorphism" but this is hard to grasp what it means if the student is not familiar with a homomorphism, and it's very likely they aren't (or have at least, forgotten).

It may be useful to say something like this:

_A homomorphism is a concept from abstract algebra that describes a structure-preserving map between two algebraic structures (such as two groups, two rings, or two vector spaces). General homomorphisms are beyond the scope of this text, but it’s important to note that a linear mapping is a specific type of homomorphism: a vector space homomorphism. Its specific form is defined in 2.87. Here, the mapping is between two vector spaces, and what is preserved under the mapping is the Abelian group structure (with vector addition) and scalar multiplication._ 

The text goes on to describe more specific types of vector space homomorphisms, e.g.
- isomorphism
- endomorphism
- automorphism

But the text before this says "we introduce the following special cases of linear mappings between vector spaces V and W..."

If the reader remembers the equivalence "linear mapping = vector space homomorphism" then this reads ok, but it may be safer to say:

"we introduce the following special cases of vector space homomorphisms or linear mappings between vector spaces V and W..."
- isomorphism
- endomorphism, etc.

**Comment by mpd37** [comment]
This is a good suggestion, but we are no longer able to incorporate this change prior to printing.
