### ISSUE TITLE
[Chapter 5] Errata & feedback

### ISSUE THREAD

**Issue by RR5555** [mml-book/mml-book.github.io#37]
Would you please find here below a list of what I think to be errors, and what I think could require modifications.

Errata:
Line 2716: "where we look" instead of "where look"
Line 2855 (+5): "the gradient, we compute" instead of "the gradient compute"
Eq. (5.86): Index over the sum should be N instead of D
Eq. (5.103): Index over the sum should be m instead of n
Line 2895: ", and every" instead of ", end every"
Line 2906: "a taste" instead of "a taster"
Eq. (5.117), (5.139), (5.146): Error of sign in the derivative of the square root function
Line 2920: "f_{i}(x_{i-1})" instead of "f_{i}(x)"
Line 2925: "j" instead of "i"
Eq. (5.142): The second element of the second term of the RHS should be the partial derivative of e with respect to c instead of  the partial derivative of d with respect to c.
Eq. (5.184), (5.185): Not being very knowledgeable about it, it felt very counter-intuitive. I would have derived the equation (5.184) by applying on H the operator d\dx, but it seems the equation was derived by applying it from the inside. Though it does not modify the final result, it feels odd.

Feedback:
Eq. (5.98): Would have found it more intuitive to have a transpose of the zero vector right before the transpose of x in the RHS of the equation.
Line 2927: Notation seems ambiguous. Clarifying to make sure that people understands that \theta is the set of all A_{.} and b_{.} in contrast with \theta_{j} which contains only the associated A_{j} and b_{j} would be nice.

I did truly appreciate that chapter.

**Comment by mpd37** [comment]
"I would have derived the equation (5.184) by applying on H the operator d\dx, but it seems the equation was derived by applying it from the inside."

Can you elaborate a bit?

**Comment by RR5555** [comment]
[Eq5_184-185.pdf](https://github.com/mml-book/mml-book.github.io/files/1949384/Eq5_184-185.pdf)

**Comment by mpd37** [comment]
Thanks. Good catch - the differentiation order in d^2 f / dxdy was not defined correctly, and this propagated through to this point. It will be fixed with the next revision of the chapter.
