### ISSUE TITLE
On P205,  Cholesky decomposition can be also applied to positive semi-definite matrices

### ISSUE THREAD

**Issue by zhfkt** [mml-book/mml-book.github.io#372]
**Describe the mistake**

On the P205, there is the saying:

"To compute the Cholesky factorization of a matrix, it is required that the matrix is symmetric and positive definite (Section 3.2.3). Covariance matrices possess this property"

Covariance matrices is the positive semi-definite instead of positive definite. So in fact, Covariance matrices do not possess this property (positive definite).

According to the wiki https://en.wikipedia.org/wiki/Cholesky_decomposition , Cholesky decomposition can be also applied to positive semi-definite matrices.

------------------

"If the matrix A is Hermitian and positive semi-definite, then it still has a decomposition of the form A = LL* if the diagonal entries of L are allowed to be zero"

"However, the decomposition need not be unique when A is positive semidefinite."

------------------

**Location**
Please provide the 
1. version (bottom of page)
Draft (2019-07-28) of “Mathematics for Machine Learning”. Feedback to https://mml-book
2. Chapter
6.5.4
3. page
P205
4. line number/equation number
On the right comment of the page 205

**Proposed solution**
In  both Section 3.2.3 and P205, the author needs to mention that Cholesky decomposition can be also applied to positive semi-definite matrices.

**Additional context**
It is surprised that several errors related with "positive semi-definite" have been reported across the whole book.

**Comment by chengsoonong** [comment]
Same fix as issue #367
