### ISSUE TITLE
Give a pointer to a blog on Einstein summation the first time it's used

### ISSUE THREAD

**Issue by gwtaylor** [mml-book/mml-book.github.io#374]
Einsum syntax appears in the margin in section 2.2, page 22 (current version). It is used several times throughout the book. It's awesome to expose readers to einsum. But it's an under-appreciated function and could use a pointer for readers to get acquainted with it.

Since you've pointed to blogs in other places in the book, you could consider pointing to one or more blogs describing its use, e.g.

> For a basic introduction to NumPy's Einsum and a list of simple operations achieved by it, see [Alex Riley's blog](http://ajcr.net/Basic-guide-to-einsum/). For a much more detailed introduction to Einsum and a discussion of its inner workings, see [Olexa Bilaniuk's blog](https://obilaniu6266h16.wordpress.com/2016/02/04/einstein-summation-in-numpy/).  For a more advanced primer of its use in TensorFlow and PyTorch, see [Tim Rocktäschel's blog](https://rockt.github.io/2018/04/30/einsum).

**Comment by mpd37** [comment]
Thanks for the feedback and the suggestions. We can't add this at this time, because we are about to print, so the changes are too significant. However, we'll keep this in mind.
