### ISSUE TITLE
Numerical error in Example 3.7

### ISSUE THREAD

**Issue by gwtaylor** [mml-book/mml-book.github.io#376]
I think there is a numerical mistake in Example 3.7.

- Current version
- Section 3.3
- Page 77

I have done this by hand and checked by Python. I get cos( \omega ) = (-1/2) and not (-1/3).

```python
import numpy as np
x = np.array([1, 1])
y = np.array([-1, 1])
A = np.array([[2, 0], [0, 1]])
print(x.dot(A).dot(y) / (np.linalg.norm(x) * np.linalg.norm(y)))
print(np.linalg.multi_dot([x, A, y]) / (np.linalg.norm(x) * np.linalg.norm(y)))
```
```
-0.4999999999999999
-0.4999999999999999
```

**Comment by chengsoonong** [comment]
The example is correct. What you are missing is that the definition of a norm is dependent on the definition of the inner product (see equation (3.16)).

Here's some code to double check.
```python
import numpy as np

x = np.array([1,1])
y = np.array([-1,1])
A = np.array([[2,0], [0,1]])

def dotprod(x, y, A):
    return x.dot(A).dot(y)

def norm(x, A):
    return np.sqrt(dotprod(x, x, A))

print(dotprod(x, y, A))
print(norm(x, A))

print(dotprod(x, y, A)/(norm(x, A)*norm(y, A)))
```

**Comment by gwtaylor** [comment]
Ah right, I was still using dot product in my norms. *Facepalm*.
Sorry for the false alarm.

**Comment by chengsoonong** [comment]
No harm done. There is likely to be a still bugs in the book, but our ability to fix them for the printed version is essentially over now.
