### ISSUE TITLE
Exercise 2.4 a

### ISSUE THREAD

**Issue by DominikKoller** [mml-book/mml-book.github.io#379]
**Exercise asks for product of matrices in incompatible dimensions**

It asks for
[[1,2], [4,5], [7,8]] * [[1,1,0], [0,1,1], [1,0,1]]

Which is undefined. You might have done this on purpose, it does make students check their understanding three times before concluding it's undefined. 

**Location**
1. version 2019-07-28
2. Chapter 2
3. page 64
4. Exercise 2.4 a

**Comment by mpd37** [comment]
That's correct. This is actually on purpose. I'll add "if possible". Would that help?

**Comment by Kabongosalomon** [comment]
Definitely yes, that will be helpful.

Regards, 

Salomon KABONGO
My Website
Contact                : +27    81 008 8024
   +243 998 698 749
WhatsApp           : +254 79 58 35 461

Twitter : @Salomon
Skype    : KabongSalomon

**Comment by mpd37** [comment]
OK. This will be fixed with the next PDF update. Thanks both of you!
