### ISSUE TITLE
Add more detailed descriptions about the Conditional Variance on the P203

### ISSUE THREAD

**Issue by zhfkt** [mml-book/mml-book.github.io#381]
**Is your feature request related to a problem? Please describe.**
On P203, the author just describes the following:

--------

The last line is an illustration of the conditional variance formula: “The variance of a mixture is the mean of the conditional variance and the variance of the conditional mean.”

--------

From my opinion, this statement is confusing because we can not point out why it is related with the formula 6.85c. I think the readers can not see directly which parts are the "the mean of the conditional variance" and " the variance of the conditional mean".

**Describe the solution you'd like**
The author needs to add more detailed descriptions about the Conditional Variance on the P203 . At least,  the author needs to show the formula of conditional variance obviously.

![](http://latex.codecogs.com/gif.latex?%5Coperatorname%7BVar%7D%28Y%29%20%3D%20%5CBbb%20E%5Cleft%5B%5Coperatorname%7BVar%7D%5Cleft%28Y%5Cmid%20X%5Cright%29%5Cright%5D%20&plus;%20%5Coperatorname%7BVar%7D%5Cleft%28%5CBbb%20E%5BY%5Cmid%20X%5D%5Cright%29 )

And the author can also talk about more concept of conditional variance. The following urls are some examples:

https://math.stackexchange.com/questions/7040/conditional-and-total-variance
https://math.stackexchange.com/questions/1742578/law-of-total-variance-intuition
https://stats.stackexchange.com/questions/16608/what-is-the-variance-of-the-weighted-mixture-of-two-gaussians

Thank you

**Comment by chengsoonong** [comment]
Will add the equation above, and also add "law of total variance."
