### ISSUE TITLE
The question on the Formula 6.122 (conjugate prior for the Bernoulli distribution) on the page 214

### ISSUE THREAD

**Issue by zhfkt** [mml-book/mml-book.github.io#383]
**Describe the mistake**
This is not the issue on the mistake. This is a question.

I would like to discuss on the Formula 6.122 . i.e. conjugate prior for the Bernoulli distribution . The authors are using the Formula 6.120 to get the Formula 6.122 . From my understanding, the y1 in the 6.120 is y in the 6.122, and y2 in the 6.120 is n0 in the 6.122 .  

So I would like to ask that why the first item in the 6.122 in the exp is  "n0ylog(u/1-u)" ? According to the inner product in the 6.120, it should be 

y1 * theta - y2 * A(theta) = ylog(u/1-u) + n0log(1-u)

So the first item in the 6.122 should be "ylog(u/1-u)" instead of "n0ylog(u/1-u)" , right ? Could you help to point out whether I am wrong , or give some hint ?

Thank you

**Location**
Please provide the 
1. 2019-08-11
2. Chapter 6
3. page 214
4. Formula 6.122

**Comment by mpd37** [comment]
We are working on an updated example. Does this look better:


![image](https://user-images.githubusercontent.com/5500569/63338444-b85af900-c33a-11e9-9bac-9b7e466f4739.png)

**Comment by zhfkt** [comment]
Thank you. The new example looks better.

Out of curiosity, I also would like to get more mathematics knowledge behind this example.  Why is the y in the new example defined as [alpha, beta + alpha]T ? I know that you would like to derive to the Beta Distribution so you define the corresponding y.  But if you don't know the conjugate prior for any other distribution in the exponential family, how will you define the parameter y in advance ? Is there any math restriction on this parameter y ?

Because this mathematics knowledge is totally new to me , I ask more on it. Thank you.
