### ISSUE TITLE
Should be "not for" instead of "for" in Example 4.15

### ISSUE THREAD

**Issue by gwtaylor** [mml-book/mml-book.github.io#384]
**Describe the mistake**
This sentence:

> In this second rank-1 approximation, A_2 we capture Chandra’s ratings and movie types well, but for the science fiction movies. 

I believe should read:

In this second rank-1 approximation, A_2 we capture Chandra’s ratings and movie types well, but *not* for the science fiction movies. 

**Location**
1. 2019-08-15
2. 4
3. 133
4. Paragraph immediately after 4.100b

**Comment by mpd37** [comment]
This looks right. Here's a suggestion:

In this second rank-1 approximation A_2, we capture Chandra’s ratings and movie types well, but not the science fiction movies.
