### ISSUE TITLE
Typo (missing space)

### ISSUE THREAD

**Issue by gcalmettes** [mml-book/mml-book.github.io#385]
**Describe the mistake**
Missing space between `matrix` and `A`

**Location**
Please provide the 
1. version: 2019-08-19
2. Chapter: 2 (section 2.2.2)
3. page: 24
4. line number: 13 (start of Definition 2.3)

**Proposed solution**
Change 
Consider a square matrix**A**
to
Consider a square matrix **A**

**Comment by mpd37** [comment]
Thanks!
