### ISSUE TITLE
TOC link to Index is invalid.

### ISSUE THREAD

**Issue by fkdosilovic** [mml-book/mml-book.github.io#386]
**Describe the mistake**
When using TOC to navigate the book, link to Index jumps to page 395 (to References) instead of page 407.

**Location**
Please provide the 
1. version (bottom of page) - Draft (2019-08-19)
2. Chapter - Contents
3. page - iii
4. line number/equation number - first line from the bottom

**Proposed solution**
TOC link to Index should jump to page 407, not 395.

**Additional context**
None.

**Comment by mpd37** [comment]
Good catch; I'll fix this with the next PDF update
