### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mansoor49** [mml-book/mml-book.github.io#392]
**Describe the mistake**
dh/dt = df/dx * dx/dt

**Location**
1. 25 July 2019 
2. Chapter 5
3. page 153
4. line number/equation number 5.74a

**Proposed solution**
I believe must be dh/dt = dh/dx * dx/dt

**Comment by mpd37** [comment]
The equation should be correct because h(t) = f(g(t)). 
Therefore dh/dt = df/dg * dg/dt, where g(t) = x (which is in that equation)

Does this make more sense now?

**Comment by mansoor49** [comment]
Yes
