### ISSUE TITLE
maybe a small mistake in projection onto general subspaces

### ISSUE THREAD

**Issue by zykphzx** [mml-book/mml-book.github.io#394]
**Describe the mistake**
not  **_x_** must be orthogonal to all basis vectors of U

**Location**
Please provide the 
1. Draft (2019-08-14)
2. Chapter 3
3. page 86
4. line 11

**Proposed solution**
pi_U_(x) - x must be orthogonal to all basis vectors of U

**Additional context**

**Comment by mpd37** [comment]
This is pretty much what the text says: The difference between pi_U(x) and x must be orthogonal to all basis vectors.
