### ISSUE TITLE
Typo in Table of Abbreviations and Acronyms: "Orthonomal

### ISSUE THREAD

**Issue by lgalvao** [mml-book/mml-book.github.io#402]
**Describe the mistake**
There is a typo (missing 'r') in the Table of Abbreviations and Acronyms: "Orthonomal".

**Location**
1. Version: 2019-08-20
2. Chapter: Foreword
3. Page: 7
4. Section: Table of Abbreviations and Acronyms

**Proposed solution**
Correct to *Orthonormal*.

**Comment by mpd37** [comment]
thanks!
