### ISSUE TITLE
.mobi version

### ISSUE THREAD

**Issue by timkofu** [mml-book/mml-book.github.io#404]
First, thank you for writing this book and making it available for free.

Would it be possible to make publish a .mobi version as well for eReaders?

Thanks.

**Comment by chengsoonong** [comment]
It seems hard.

From
https://github.com/michal-h21/tex4ebook
> Note that while mobi is supported by Amazon Kindle, most widespread ebook reader, it doesn't support mathml and this means that math must re represented as images. The same is true for epub. This is not a good thing, especially for inline math, as you may experience wrong baselines. If your ebook contains math, the only correct solution is to produce epub3, as it supports mathml. The issue with epub3 is, that majority of e-ink ebook readers doesn't support this format, reader applications exists mainly for Android and Apple devices.
