### ISSUE TITLE
d and \partial

### ISSUE THREAD

**Issue by r-cui** [mml-book/mml-book.github.io#405]
**Describe the mistake**
Here's my observation when reading the book.

In (5.40) the authors use the symbol <a href="https://www.codecogs.com/eqnedit.php?latex=\frac{df}{d\boldsymbol{x}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{df}{d\boldsymbol{x}}" title="\frac{df}{d\boldsymbol{x}}" /></a> to denote a total derivative of a function <a href="https://www.codecogs.com/eqnedit.php?latex=f" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f" title="f" /></a> with respect to a vector <a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{x}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{x}" title="\boldsymbol{x}" /></a>. However, in (5.46) - (5.48), the authors use symbol <a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\partial&space;f}{\partial&space;\boldsymbol{x}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;f}{\partial&space;\boldsymbol{x}}" title="\frac{\partial f}{\partial \boldsymbol{x}}" /></a> to denote similar concept.

I think the mix-use of <a href="https://www.codecogs.com/eqnedit.php?latex=d" target="_blank"><img src="https://latex.codecogs.com/gif.latex?d" title="d" /></a> and <a href="https://www.codecogs.com/eqnedit.php?latex=\partial" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\partial" title="\partial" /></a> creates some inconsistency.

**Location**
1. version: 20190820
2. Chapter: 5
3. page: 146 and 147
4. line number/equation number: equation (5.40) vs (5.46) - (5.48)

**Proposed solution**
For concept "total derivative (gradient) of a multivariate function <a href="https://www.codecogs.com/eqnedit.php?latex=f" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f" title="f" /></a> with respect to all variables <a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{x}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{x}" title="\boldsymbol{x}" /></a>", use  <a href="https://www.codecogs.com/eqnedit.php?latex=\frac{df}{d\boldsymbol{x}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{df}{d\boldsymbol{x}}" title="\frac{df}{d\boldsymbol{x}}" /></a>.

For concept "partial derivative of a multivariate function <a href="https://www.codecogs.com/eqnedit.php?latex=f" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f" title="f" /></a> with respect to one of the variables <a href="https://www.codecogs.com/eqnedit.php?latex=x_1" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x_1" title="x_1" /></a>", use <a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\partial&space;f}{\partial&space;x_1}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;f}{\partial&space;x_1}" title="\frac{\partial f}{\partial x_1}" /></a>.

**Comment by mpd37** [comment]
(5.46)-(5.48) hold for total and partial derivatives. We decided to formulate them for partial derivatives
