### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by r-cui** [mml-book/mml-book.github.io#409]
**Describe the mistake**
"we do not expect the identifier (the Name) to be **infomative** for a machine learning task"

**Location**
1. version (bottom of page): 2019-08-20
2. Chapter: 8.1.1
3. page: 253
4. line number/equation number

**Proposed solution**
"we do not expect the identifier (the Name) to be **informative** for a machine learning task"

**Comment by mpd37** [comment]
thanks
