### ISSUE TITLE
Chapter 6.1.2 word suggestion: outcome to state

### ISSUE THREAD

**Issue by r-cui** [mml-book/mml-book.github.io#413]
**Describe the mistake**
In the following sentence, I think the word "outcome" is not quite right in the context of this book.

> For example, in the case of tossing two coins and counting the number of heads, a random variable X maps to the **three possible outcomes**: X(hh) = 2 , X(ht) = 1 , X(th) = 1 , and
X(tt) = 0 .

In the context of this paragraph where the quotation lies, an "outcome" means any element in the sample space {hh, ht, th, tt}, whereas a "state" means any element in the target space {0, 1, 2}. Saying "three possible outcomes" might lead to misunderstanding because if we care about outcomes, there are 4 of them, i.e., hh, ht, th, and tt.

**Location**
Please provide the 
1. version (bottom of page): 2019-09-17
2. Chapter: 6.1.2
3. page: 175

**Proposed solution**
For example, in the case of tossing two coins and counting the number of heads, a random variable X maps to the **three possible states**: X(hh) = 2 , X(ht) = 1 , X(th) = 1 , and
X(tt) = 0 .

**Comment by chengsoonong** [comment]
This is tricky. The word "state" can also refer to the states of the sample space $\Omega$, i.e. h, t. Later, we do tend to loosely refer to elements of the target space as states, but I'm a bit worried that changing it at this point would confuse things in a different way.

**Comment by r-cui** [comment]
I agree, this part of terminologies are difficult to distinguish. The words "state", "outcome", "event" should get more care when using them. Given this, if you think this issue I created here is a problem worth correcting, then an alternative could be changing it to "a random variable X maps to the four possible outcomes". If otherwise, you think that this is not a problem due to the fact that there's no golden rule to manage these similar terms, then I totally understand.

**Comment by chengsoonong** [comment]
There is no golden rule to manage these terms unfortunately. Ideally, we want to call elements of \mathcal{T} targets. However, this a pretty non-standard (in fact we invented this name for the space \mathcal{T}.

I want to talk about the values {0,1,2}. One option is:
"a random variable X maps to the three possible values in \mathcal{T}"

However, the chapter (in the following pages) is also sometimes mixing up these terms (state, outcome, event, values).

Given the complexity of the changes required all over the chapter, I'm closing this issue.
