### ISSUE TITLE
Word "span" missing in Example 2.26

### ISSUE THREAD

**Issue by zdenek-c** [mml-book/mml-book.github.io#414]
**Describe the mistake**
The second bullet point of Example 2.26 states that:
> The parametric equation for planes is y = x<sub>0</sub> + λ<sub>1</sub>x<sub>1</sub> + λ<sub>2</sub>x<sub>2</sub>, where λ<sub>1</sub>, λ<sub>2</sub> ∈ R
> and **U = [x<sub>1</sub>, x<sub>2</sub>] ⊆ R<sup>n</sup>**. This means that a plane is defined by a support point x<sub>0</sub> and two linearly independent vectors x<sub>1</sub>, x<sub>2</sub> that span the direction space.

**Location**
1. version (bottom of page): 2019-09-17
2. Chapter: 2.8.1
3. page: 62
4. line number: 3 

**Proposed solution**
I think that the word "span" slipped away from the definition of U, so it should be changed to:
> **U = span[x<sub>1</sub>, x<sub>2</sub>] ⊆ R<sup>n</sup>**

**Comment by mpd37** [comment]
thanks
