### ISSUE TITLE
coefficient x1 is missing which makes it confusing

### ISSUE THREAD

**Issue by cc-visionary** [mml-book/mml-book.github.io#415]
**Describe the mistake**
The explanation for equation 2.5 states:
> From the first and third equation, it follows that x 1 = 1 . From (1) + (2),
we get 2 + 3x<sub>3</sub> = 5 , i.e., x<sub>3</sub> = 1 . From (3), we then get that x<sub>2</sub> = 1 .
Therefore, (1, 1, 1) is the only possible and unique solution (verify that
(1, 1, 1) is a solution by plugging in).

**Location**
1. version (bottom of page): 2019-09-17
2. Chapter: 2.1
3. page: 20
4. equation number: 2.5

**Proposed solution**
The coefficient x<sub>1</sub> went missing at 2 + 3x<sub>3</sub> = 5, so the change should be:
2x<sub>1</sub> + 3x<sub>3</sub> = 5

**Additional context**
Although anyone can notice and still understand that this was a mistake eventually, it is still confusing at first sight. So I think its still better to correct this.

**Comment by mpd37** [comment]
good catch
