### ISSUE TITLE
Chapter 8: change likelihood to posterior

### ISSUE THREAD

**Issue by r-cui** [mml-book/mml-book.github.io#416]
**Describe the mistake**

> Recall that we are interested in finding the parameter θ that maximizes **likelihood**.

I think this part is talking about maximising posterior here, so the word "likelihood" is not very accurate. Maybe the author meant "posterior"?

**Location**
Please provide the 
1. version: 2019-10-03
2. Chapter: 8.3.2
3. page: 269
4. line number/equation number: line 10 which is just under eq (8.19)

**Proposed solution**
Recall that we are interested in finding the parameter θ that maximizes **posterior**.

**Comment by mpd37** [comment]
Thanks!
