### ISSUE TITLE
Chapter 7: Potentially wrong reference to equation

### ISSUE THREAD

**Issue by david-haber** [mml-book/mml-book.github.io#417]
**Describe the mistake**
It says "consider the function in figure 7.2" which I believe should refer to figure 7.1 (7.2 is the derivate of 7.1)

**Location**
Please provide the 
1. 2019-10-03
2. 7
3. 225
4. Last paragraph before equation

**Proposed solution**
Change text to refer to figure 7.1.

**Additional context**
-

**Comment by mpd37** [comment]
Figure 7.1 is the mimdmap. Am I missing something?

**Comment by david-haber** [comment]
Yes, saw it too now. Thanks & sorry for the false alarm.
