### ISSUE TITLE
Chapter 7, equation 7.12

### ISSUE THREAD

**Issue by dongwookim-ml** [mml-book/mml-book.github.io#419]
**Describe the mistake**

It seems the equation 7.12 is missing \alpha \Delta x_{i-1} on the right-hand side of the equation, based on the relation defined in Eq 7.11.

**Location**
Please provide the 
1. version (bottom of page): Draft 2019-07-23
2. Chapter 7
3. page 231
4. line number/equation number Eq 7.11 / 7.12

**Proposed solution**
A clear and concise description of what you would like to change.

maybe add +  \alpha \Delta x_{i-1} to the RHS of Eq 7.12?

**Additional context**

**Comment by mpd37** [comment]
I think that's correct. Thank a lot!
