### ISSUE TITLE
p.227 Possibly confusing wording and figure: Following the gradient, direction of gradient.

### ISSUE THREAD

**Issue by sebastianbertoli** [mml-book/mml-book.github.io#422]
N.b. not really a mistake but maybe the wording needs to be changed as it might be confusing to the reader not familiar with the ideas presented.

**Description**
On page 225 it is correctly stated that the gradient points us uphill and that we want to move in the opposite direction of the gradient.

> Intuitively finding the best value is like finding the val-
> leys of the objective function, and the **gradients point us uphill**. The idea is
> to **move downhill (opposite to the gradient)** and hope to find the deepest
> point.

On page 227 this information is somehow lost and the paragraph talks about moving in the direction of the gradient.  Moreover, it might be better to say x0 = -6 because x0 = -10 is not visible on the chart.

> In general, we are unable to find analytic solutions, and hence we need to start at some value, say x 0 = −10 , and **follow the gradient.**

The description for figure 7.2 and the figure also seems a bit confusing to me. Should the arrows not point in the direction of ascent?

> **Figure 7.2** Example objective function. **Gradients are indicated by arrows**, and the global minimum is indicated by the dashed blue line.

**Location**
1. Version: October 18 2019
2. Chapter 7
3. p.227

**Proposed solution**
Maybe it could be helpful to explicitly say that we are following the opposite direction of the gradient.

**Comment by chengsoonong** [comment]
Thank you.
