### ISSUE TITLE
Typos on page 291

### ISSUE THREAD

**Issue by fkdosilovic** [mml-book/mml-book.github.io#424]
**Describe the mistake**
Wrong figure is referenced. Figure 9.1(a) is referenced multiple times, while it should mention Figure 9.2.

**Location 1**
Please provide the 
1. Draft (2019-10-20)
2. Chapter 9. Linear regression
3. page 291.
4. Example 9.1. , third row ( Figure 9.1.(a) )

**Location 2.**
Please provide the 
1. Draft (2019-10-20)
2. Chapter 9. Linear regression
3. page 291.
4. Last paragraph, second row, again, Figure 9.1(a)

**Proposed solution**
Change Figure 9.1(a) to Figure 9.2(a).

**Additional context**
None.

**Comment by mpd37** [comment]
thanks for finding this. there's a but in the template that sometimes messes up the referencing of figures. should be fixed with the next push
