### ISSUE TITLE
Chapter 8 various minor corrections

### ISSUE THREAD

**Issue by sebastianbertoli** [mml-book/mml-book.github.io#425]
**Describe the mistake**
Correction/insertion in boldface.
p.254
> In recent years, deep learning methods (Goodfellow et al.,
> 2016) have shown promise in using the data itself to learn new good
> features, and ~~has been~~ **have been** very successful in areas such as computer vision,
> speech recognition, and natural language processing.

p.257 
> To apply hill-climbing approaches we use the gradients described **in**
> Chapter 5 and implement numerical optimization approaches from Chap-
> ter 7.

p.263
> We mentioned in the previous section that we measure **the** generalization er-
> ror by estimating it by applying the predictor on test data.

**Location**
1. version: Draft (2019-10-18)

**Comment by mpd37** [comment]
thanks a lot for this!

**Comment by sebastianbertoli** [comment]
It's a pleasure, the book is amazing. :)
