### ISSUE TITLE
Binder link for the tutorials

### ISSUE THREAD

**Issue by MadsJensen** [mml-book/mml-book.github.io#430]
Hi and thank you for making the book and the tutorials available! 

I wondered if you had considered adding a [binder](https://mybinder.org/) link for the tutorial notebooks, so people can just jump directly in without needing any installed etc. 

I will be happy to submit a pull request with a setup for binder if it would be helpful and /or useful.

**Comment by chengsoonong** [comment]
If you could send a pull request with a requirements.txt or environment.yml, that'll be great.

**Comment by mpd37** [comment]
we now link the tutorials to nbviewer from where things are also linked to binder. will this work?

**Comment by chengsoonong** [comment]
We can add the link at the bottom of [the website readme](https://github.com/mml-book/mml-book.github.io/blob/master/README.md) to launch the directory on Binder.

**Comment by mpd37** [comment]
This has been resolved
