### ISSUE TITLE
Error in a reference

### ISSUE THREAD

**Issue by othmanesebbouh** [mml-book/mml-book.github.io#433]
**Describe the mistake**
An error in a reference.

**Location**
Please provide the 
1. version (bottom of page): 2019-10-23
2. Chapter 4.8
3. page 136
4. line number/equation number: line 5

**Proposed solution**
Kingma and Ba -> Kingma and Welling

**Additional context**

**Comment by mpd37** [comment]
Thanks! I'll fix this with the next updated version
