### ISSUE TITLE
Chapter 5 Page 170 Q 5.5

### ISSUE THREAD

**Issue by bhonris** [mml-book/mml-book.github.io#434]
**Describe the mistake**
On page 170 in chapter 5, exercise 5.5, we see that the third function is defined as follow:
![image](https://user-images.githubusercontent.com/4752453/67637950-2b8e6780-f8b6-11e9-8bd6-4797ed8cc2e7.png)

**Location**
Please provide the 
1.  version 2019-10-27
2. chapter 5
3. page 170
4. Exercise 5.5

**Proposed solution**
![image](https://user-images.githubusercontent.com/4752453/67637939-000b7d00-f8b6-11e9-91ee-84d97392191c.png)
**Additional context**
Finding the derivative of an (n x n) matrix would lead to a 3-dimensional tensor, which is probably not the intended result.

**Comment by mpd37** [comment]
It actually is the intention: You are supposed to compute the derivative of a matrix w.r.t. a vector, which (as you said) will result in a 3-dimensional tensor.
