### ISSUE TITLE
Chapter 5, Example 5.11, Equation (5.81)

### ISSUE THREAD

**Issue by nurtayzh** [mml-book/mml-book.github.io#435]
## Describe the mistake
I think the equation 5.81 must be:
![1](https://user-images.githubusercontent.com/32160765/67850984-c5018780-fb09-11e9-9d0e-d1a3f3533837.png)

instead of 
![2](https://user-images.githubusercontent.com/32160765/67851338-891af200-fb0a-11e9-8631-94275dbfd7f3.png)

## Location
1. version 2019-10-18
2. Chapter 5
3. page 154
4. line number/equation number 5.81

## Proposed solution
![3](https://user-images.githubusercontent.com/32160765/67853003-d2207580-fb0d-11e9-8387-6a2d00fb01e2.png)

## Additional context
Reference 1: [Derivative of Dot Product of Vector-Valued Functions](https://proofwiki.org/wiki/Derivative_of_Dot_Product_of_Vector-Valued_Functions)
Reference 2: [Derivative of vector and vector transpose product](https://math.stackexchange.com/questions/1377764/derivative-of-vector-and-vector-transpose-product)

**Comment by mpd37** [comment]
Equation 5.81 is correct since we are looking at the squared norm. You can write this as \sum_i e_i^2. In your example above, you would need to define f(e) = e^T e (without the square root).
