### ISSUE TITLE
page 110 phrasing error in percentage

### ISSUE THREAD

**Issue by tlooden** [mml-book/mml-book.github.io#436]
**Describe the mistake**

It is stated that:
'A5 is a shear and stretch mapping that shrinks space by 75%'

**Location**
Please provide the 
1. version: draft 2019-08-20
2. Chapter 4 
3. page 110 top

**Proposed solution**

I think this could be more clearly formulated as:

'A5 is a shear and stretch mapping that shrinks space -TO- 75%', or alternatively:
'A5 is a shear and stretch mapping that shrinks space by 25%'

as the determinant of A5 is 0.75.

**Comment by mpd37** [comment]
Thanks! What about 
"... is a shear-and-stretch mapping that scales space by 75%" ?

This may be clearer.

**Comment by tlooden** [comment]
I think that makes sense, thank you!
