### ISSUE TITLE
Mathematically incorrect statement in Chapter 4 

### ISSUE THREAD

**Issue by gtusr** [mml-book/mml-book.github.io#437]
**Describe the mistake**
A clear and concise description of what the mistake is.

For symmetric matrices A ∈ Rn×n, the eigenvalue decomposition and
the SVD are one and the same, which follows from the spectral theorem 4.15.

**Location**
Please provide the 
1. version (bottom of page) 2019-08-11)
2. Chapter 4
3. page 127
4. line number/equation number

**Proposed solution**
A clear and concise description of what you would like to change.

symmetric + positive semi-definite => SVD = eigendecomposition

**Additional context**

Statement of spectral theorem should note that 

symmetric + positive-semidefinite => eigenvals non-negative

**Comment by mpd37** [comment]
I'm not entirely sure: The SVD requires an orthonormal basis, whereas the eigendecomposition does not require this. It is true that you *can* find an eigendecomposition that corresponds to the SVD, but you can also find an eigendecomposition, which is not an SVD.
