### ISSUE TITLE
Chapter 2: Singular matrix definition reversed

### ISSUE THREAD

**Issue by ArchitParnami** [mml-book/mml-book.github.io#439]
**Describe the mistake**
Next to Definition 2.3:

> Unfortunately, not every matrix A possesses an inverse A−1. If this **inverse does exist**, A is called regular/**invertible/nonsingular,** otherwise **singular/noninvertible.**

**Location**
Please provide the 
1. 2019-10-27 
2. 2
3. 24
4. Def 2.3

**Proposed solution**

Unfortunately, not every matrix A possesses an inverse A−1. If this inverse does exist, A is called **singular/noninvertible** otherwise regular/**invertible/nonsingular** .

**Additional context**
If the inverse does not exist, the matrix is singular/noninvertible.
http://mathworld.wolfram.com/SingularMatrix.html
https://en.wikipedia.org/wiki/Invertible_matrix

**Comment by mpd37** [comment]
A singular matrix is non-invertible. The statement in the book is:
"If this inverse does exist, A is called regular/invertible/ ..."

I'm not seeing what the problem is.

Note: the "not" you have in your suggestion is not in the text. Your statement is correct, but I think the book is also correct.

**Comment by ArchitParnami** [comment]
Sorry my bad. I kept reading the statement as if its written "if the inverse does **not** exist, A is called invertible/non-singular". Thank you for clarification though.
