### ISSUE TITLE
Cosmetic fix in Chapter 2: Figure 2.2

### ISSUE THREAD

**Issue by pranavsubramani** [mml-book/mml-book.github.io#44]
**Describe the mistake**
The used in between Linear/Affine Mapping overlaps with the box. 

**Location**
Please provide the 
1. version (bottom of page)
2. Chapter 2
3. Page 17
4. Figure 2.2

**Proposed solution**
Maybe positioning it to the center of the arrow would help

**Comment by mpd37** [comment]
Will be fixed in the next version:

![image](https://user-images.githubusercontent.com/5500569/40448231-d68da716-5ecc-11e8-971d-3a46ec10a12e.png)
