### ISSUE TITLE
Example 4.15 typo

### ISSUE THREAD

**Issue by imitusov** [mml-book/mml-book.github.io#440]
**Describe the mistake**
If I understood correctly there is '0.' missing in Example 4.15 description. It's written (entries have values > 4) but should be (entries have values > 0.4)

**Location**
Please provide the 
1. version Draft (2019-10-27)
2. Chapter 4
3. page 133
4. line number 5 / 2 lines after 4.100b equation number

**Proposed solution**
Add '0.'

**Comment by mpd37** [comment]
good catch. i'll fix this with the next update.
