### ISSUE TITLE
Minor mistake in description of Figure 12.1.

### ISSUE THREAD

**Issue by fkdosilovic** [mml-book/mml-book.github.io#441]
**Describe the mistake**
In description of Figure 12.1 you mention red crosses, but the crosses in the figure are actually orange.

**Location**
Please provide the 
1. Draft (2019-11-11) 
2. Chapter 12
3. page 371
4. Figure 12.1

**Proposed solution**
Change red to orange.

**Additional context**
None.

**Edit**: The same mistake is present in Figure 12.3 on page 374 and Figure 12.9b on page 386.

**Comment by fkdosilovic** [comment]
Additionally, you should probably also change _red_ to _orange_ in the last paragraph on page 371 on the seventh line from below.

> two different symbols (**red** cross or blue disc)

**Comment by mpd37** [comment]
Good catch!

**Comment by fkdosilovic** [comment]
It seems that you forgot to change the description of **Figure 12.3 on page 374** (orange --> red). I should have opened up a new issue for that page.

**Comment by mpd37** [comment]
had forgotten to recompile... should be there now
