### ISSUE TITLE
Minor Typo: p. 299 (ch. 9)

### ISSUE THREAD

**Issue by varivera** [mml-book/mml-book.github.io#446]
There is a small typo in page 299: a closing parenthesis is missing.

"We notice that polynomials of low degree (e.g., constants (M = 0) or linear (M = 1) fit ... "
It should read
"We notice that polynomials of low degree (e.g., constants (M = 0) or linear (M = 1)) fit ... "

**Location**
1. version
commit: 6f9872e (2 days before posting this Issue)
2. Chapter: 9
3. page: 299

**Comment by mpd37** [comment]
thanks!
