### ISSUE TITLE
Formula 9.1 and 9.3

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#447]
**Location**
1. version: Draft (2019-12-03)
2. Chapter: 9.1 Problem Formulation
3. page: 291
4. line number: Formula 9.1 and 9.3 (and 9.5b, 9.6 and 9.13)

Hello,
I find the formula 9.1 a bit strange.
To me, it should be: p(y | **x**) = N(f(**x**), σ^2) rather than p(y | **x**) = N(y | f (**x**), σ^2) since y | f (**x**) is a random variable.
For example, let's say we have a random variable y = f(**x**) + e, with e ~ N(0, σ^2)
Then, the random variable y|**x** is normal with E[y|**x**] = f(**x**) and Var(y|**x**)= σ^2.
That is, p(y | **x**) = N(f(**x**), σ^2).
Similarly, formula 9.3 should be p(y | **x**, **θ**) = N(**x**'**θ**, σ^2).
Formula 9.5b and 9.6 should be modified the same way.

Best regards,
Chris.

**Comment by mpd37** [comment]
Hi Chris,

We use both notations. When we write N(y| a, A) we want to highlight that y is the random variable with mean a and covariance matrix A; when we write N(a,A), it should be clear from the context what the random variable is. 

In the above example, f(x) is not the random variable (deterministic).

Does this resolve this issue?

**Comment by CL-BZH** [comment]
Hi Marc,
Thanks a lot for your reply.
I think I will just replace p(y | x) = N(y | f (x), σ^2) by p(y ;x) = N(f(x), σ^2) in my copy. :-)
I have trouble writing p(y | x)  when x is not a random variable...
