### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#448]
**Describtion**
Gaussian prior p(θ) = N(**0**, **I**) instead of p(θ) = N(**0**, b^2**I**)

**Location**
1. version: Draft (2019-12-03)
2. Chapter: 9.2.3 Maximum A Posteriori Estimation
3. page: 302
4. line number: First sentence of Example 9.6

**Proposed solution**
Replace p(θ) = N(**0**, **I**) by p(θ) = N(**0**, b^2**I**)

**Comment by mpd37** [comment]
In this concrete example, we chose b=1
