### ISSUE TITLE
Possible Misinterpretation in Uniqueness of solutions to Systems of Linear Equations

### ISSUE THREAD

**Issue by pranavsubramani** [mml-book/mml-book.github.io#45]
Verification by plugging in, is actually incorrect. The verification behind why this is a unique solution to the system of linear equations stems from the theorem: A system of linear equations, which is non-homogenous has a unique solution if and only if the determinant is non zero. Otherwise it has either no solutions or infinite solutions. It is also possible I misunderstood the "verify by plugging in" statement, is it indicative of both the uniqueness and existence, or only of the existence. This may just be my lack of understanding of the statement, but maybe it can be made clearer.

**Location**
1. (2018-02-25)
2. Chapter 2
3. Page 18
4. Line Number 834

**Proposed solution**
What about something along the lines of: "The existence of the solution is verified by plugging in the vector, and the uniqueness is a result of determinants (and provide a link/extra reading on the matter for those interested)?

**Additional context**
Determinants are a fairly useful concept when it comes to the understanding of basics of matrices, would it be valuable to have a mention of it in the chapter apart from the additional exercises presented at the end?

**Comment by mpd37** [comment]
Thanks for the comment. At this point in the book, we only talk about the "existence". We will introduce determinants later Chapter 4. That's why we can't really mention them here. I adjusted the wording so that it is clearer what was meant.
