### ISSUE TITLE
Full rank design matrix

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#450]
**Describe the mistake**
The remark at the end of page 296 says "When we were working without features, we required X'X to be invertible, which is the case when the rows of X are linearly independent".
Well sure, if we have more rows than columns and the rows of X are linearly independent X'X will be invertible. But we are more interested in the columns of X. Having more rows than columns, the only necessary condition we need is that the columns are linearly independent (rk(X) == number of columns of X). (We may even have rows of X that are equals)

**Location**
Please provide the 
1. version (2019-12-03)
2. Chapter 9
3. page 296-297
4. line number/equation number "Remark" at the end of page 296

**Proposed solution**
Replace "When we were working without features, we required X'X to be invertible, which is the case when the **rows** of X are linearly independent"
with
"When we were working without features, we required X'X to be invertible, which is the case when the **columns** of X are linearly independent"

**Comment by mpd37** [comment]
That's correct. 
We assume that we have more data points (rows) than features/input dimensions, and we require X to have full rank (D), which is the case when the columns are linearly independent.

Is this better:
![image](https://user-images.githubusercontent.com/5500569/70461363-5bac5700-1a6d-11ea-8a62-8c864e45172e.png)

**Comment by CL-BZH** [comment]
Perfect!
Thanks.
