### ISSUE TITLE
Could you please give the process of how to get the result, new transformation matrix, in Example 2.23(Basis change)? I can't work out this...

### ISSUE THREAD

**Issue by wizard1203** [mml-book/mml-book.github.io#451]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CL-BZH** [comment]
You must apply the Theorem 2.20.
Express the canonical basis in the new basis.
[1 0]' = 0.5*{[1, 1]' + [1, -1]'}
[0 1]' = 0.5*{[1, 1]' - [1, -1]'}
Then, you have:
S = [[1/2, 1/2], [1/2, -1/2]]
T = S^-1
T A S =  [[3, 0], [0, 1]]

**Comment by wizard1203** [comment]
> You must apply the Theorem 2.20.
> Express the canonical basis in the new basis.
> [1 0]' = 0.5*{[1, 1]' + [1, -1]'}
> [0 1]' = 0.5*{[1, 1]' - [1, -1]'}
> Then, you have:
> S = [[1/2, 1/2], [1/2, -1/2]]
> T = S^-1
> T A S = [[3, 0], [0, 1]]

I am confused about how to get the T=S^-1. How the basis in the space W changes with respect to the basis in the space V. Could you please explain it?

**Comment by CL-BZH** [comment]
To Compute T, the inverse of the matrix S, you can refer to page 33 "Calculating the Inverse".
In a vector space you have an infinity of basis.
If you have a space of finite dimension **n**, then any set of **n** linearly independent vectors is a basis for the space.
For example, in **R**^2, {[1, 0]' ; [0, 1]'} is the canonical basis, {[1, 1]' ; [1, -1]'} is another basis, another one could be {[1, 0]' ; [1, 1]'}, etc. As **R**^2 is of dimension **n**=2, all you need to have a basis of **R**^2 are 2 vectors of **R**^2 that are linearly independent.

**Comment by wizard1203** [comment]
> To Compute T, the inverse of the matrix S, you can refer to page 33 "Calculating the Inverse".
> In a vector space you have an infinity of basis.
> If you have a space of finite dimension **n**, then any set of **n** linearly independent vectors is a basis for the space.
> For example, in **R**^2, {[1, 0]' ; [0, 1]'} is the canonical basis, {[1, 1]' ; [1, -1]'} is another basis, another one could be {[1, 0]' ; [1, 1]'}, etc. As **R**^2 is of dimension **n**=2, all you need to have a basis of **R**^2 are 2 vectors of **R**^2 that are linearly independent.
> In the example, V=W=**R**^2.

I mean, I don't know why there is T=S^-1, there is nothing indicating this in the example. So, I thought the T should be the identity matrix?

**Comment by mpd37** [comment]
The example is a motivating example, why we may want to think about basis change. The rest of the section explains how to do this.

**Comment by wizard1203** [comment]
> The example is a motivating example, why we may want to think about basis change. The rest of the section explains how to do this.

So, the T does not have to be S^-1？ Can it be another transformation matrix?

**Comment by mpd37** [comment]
T does not have to be S^{-1}. For example, if the transformation matrix is not square, we these two matrices will differ. Have a look at example 2.24.

**Comment by CL-BZH** [comment]
Study carefully Theorem 2.20. The figures page 56 should help you to understand.
The matrix A of example 2.23 is the matrix of Φ : R2→ R2 expressed in the canonical basis of R2 (the canonical basis is used in the codomain and in the domain). The matrix Ã is the matrix of Φ expressed in the basis B = {[1, 1]' ; [1, -1]'} (the basis B is used in the codomain and in the domain).

First, express the vectors of the new basis B as a linear combination of the vectors of the canonical basis of R2.
[1, 1]'  = (1)[1, 0]' + (1)[0, 1]'
[1, -1]' = (1)[1, 0]' + (-1) [0, 1]'
This gives you S, the transformation matrix that maps coordinates with respect to B onto coordinates with respect to the canonical basis of R2.
S = [[1, 1],  [1, -1]]
So, in the opposite direction, the transformation matrix that maps coordinates with respect to the canonical basis of R2 onto coordinates with respect to the new basis B is the inverse of S.
You may also compute it by expressing the vectors of the canonical basis of R2  as a linear combination of the vectors of the new basis B.
[1, 0]' = (1/2)[1, 1]' + (1/2)[1, -1]'
[0, 1]' = (1/2)[1, 1]' + (-1/2) [1, -1]'
Thus, S^-1 =  [[1/2, 1/2],  [1/2, -1/2]]

Finally, Ã = S^-1 A S = [[3, 0], [0, 1]]

**Comment by wizard1203** [comment]
> Study carefully Theorem 2.20. The figures page 56 should help you to understand.
> The matrix A of example 2.23 is the matrix of Φ : R2→ R2 expressed in the canonical basis of R2 (the canonical basis is used in the codomain and in the domain). The matrix Ã is the matrix of Φ expressed in the basis B = {[1, 1]' ; [1, -1]'} (the basis B is used in the codomain and in the domain).
> 
> First, express the vectors of the new basis B as a linear combination of the vectors of the canonical basis of R2.
> [1, 1]' = (1)[1, 0]' + (1)[0, 1]'
> [1, -1]' = (1)[1, 0]' + (-1) [0, 1]'
> This gives you S, the transformation matrix that maps coordinates with respect to B onto coordinates with respect to the canonical basis of R2.
> S = [[1, 1], [1, -1]]
> So, in the opposite direction, the transformation matrix that maps coordinates with respect to the canonical basis of R2 onto coordinates with respect to the new basis B is the inverse of S.
> You may also compute it by expressing the vectors of the canonical basis of R2 as a linear combination of the vectors of the new basis B.
> [1, 0]' = (1/2)[1, 1]' + (1/2)[1, -1]'
> [0, 1]' = (1/2)[1, 1]' + (-1/2) [1, -1]'
> Thus, S^-1 = [[1/2, 1/2], [1/2, -1/2]]
> 
> Finally, Ã = S^-1 A S = [[3, 0], [0, 1]]

Thanks for your carefully interpretation. Is the basis C in the space W the canonical basis? And will the \tilde{C} change with respect to the changing of basis B in V?

**Comment by CL-BZH** [comment]
Considering notations of figure 2.11 you have:
V=W=R2
B = C ={[1, 0]' ; [0, 1]'} (the canonical basis of R2) (here the "B" is the one of the figure, not "B" of example 2.23)
\tilde{C} = \tilde{B} = {[1, 1]' ; [1, -1]'}  (what is called B in example 2.23)
A_Φ = [[2, 1], [1, 2]] (The matrix of Φ expressed in the canonical basis of V=W=R2)
\tilde{A_Φ} = [[3, 0], [0, 1]] (The matrix of Φ expressed in the basis {[1, 1]' ; [1, -1]'} of V=W=R2)

I hope this help.

**Comment by wizard1203** [comment]
> Considering notations of figure 2.11 you have:
> V=W=R2
> B = C ={[1, 0]' ; [0, 1]'} (the canonical basis of R2) (here the "B" is the one of the figure, not "B" of example 2.23)
> \tilde{C} = \tilde{B} = {[1, 1]' ; [1, -1]'} (what is called B in example 2.23)
> A_Φ = [[2, 1], [1, 2]] (The matrix of Φ expressed in the canonical basis of V=W=R2)
> \tilde{A_Φ} = [[3, 0], [0, 1]] (The matrix of Φ expressed in the basis {[1, 1]' ; [1, -1]'} of V=W=R2)
> 
> I hope this help.

Yeah, thank you. The last question, if C is some other basis like {[3,1]' ; [2, 5]'}, then what will the \tilde{C} become?

**Comment by CL-BZH** [comment]
\tilde{C} is independent of C. It is your choice of basis.
What will change is the matrix to go from C to \tilde{C} (i.e. the matrix T^{-1} in figure 2.11).
And then of course \tilde{A_Φ} will change since, as you can see on the right side of figure 2.11,
\tilde{A_Φ} = T^{-1} A_Φ S.

**Comment by wizard1203** [comment]
> \tilde{C} is independent of C. It is your choice of basis.
> What will change is the matrix to go from C to \tilde{C} (i.e. the matrix T^{-1} in figure 2.11).
> And then of course \tilde{A_Φ} will change since, as you can see on the right side of figure 2.11,
> \tilde{A_Φ} = T^{-1} A_Φ S.

I get it now. Thank you for this careful explanation.

**Comment by CL-BZH** [comment]
You're welcome.
Maybe you can close this issue.

**Comment by wizard1203** [comment]
> You're welcome.
> Maybe you can close this issue.

OK.

**Comment by navkapil** [comment]
I think you should include the learning of the issue in the book

**Comment by CL-BZH** [comment]
Hi robml,
I think you misunderstood.
S is the transformation matrix of the **identity application** when the domain basis is B_tilde and the codomain basis is B.
I hope this help.
Chris.
