### ISSUE TITLE
Margin notes for 9.3.4 Posterior Predictions

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#453]
**Is your feature request related to a problem? Please describe.**
The last sentence of page 308 (9.3.4 Posterior Predictions) "The predictive mean φ'(x)m_N coincides with the MAP estimate" could be clarified by adding 2 margin notes.

**Describe the solution you'd like**
Since we have the parameter posterior p(θ | X , Y) = N (m_N , S_N) we could have in the margin a first note saying that θ_MAP = m_N.
And then, a second note below saying that since y = φ'(x)θ, y_MAP = φ'(x)m_N.

**Comment by mpd37** [comment]
Good points. 

I already fixed the wording in that sentence you mentioned to "The predictive mean [...]
coincides with the predictions made with the MAP estimate."

The margin notes make sense, but I'll leave them as a feature request at this time.
