### ISSUE TITLE
E not E_θ

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#454]
**Describe the mistake**
Formula (9.62) and (9.63a) use E_θ and Cov_θ for the expected value and covariance of Y|X.
I believe it should be E and Cov. That is, not with respect to θ only since Y|X=(Xθ + e)|X with θ and e independent random variables.

**Location**
1. version: 2019-12-07
2. Chapter: 9
3. page: 312
4. line number/equation number: Formula (9.62) and (9.63a)

**Proposed solution**
Replace E_θ and Cov_θ by E and Cov respectively.
Furthermore, the conditioning on X should not be dropped.
The formula would be:
(9.62)  E[Y | X ] = E[Xθ + e | X] = X E[θ] = X m_0 .
(9.63a) Cov[Y|X ] = Cov[Xθ | X] + Cov[e] = X Cov[θ] X' + σ^2 I

**Comment by mpd37** [comment]
Here's my suggested fix:

![image](https://user-images.githubusercontent.com/5500569/70631011-57a14600-1be1-11ea-9c25-fff3e640676f.png)


I do want to keep the subscripts in some places to emphasize what the random variables are.

**Comment by CL-BZH** [comment]
Hi Marc,
With the epsilon subscript added it is now correct.
Thank you.
Chris.

________________________________
De : Marc Deisenroth <notifications@github.com>
Envoyé : mercredi 11 décembre 2019 14:42
À : mml-book/mml-book.github.io <mml-book.github.io@noreply.github.com>
Cc : Christophe Louargant <christophe_louargant@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [mml-book/mml-book.github.io] E not E_θ (#454)


Here's my suggested fix:

[image]<https://user-images.githubusercontent.com/5500569/70631011-57a14600-1be1-11ea-9c25-fff3e640676f.png>

I do want to keep the subscripts in some places to emphasize what the random variables are.
