### ISSUE TITLE
Transpose missing

### ISSUE THREAD

**Issue by CL-BZH** [mml-book/mml-book.github.io#455]
**Describe the mistake**
There seems to be a small error in the first term of formula (9.71).
Φ(Φ' Φ)^−1Φy should be Φ(Φ' Φ)^−1Φ'y (i.e. the last Φ before y should be transposed).

**Location**
1. version: 2019-12-07
2. Chapter: 9
3. page: 314
4. line number/equation number: Formula  (9.71)

**Proposed solution**
Replace Φ(Φ' Φ)^−1Φy  by  Φ(Φ' Φ)^−1Φ'y

**Comment by mpd37** [comment]
good catch. I'll fix this with the next update.
