### ISSUE TITLE
Can i request for Kindle version of this book

### ISSUE THREAD

**Issue by nikhilkuyya** [mml-book/mml-book.github.io#458]

**Comment by mpd37** [comment]
There's a plan to have an ebook version, but we don't know when this will happen

**Comment by mpd37** [comment]
You can order the Kindle version here:
https://www.amazon.co.uk/Mathematics-Machine-Learning-Peter-Deisenroth-ebook/dp/B082Q2CC44/ref=sr_1_1?keywords=mathematics+for+machine+learning&qid=1578048522&sr=8-1
