### ISSUE TITLE
Possible extra word on page 40.

### ISSUE THREAD

**Issue by fkdosilovic** [mml-book/mml-book.github.io#460]
**Describe the mistake**
At the top of **page 40**, remark on vector subspaces says that _...U ⊆ (R^n, +, ·) is the solution space of a homogeneous system of **homogeneous linear equations** Ax = 0 for x ∈ R^n ..._ . Is this boldfaced _homogeneous_ extra.

**Location**
Please provide the 
1. Draft (2019-12-11)
2. Linear Algebra
3. page 40
4. Second line from the top.

**Proposed solution**
Should the sentence be _...U ⊆ (R^n, +, ·) is the solution space of a homogeneous system of **linear equations** Ax = 0 for x ∈ R^n ..._?

**Additional context**
None.

**Comment by mpd37** [comment]
I'll remove it. Thanks!
