### ISSUE TITLE
Random variables flipped in description of likelihood portion of Bayes' formula

### ISSUE THREAD

**Issue by sdv4** [mml-book/mml-book.github.io#461]
**Describe the mistake**
The way the conditional probability is described has the random variables backwards, reading: 

> We call $p(y|x)$ either the "likelihood of x (given y)" ...

**Location**
1. version (bottom of page): Draft (2019-12-11)
2. Chapter: 6.3
3. page: 185
4. line number/equation number: line -5

**Proposed solution**
Fix typo to read:

> We call $p(y|x)$ either the "likelihood of y (given x)" ...

I am happy to fix typos and submit the fix as pull requests if you add the tex version of the book to the repo.

**Comment by mpd37** [comment]
This is actually correct: p(y|x) is the likelihood of x given y, but the conditional probability distribution of y given x. Note that the likelihood is not a distribution in x.

Have a look at David MacKay's book (p. 29):
http://www.inference.org.uk/itprnn/book.pdf

**Comment by sebastianbertoli** [comment]
Interesting, thanks for the reference Marc. I hope it is ok if I ask a question regarding this. On page 29 of McKay we find the following statement:
> "Never say ‘the likelihood of the data’. Always say ‘the likelihood
> of the parameters’. The likelihood function is not a probability
> distribution."

But on slide 67, [Lecture 21 (Parameter Estimation)]( https://web.stanford.edu/class/archive/cs/cs109/cs109.1196/lectures/21%20-%20MLE.pdf) of  [Stanford's CS109 (Probability for computer scientists) ](http://web.stanford.edu/class/cs109/) the title of the slide is "The likelihood of the data" and it goes about explaining the likelihood function.

[Screenshot Slide 67](https://imgur.com/FbTyjr9)

Is this slide then incorrect in using the term or am I missing something?

Thanks!

**Comment by mpd37** [comment]
The title of the slide is wrong. It's not the likelihood of the data. 
You can also see this on the slide: It says that the likelihood function is a function of the parameters: L(\theta).

**Comment by sebastianbertoli** [comment]
Got it, thank you very much! :)

**Comment by sdv4** [comment]
@mpd37 Thanks for the clarification!
