### ISSUE TITLE
Element of vector \bold{x} referred to as z

### ISSUE THREAD

**Issue by sdv4** [mml-book/mml-book.github.io#462]
**Describe the mistake**
When expressing the cdf as the integral of the pdf, the elements of the random variable X in the vector x are referred to as z_i instead of x_i. 

**Location**
1. version (bottom of page): Draft (2019-12-11)
2. Chapter: 6.3
3. page: 181
4. line number/equation number: 6.18

**Proposed solution**
Refer to the elements of the random variable X in the vector x as x_i instead of z_i

I am happy to fix typos and submit the fix as pull requests if you add the tex version of the book to the repo.

**Comment by mpd37** [comment]
Equation (6.18) looks fine to me. We need to define an integrand f(z), where we integrate out the individual z_i up to the value of x_i.
