### ISSUE TITLE
Typo p.243 line 3 Section 7.3.3

### ISSUE THREAD

**Issue by Simeonedef** [mml-book/mml-book.github.io#463]
Thank you for the amazing book ! The way you guys explain concepts is so intuitive and has honestly really deepened my understanding of mathematical concepts !

I found a tiny typo on p.243 line 3 section 7.3.3: "To understand Definition 7.4 in a geometric fashion, consider **an nice** simple one-dimensional convex and differentiable function..."

**Comment by mpd37** [comment]
thanks!
