### ISSUE TITLE
Confusing Symbol

### ISSUE THREAD

**Issue by jackli777** [mml-book/mml-book.github.io#464]
---
name: Confusing Symbol
about: Create a report to help us improve

---

**Describe the mistake**
An confusing symbol denoting operations in vector space.

**Location**
Please provide the 
1. version Draft (2020-01-01) of "Mathematics for Machine Learning"
2. Chapter 2
3. Page 37
4. Equation Number 2.62 and 2.63

**Proposed solution**
× might be replaced with ⊗, since × may be interpreted as multiplication, which contradicts to + and ·, the symbol ⊗ is a more generalized form, and also in line with the Definition 2.7 on Page 36

**Additional context**

**Comment by mpd37** [comment]
we consistently use this throughout the book. There is no ideal symbol. The symbol you propose is often used as a tensor product 
https://en.wikipedia.org/wiki/Tensor_product
