### ISSUE TITLE
Mistakes in Equations (5.104) and (5.105)

### ISSUE THREAD

**Issue by taolian** [mml-book/mml-book.github.io#465]
**Describe the mistake**
Mistakes in Equations (5.104) and (5.105)
![Eq](https://user-images.githubusercontent.com/5706276/71899047-dd3ef400-3195-11ea-8f79-07d1ab49130b.png)

**Location**
Please provide the 
1. version (bottom of page): Draft (2020-01-01)
2. Chapter: 5.5 Useful Identities for Computing Gradients
3. page: 158
4. line number/equation number: (5.104) and (5.105)

**Proposed solution**
The right hand of Equations (5.104) and (5.105) should be **a**, rather than the transpose of **a**.

**Additional context**

**Comment by mpd37** [comment]
The derivative of a scalar (which x^T * a ) is w.r.t. a column vector is a row vector. Therefore, the equations should be fine.
