### ISSUE TITLE
Undocumented Symbol

### ISSUE THREAD

**Issue by mthelm85** [mml-book/mml-book.github.io#467]
**Is your feature request related to a problem? Please describe.**
On page 25 in Section 2.2.3, the symbol there is a symbol that looks like a lowercase u or v with a vertical line running through the middle. This symbol is undocumented and it's unclear to me what it is. Is it just another scalar, like lambda (which is documented on page 6)?

**Describe the solution you'd like**
I would like to see this symbol documented and maybe a sentence explaining what it is in 2.2.3.

**Additional context**
![mmlbook](https://user-images.githubusercontent.com/30706758/72354677-c7589400-36ab-11ea-84a1-aab037005842.PNG)

**Comment by mpd37** [comment]
Yes, it's a scalar called psi
https://en.wikipedia.org/wiki/Psi_(Greek)

**Comment by mthelm85** [comment]
Thank you!! : )
