### ISSUE TITLE
Chapter 4, Example 4.15, calculation error

### ISSUE THREAD

**Issue by tl323** [mml-book/mml-book.github.io#468]
**Describe the mistake**
Columns 1 and 3 in matrix A2 (4.101b) are incorrect

**Location**
Please provide the 
1. version 2020
2. chapter 4
3. page 133
4. equation number 4.101b

**Proposed solution**
Numbers in columns 1 and 3 should be different

**Comment by mpd37** [comment]
Thanks for catching this!

**Comment by tl323** [comment]
Happy to be of help. Thank you soooo much for a wonderful book!
