### ISSUE TITLE
Eq 5.48 missing a term in the middle

### ISSUE THREAD

**Issue by vatai** [mml-book/mml-book.github.io#469]
**Describe the mistake**
A \frac{\partial f}{\patial x}... is missing.

**Location**
Please provide the 
1. version 2019-12-07
2. Chapter 5
3. page 148
4. line number/equation number 5.48

**Proposed solution**
Add missing term.

**Additional context**
Sorry for not being detailed. It's hard to write latex on a phone, but I'm afraid I'll forget to write this is I don't do it now.

**Comment by mpd37** [comment]
what exactly is missing here?

**Comment by vatai** [comment]
Sorry, it seems I was tired. Misread/misinterpreted.
