### ISSUE TITLE
Missing line numbers, words and typos (pages 255-259, chapter 10)

### ISSUE THREAD

**Issue by snikumbh** [mml-book/mml-book.github.io#47]
**Missing line numbers and words in chapter 10** 
Version number: Draft chapter (May 28, 2018)

1. Many lines in chapter 10 PDF have line numbers missing. Examples:
-See line number 4442-4443 (page 255)
-See line number 4501-4502 (page 257)
-See line number 4518-4519 (page 257-258)

2. Also, some places words seem to be missing or have minor typos.
- See line number 4480, page 256, the sentence "[...] corresponding to the training" is missing the word "data"? 
- See line number 4481, page 256, the sentence "Intuitively we imagine nice data for binary classification [...]" --> did you mean to use "nicely separable" here?, or it would be useful to let the reader know what "nice" means in this context. 
I haven't read the earlier chapters (came across this just today), so I apologize in advance if this has been explained before. In that case referring to it could still be useful.
- See line number 4483, page 256, "[...] arranged in such _as_ way as to allow [...]" --> "[...] arranged such _a_ way as to allow [...]"

3. See line number 4527, "[...] have _a_ many possible classifiers." -- > "have many possible classifiers."

Thanks.

**Comment by austinjtaylor** [comment]
See line number 4583, page 262, the sentence "[...] we argues that we would like to [...]" --> "[...] we argue that we would like to [...]"

**Comment by chengsoonong** [comment]
Thanks for your comments. This will be fixed in the upcoming version.

**Comment by chengsoonong** [comment]
We do not intend to keep the line numbers in the final draft. They are currently there so that you can precisely point out the location of the problem.
