### ISSUE TITLE
Missing definition of backslash set notation

### ISSUE THREAD

**Issue by OlyDLG** [mml-book/mml-book.github.io#470]
**Describe the mistake**
Example 2.10, fifth bullet, uses the notation A\B (A, B sets) without definition (including in the Table of Symbols).

**Location**
Please provide the 
1. version (bottom of page)
Draft 2020-01-01
2. Chapter
Chapter 2
3. page
Page 36
4. line number/equation number
Example 2.10, Bullet 5

**Proposed solution**
Add definition of the notation, preferably both here ("first use") and in the Table of Symbols, but at the very least in the latter.

**Additional context**
Especially important, given that the notation is subsequently used, more than once, in the Exercises, and that mathematicians will probably know what is meant, but many (most?) other readers may not.

**Comment by mpd37** [comment]
Thanks for the suggestion. I'll add something to the table of symbols, but I can't change the main text at this point in time.
