### ISSUE TITLE
Missing definition of argmin/argmax

### ISSUE THREAD

**Issue by OlyDLG** [mml-book/mml-book.github.io#471]
**Describe the mistake**
Notation arg min, arg max, argmin argmax undefined (and formatted inconsistently).

**Location**
Please provide the 
1. version (bottom of page)
Draft 2020-01-01
2. Chapter
First occurrence in Chapter 4, subsequent (also undefined) uses in Chpts. 8, 9, 10, & 12
3. page
131 (f.o.), et al.
4. line number/equation number
Eq. 4.94, et al.
**Proposed solution**
Add definition in (at least) the Table of Symbols, and (preferably) also at first use.  Also, standardize format to either argmin/argmax or arg min/arg max (both formats occur at the various usages; personally, I would suggest "no space," i.e., argmin/argmax b/c arg already means something else in mathematics, and so arg min/arg max might be construed erroneously--indeed, this is precisely why/how I noticed the issue--but the important thing is consistency).

**Additional context**
Apparently, I was taught mathematics before this became "standard notation" (or my education was in too different of a realm, i.e., not in optimization): the only meaning I knew for arg, before seeing this, was as the argument, i.e., "angle," of a complex number!  Fortunately, Google "knew" of this meaning of argmin/argmax (and frankly, I am grateful to now have this notation in my repertoire: it has always been cumbersome when communicating, esp. to students, about the distinction between the extreme value of a function vs. the domain location of that extremum) but I suspect that other old fogies like me might get similarly tripped up by this.

**Comment by mpd37** [comment]
Thanks for the suggestion. I'll add something in the table of symbols. Changing the main text is no longer possible at this point.
