### ISSUE TITLE
Typo in Eq. 9.26

### ISSUE THREAD

**Issue by OlyDLG** [mml-book/mml-book.github.io#473]
**Describe the mistake**
In Eq. 9.26, \in is used where = is meant

**Location**
Please provide the 
1. version (bottom of page)
Draft 2010-01-01
2. Chapter
9.2
3. page
301
4. line number/equation number
Eq. 9.26

**
Change \in to =

**Additional context**

**Comment by mpd37** [comment]
The argmin returns a set. Any solution in this set is equally good. Only if the set contains a single element, the \in can be replaced with "=".
Therefore, we prefer leaving the \in here.

**Comment by OlyDLG** [comment]
In that case, I would argue that your use of the verb "solve" is improper: what you mean is "find" the set of \theta_{MAP} such that \theta_{MAP} \in ...
