### ISSUE TITLE
Mismatch of object types

### ISSUE THREAD

**Issue by OlyDLG** [mml-book/mml-book.github.io#475]
**Describe the mistake**
"The similarity measure we use in the following is the squared Euclidean norm ∥x − x ̃∥2 between x and x ̃."  The norm is a scalar, whereas x and x~ are vectors, so the meaning of the preposition "between" is ambiguous (at best).

**Location**
Please provide the 
1. version (bottom of page)
Draft 2020-01-01

2. Chapter
10

3. page
327

4. line number/equation number
First sentence of second full paragraph.

**Proposed solution**
Rewrite sentence to more accurately state its intended meaning.

**Additional context**

**Comment by mpd37** [comment]
Thanks for the feedback. Would you be more happy with "squared distance (Euclidean norm) between ... " ?
Maybe I'm not quite understanding the issue correctly. Would be great if you could clarify a bit more.

**Comment by OlyDLG** [comment]
How can a scalar be "between" two vectors?

**Comment by mpd37** [comment]
Can you make a concrete suggestion?

**Comment by mpd37** [comment]
I reworded the text according to my suggestion above. This will be fixed with the next revision.
