### ISSUE TITLE
Extra "the"

### ISSUE THREAD

**Issue by OlyDLG** [mml-book/mml-book.github.io#476]
**Describe the mistake**
"We therefore define our objective as the minimizing the average squared Euclidean distance."  One too many "the"s.

**Location**
Please provide the 
1. version (b
Draft: 2020-01-01

2. Chapter
10

3. page
327

4. line number/equation number
2nd sentence of second full paragraph 

**Proposed solution**
I'm guessing what's intended is:
"We therefore define our objective as minimizing the average squared Euclidean distance" or "We therefore define our objective as the minimum of the average squared Euclidean distance"

**Additional context**

**Comment by mpd37** [comment]
Good catch! Will be fixed with the next update.
