### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by OlyDLG** [mml-book/mml-book.github.io#477]
**Describe the mistake**
"In the following, we use exactly this kind of representation of x ̃ to find optimal coordinates z and basia vectors b1,...,bM such that x ̃is as sim- ilar to the original data point x"..."as possible"? I.e., you've used the phrase "A is as similar to B" without supplying the implied syntactic consequent "as C is to D": you've left the idiom incomplete.

**Location**
Please provide the 
1. version (bottom of page)
Draft 2020-01-01

2. Chapter
10

3. page
326

4. line number/equation number
First sentence of last complete paragraph on the page.

**Proposed solution**
I'm guessing the intended meaning is "as similar...as possible, i.e., ...

**Additional context**

**Comment by mpd37** [comment]
Thanks! Will be fixed with the next update.
