### ISSUE TITLE
Definition 2.19 Transformation matrix

### ISSUE THREAD

**Issue by navkapil** [mml-book/mml-book.github.io#478]
**Describe the mistake**
\phi is function defined from Vector space V to Vector space W and the respective set of basis vectors are B and C. Then by equation 2.92 what we want to tell 
Does that is how \phi is defined on the basis vectors in B or we want to say that since \phi is mapped to space C and that is why \phi(b_j) can be written as linear combination of basis vectors in C

I think this can be clearly written in the book

**Location**

1. version (bottom of page)Draft (2019-10-27)
2. Chapter 2
3. page 51
4. line number/equation number 2.92

**Comment by mpd37** [comment]
\Phi by itself is not limited to a particular choice of basis in V and W. However, if you map basis vectors b_i into W, where you also have a basis chosen, then the image \Phi(b_i) can be uniquely expressed by a linear combination of the basis vectors in W.
