### ISSUE TITLE
Figure 10.11

### ISSUE THREAD

**Issue by mpd37** [mml-book/mml-book.github.io#48]
**Describe the mistake**
A clear and concise description of what the mistake is.
The caption of Figure 10.11 is not visible

**Location**
Please provide the 
1. version (bottom of page)
(2018-05-28
2. Chapter
10
3. page
275
4. line number/equation number
4762

**Proposed solution**
There must be a bug in the figure environment

**Comment by chengsoonong** [comment]
Will be fixed in the next update.
