### ISSUE TITLE
Dangling period caused by extra space 

### ISSUE THREAD

**Issue by vatai** [mml-book/mml-book.github.io#482]
**Describe the mistake**
The period/full-stop at **Section 7.3.3, end of 1st paragraph** (middle of the page) seem to have a space before it, causing it to appear in a line of it's own.

**Location**
Please provide the 
1. version (2020-01-27)
2. Chapter 7 (section 7.3.3)
3. page 242
4. line number 20-21

**Proposed solution**
Remove the space so the last word ("concept") is followed immediately by the period, without a line break.

**Comment by mpd37** [comment]
Thanks! Will be fixed with next revision
