### ISSUE TITLE
Typo in problem 5.9

### ISSUE THREAD

**Issue by carlolimb** [mml-book/mml-book.github.io#485]
5.9 
We define
g(z,v):= log p(x,z) - log q(z,v)
z := t(e,v)

What is x in p(x,z)? It would make sense if it was a v and we considered p(v,z).

**Comment by mpd37** [comment]
The definition is OK. The x does not play an important role in the context of the question. But we didn't want to reformulate it as p(z) alone as it resembles a problem in variational inference. Agree it's probably misleading, but I don't have a good workaround.

**Comment by carlolimb** [comment]
Thanks for the quick response. Would it be prudent to state x \in
\mathbb{R}^n and/or the dimension of the other variables?

**Comment by mpd37** [comment]
Good suggestion. I'll add this.
