### ISSUE TITLE
chapter 2. example 2.22(d). mistake in transformation matrix.

### ISSUE THREAD

**Issue by aptmess** [mml-book/mml-book.github.io#486]
**Describe the mistake**
The result of Linear Transformation in item (d) isn't right, or the matrix A3 isn't correct to transform original data in in picture (d).

**Location**
Please provide the 
1. Draft 2020-02-24
2. Chapter 2
3. page 52 bottom
4. (2.97), Example 2.22 (d)

**Proposed solution**

I would have switched elements on secondary diagonal in matrix A3. After that change, the visualisation of transformation (d) would be correct.

**Additional context**
![argument](https://user-images.githubusercontent.com/43338025/75476652-074daf00-59ac-11ea-91fc-9f6661c4aaae.png)

**Comment by aptmess** [comment]
am i right or not?..

**Comment by mpd37** [comment]
I'll look into this. Haven't had the time yet

**Comment by mpd37** [comment]
I think the figure in the book is correct.
`
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

def linear_trafo(A, data):
    return A @ data

N = 20
grid = np.linspace(-0.5,0.5,N)
x, y = np.array(np.meshgrid(grid, grid))
x = x.reshape(N**2, 1)
y = y.reshape(N**2, 1)
data = np.hstack([x, y]).T

A = np.array([[1.5, -0.5], [0.5, -0.5]])
print(A)

d = linear_trafo(A, data)

plt.scatter(d[0,:], d[1,:]);`

**Comment by mpd37** [comment]
closed due to inactivity
