### ISSUE TITLE
Probably typo in equation (10.68a)

### ISSUE THREAD

**Issue by Ant3ng** [mml-book/mml-book.github.io#487]
**Describe the mistake**
About right-hand-side of (10.68a), **_B_** is missing

∮p(x | z, μ, σ2)p(z)dz
　→    ∮p(x | z, **_B_**,  μ, σ2)p(z)dz

**Location**
1. 2020-02-24
2. Chapter: 10
3. page: 342

----
I am learning a lot from your book, and I really appreciate that!

**Comment by mpd37** [comment]
Thanks~
