### ISSUE TITLE
Being more precise when giving an example of the Moore-Penrose pseudo-inverse.

### ISSUE THREAD

**Issue by SyxtonPrime** [mml-book/mml-book.github.io#49]
**Describe the mistake**
The way this line is worded seems to suggest that the given Moore-Penrose pseudo-inverse can work for non-invertible square matrices. 

**Location**
Please provide the 
1. version: Draft 2018-05-28
2. chapter: 2
3. page: 29
4. line number/equation number: 870/2.46

**Proposed solution**
Perhaps give the mild assumptions required for 2.46 to hold. (The columns of the matrix must be linearly independent).

**Comment by mpd37** [comment]
![image](https://user-images.githubusercontent.com/5500569/41740188-26d6c7b0-758f-11e8-8620-b3c3ff41510d.png)

fixed in next revision

**Comment by SyxtonPrime** [comment]
Looks good, I think you may be missing a word in the added line though.  Did you mean:

A needs to "have" linearly independent columns?

**Comment by mpd37** [comment]
Yes. I changed that, too. Thanks!

**Comment by mandarm** [comment]
Shouldn't "A needs to have linearly independent columns" really be "A needs to be of full rank"?

A = [ 1 1 1
         1 0 0
         0 1 0
         0 0 1 ]

has 3 l.i. columns, but A^T A is not invertible.
