### ISSUE TITLE
Gaussian mixture distribution desity does not integrate to 1

### ISSUE THREAD

**Issue by hanyangshu1** [mml-book/mml-book.github.io#490]
**Describe the mistake**
Figure 11.2 shows an incorrect pdf of the GMM because it does not integrate to 1. i.e, the value of p(-2) should be about 0.14.

**Location**
Please provide the 
1. version 2020-02-24
2. Chapter 11
3. Page 350
4. line number/equation number

**Comment by mpd37** [comment]
I get p(-2) =  0.2880; The plot looks fine to me.
