### ISSUE TITLE
p.117, Geometric Intuition for the Eigendecomposition

### ISSUE THREAD

**Issue by novice-mercenary** [mml-book/mml-book.github.io#493]
**Describe the mistake**
A clear and concise description of what the mistake is.
Wrong sentences, 
1. Let A be the transformation matrix of a linear mapping with respect to **the standard basis.**
2. P^(-1) performs  a basis change **from the standard basis into the eigenbasis.**

**Location**
Please provide the 
1. version (bottom of page) : Draft (2020-03-07)
2. Chapter : 4
3. page : 117
4. line number/equation number : 
In Geometric Intuition for the Eigendecomposition, line 2~4

**Proposed solution**
A clear and concise description of what you would like to change.
1. the standard basis -> eigenbasis
2. from the standard basis into the eigenbasis -> from the eigenbasis into the standard basis

**Comment by novice-mercenary** [comment]
I was mistaken. Figure 4.7 is wrong. 
it does not match lines 2~4 in Geometric Intuition for the Eigendecomposition.

**Comment by mpd37** [comment]
Agree, the wording is not great and misleading. Solution proposal (same as main text):

Top-left to bottom-left: P^{-1}performs a basis change (here drawn in R^2 and depicted as a rotation-like operation) from the standard basis into the eigenbasis.
