### ISSUE TITLE
Add problem solutions for every chapter

### ISSUE THREAD

**Issue by gordicaleksa** [mml-book/mml-book.github.io#494]
Awesome book!

Do you have the problem solutions somewhere already (am I missing something)? 

If not I'd suggest adding it as it seems that the problems are a bit more advanced than the theory covered in the book (or better said more broad). For example problem 2.2 in Linear Algebra chapter.

**Comment by chengsoonong** [comment]
We have agreed with the publisher CUP that we will not be publicly making solutions available.
