### ISSUE TITLE
(Z,+) is an abelian group

### ISSUE THREAD

**Issue by lotryisagoodperson** [mml-book/mml-book.github.io#495]
**Describe the mistake**
(Z,+) is a group

**Location**
Please provide the 
1. Draft (2020-03-07)
2. Chapter 2
3. page 36
4. Example 2.10 (Groups)

**Proposed solution**
(Z,+) is an abelian group

**Additional context**

**Comment by mpd37** [comment]
Thanks. I'll change this with the next update.
