### ISSUE TITLE
Definition of Inverse element

### ISSUE THREAD

**Issue by lotryisagoodperson** [mml-book/mml-book.github.io#496]
**Describe the mistake**
In Inverse element definition, the e is not any random element  e E G, but e is the neutral element from the neutral element definition 2.7 (3)  

**Location**
Please provide the 
1.Draft (2020-03-07)
2. Chapter 2
3. page 36
4. Definition 2.7 , (4) Inverse element

**Proposed solution**
Addition of the sentence , "where e is the neutral element"

**Additional context**

**Comment by mpd37** [comment]
I'll add this clarification. Thanks for the suggestion!
