### ISSUE TITLE
Definition of Basis: Proper Subset

### ISSUE THREAD

**Issue by RobMcH** [mml-book/mml-book.github.io#497]
**Describe the mistake**

> A generating set A of V is called minimal if there exists no smaller set A' ⊆ A ⊆ V that spans V .

**Location**
Please provide the 

1. Draft (2020-03-07)
2. Chapter 2
3. Page 44
4. Definition 2.14

**Proposed Solution**
If A' were smaller, than it wouldn't be a subset but a proper subset of A. Therefore, it should be A' ⊂ A ⊆ V.

**Comment by mpd37** [comment]
Would this be better?
![image](https://user-images.githubusercontent.com/5500569/77820778-a1546480-70dc-11ea-8b44-713a6bf9ea6b.png)
