### ISSUE TITLE
Typo in 3.7

### ISSUE THREAD

**Issue by nschmeller** [mml-book/mml-book.github.io#498]
**Describe the mistake**
Second paragraph, second sentence reads "We can think of a vector x ∈ Rn as function with n function values", should read "We can think of a vector x ∈ Rn as [a] function with n function values"

**Location**
1. Version (Draft 2020-03-07) (most recent download as of time of posting)
2. Chapter: 3
3. Page: 80

**Proposed solution**
Very small typo, add indefinite article "a"

**Additional context**
Hope this isn't too nitpicky!

**Comment by mpd37** [comment]
thanks!
