### ISSUE TITLE
Intuitive Definition of Kernel

### ISSUE THREAD

**Issue by RobMcH** [mml-book/mml-book.github.io#499]
**Describe the mistake**

> Intuitively, the kernel is the set of vectors in v ∈ V that Φ maps onto the neutral element 0w ∈ W.

**Location**
Please provide the 
1. Draft (2020-03-07)
2. Chapter 2
3. Page 58
4. Right beneath definition 2.23

**Proposed solution**
It should be either "the set of vectors in V [...]" or "the set of vectors v ∈ V [...]", since v is a single vector and therefore "in v ∈ V" is wrong.

**Comment by mpd37** [comment]
Thanks. It will be fixed with the next update.
