### ISSUE TITLE
Minor wording issue in the second example in section 2.1.

### ISSUE THREAD

**Issue by SyxtonPrime** [mml-book/mml-book.github.io#50]
**Describe the mistake**
The line: "Adding the first two equations yields (1) + (2) = 2x_1 + 3x_3 = 5"
feels a little off because the 2 uses of = here are fundamentally different.

Really, (1) + (2) = (2x_1 + 3x_3 = 5) but this bracketing could be confusing,

**Location**
Please provide the 
1. version: (2018-05-28) 
2. Chapter: 2
3. page: 16
4. line number/equation number : Below 701/2.4

**Proposed solution**
Reword the line to be: Adding the first two equations ((1) + (2)) yields 2x_1 + 3x_3 = 5
or: Adding the first two equations yields 2x_1 + 3x_3 = 5

**Comment by mpd37** [comment]
will be fixed with next revision.
