### ISSUE TITLE
The definition of group

### ISSUE THREAD

**Issue by dj-zhou** [mml-book/mml-book.github.io#501]
**Describe the mistake**
the operation defined as $\otimes$, but used $\times$ when saying $\mathcal{G}\otimes\mathcal{G}$

**Location**
Please provide the 
1. version: draft (2019-08-200
2. Chapter 2
3. page 36
4. line number: 4

**Proposed solution**
Use $\otimes$

**Comment by mpd37** [comment]
\times is actually correct here:

We have an operation \otimes that takes in two elements g_1, g_2 in G. Therefore, writing \otimes: GxG -> G is correct, describing \otimes as a mapping, and \times describing the Cartesian product.
