### ISSUE TITLE
projection onto affine subpsace

### ISSUE THREAD

**Issue by dj-zhou** [mml-book/mml-book.github.io#503]
**Describe the mistake**
equation (3.73b) is not precise

**Location**
Please provide the 
1. version: 2019-08-20
2. Chapter: 3
3. page: 90
4. equation number: (3.73b)

**Proposed solution**
I suggest it to 
= \|\bold{x}-\bold{x}_0,\pi_U(\bold{x}-\bold{x}_0))\| = d(\bold{x}-\bold{x}_0,U)

**Additional context**
none

**Comment by mpd37** [comment]
Your suggestion is to add  d(x - x_0, U) at the end of 3.73b?

**Comment by dj-zhou** [comment]
Yes, that was my suggestion. Such that the left side (3.73a) and right side (3.73b) are in the same formation, and indicate the similar thing.

**Comment by mpd37** [comment]
Thanks. Good idea. I changed this yesterday in the pdf. Should be online now.
