### ISSUE TITLE
Figure 4.11, matrix approximation

### ISSUE THREAD

**Issue by dj-zhou** [mml-book/mml-book.github.io#505]
**Describe the mistake**
I tried to show the rank-1 matrix defined from (4.90) and showed the figure, I cannot get the same as in the figure 4.11, however, if I multiple the singular value $\sigma_i$ to the (4.90), I got the same figures. So, should figure 4.11 shows some outer products $\bold{A}_i$ multipled by the corresponding singular value $\sigma_i$?

**Location**
Please provide the 
1. version 2019-08-20
2. Chapter 4
3. page 130
4. Figure 4.11

**Comment by mpd37** [comment]
Thanks for finding this. You are correct: the images you get by scaling the outer product with the corresponding singular values. I'll update the text and the caption.

**Comment by dj-zhou** [comment]
I might be wrong.
Because I noticed later that you use 0 to 1 as to display the image. I used
0-255, there might need some scaling, but I am not sure if that is related
to the eigenvalues.

**Comment by mpd37** [comment]
I was looking at the wrong figure (4.12). Figure 4.11 was actually generated as described in the original text. I'll undo this change later.

Here's the code snippet that I used for plotting those figures (no scaling by singular values):
![image](https://user-images.githubusercontent.com/5500569/79267280-d3ade200-7e90-11ea-85c1-eba0c66fb3d9.png)

**Comment by dj-zhou** [comment]
Fortunately I didn't mess it up. 
Thanks.
