### ISSUE TITLE
Equation 11.34: Wrong reference to an identity used

### ISSUE THREAD

**Issue by jalagus** [mml-book/mml-book.github.io#507]
**Describe the mistake**
Wrong reference to an identity used.

**Location**
1. Draft (2020-04-04)
2. Chapter 11
3. Page 356
4. Equation 11.34

**Proposed solution**
The referenced identity should be 5.103 instead of 5.106

**Comment by mpd37** [comment]
Thanks for finding this. I'll fix this with the next update.
