### ISSUE TITLE
Inconsistency of Positive Definiteness

### ISSUE THREAD

**Issue by RobMcH** [mml-book/mml-book.github.io#508]
**Describe the mistake**
In definition 3.2/equation 3.8 positive definiteness is defined as

> Ω(x, x) > 0

and in the first condition of the remark on metrics (below 3.23) positive definiteness is defined as

> d is positive definite, i.e., d(x, y) ≥ 0.

**Location**
Please provide the 
1. Draft (2020-04-04)
2. 3
3. 73 & 76
4. 3.8 & below 3.23 (first condition of the remark on metrics) & 3.11

**Proposed solution**
Definition 3.4 states
> If only ≥ holds in (3.11), then A is called symmetric, positive definite.

Therefore, the first point of the remark should be "d is positive semidefinite [...]".

**Comment by mpd37** [comment]
This should be fine actually. On p. 76 it also says that d(x,y) = 0 if and only if x = y. 

On p. 73, the corresponding definition would be 
For all x in R^n: \Omega (x, x) >=0 and \Omega (x,x) = 0 if and only if x = 0

Definition 3.2 is equivalent to this statement. 

The only inconsistency I see is that things are defined in a slightly different (but equivalent way), but there's nothing wrong as far as I can see.

**Comment by RobMcH** [comment]
You are right, I somehow missed that. Apologies. (Imho it were clearer if both definitions were equal, but I guess that is personal perference. Thanks for having a look!)
