### ISSUE TITLE
Wrtiting (A^T)^{-1} without stating that A^T is invertible.

### ISSUE THREAD

**Issue by SyxtonPrime** [mml-book/mml-book.github.io#51]
**Describe the mistake**
While the line "If A is invertible (A^{-1})^T = (A^T)^{-1}" is certainly true, it would be useful to state somewhere that we know that (A^T)^{-1} exists. 

**Location**
1. version: 2018-05-28
2. Chapter: 2
3. page : 20
4. line number/equation number: 763

**Proposed solution**
Replace the line with: "If A is invertible then so is A^T and (A^{-1})^T = (A^T)^{-1}"

**Comment by mpd37** [comment]
![image](https://user-images.githubusercontent.com/5500569/41739871-553e25ae-758e-11e8-84fc-f67d8b230190.png)
