### ISSUE TITLE
Inconsistency in definition of isomorphism

### ISSUE THREAD

**Issue by zadbasheer** [mml-book/mml-book.github.io#510]
"Theorem 2.17 (Theorem 3.59 in Axler (2015)). Finite-dimensional vector spaces V and W are isomorphic if and only if dim(V ) = dim(W )" 
The above theorem talks about isomorphism without talking about a mapping between V and W. The book further says under section 2.7.1 that "Any n-dimensional vector space is isomorphic to Rn (Theorem 2.17)"
This is inconsistent with definition of isomorphism defined earlier in the book where the book defines isomorphism as a property of a mapping between V and W vector space, whereas the above two statements talks about isomorphism between two vector spaces without talking about any mapping.

**Comment by mpd37** [comment]
When we say "isomorphic", we mean "there exists an isomorphism", without the need to specify what the isomorphism is. I'm not sure whether this resolves the issue?

**Comment by zadbasheer** [comment]
Yeah. That resolves the issue. Thanks. Cheers.
