### ISSUE TITLE
Theorem 4.16 is False for Rotation Matrices

### ISSUE THREAD

**Issue by RobMcH** [mml-book/mml-book.github.io#511]
**Describe the mistake**
Theorem 4.16 states

>  The determinant of a matrix A ∈ Rn×n is the product of its eigenvalues [...]

This is not true for all matrices ∈ Rn×n. Consider a rotation matrix R ∈ Rn×n with eigenvalues λ ∈ C. Definition 4.6 doesn't consider complex eigenvalues. 

**Location**
Please provide the 
1. Draft (2020-04-04)
2. 4
3. 112
4. 4.42 & 4.25

**Proposed solution**
Only consider symmetric matrices in Theorem 4.16. There are no symmetric rotation matrices (besides the identity matrix). Therefore, change Theorem 4.16 to "The determinant of a symmetric matrix A ∈ Rn×n is the product of its eigenvalues [...]".

**Comment by mpd37** [comment]
I still think this is correct for complex eigenvalues as they appear in pairs (complex conjugate). The determinant of rotation matrices is 1. Can you give me a concrete example where this fails? 

I also found this helpful:
https://math.stackexchange.com/questions/507641/show-that-the-determinant-of-a-is-equal-to-the-product-of-its-eigenvalues

**Comment by RobMcH** [comment]
Sorry, I wasn't clear enough regarding what I think is faulty. The definition (equation 4.25) of eigenvalues given in the book doesn't allow for complex eigenvalues. If the definition does not account for complex eigenvalues, Theorem 4.16 must be changed to "The determinant of a symmetric matrix [...]", because currently it allows for complex eigenvalues to appear (which are not defined). Alternatively, the definition of eigenvalues (eq. 4.42) could be changed to allow for complex eigenvalues (I assumed you choose to only define real eigenvalues for a reason though, so that you'd prefer to keep it that way and change Theorem 4.16 instead).

**Comment by mpd37** [comment]
OK. I misunderstood this. Apologies. 

There are two solutions to the problem. Either rewrite the theorem for symmetric matrices or mention that the eigenvalues can be complex. 

We'll discuss this.

**Comment by mpd37** [comment]
I'll make it explicit that the eigenvalues can be complex. This also applies to Theorem 4.17.
