### ISSUE TITLE
Concatenated random variable states

### ISSUE THREAD

**Issue by dj-zhou** [mml-book/mml-book.github.io#513]
**Describe the mistake**
If $\boldsymbol{x}$ and $\boldsymbol{y}$ are two column vectors (with different dimension), then the concatenated states should be $[\boldsymbol{x}^\top, \boldsymbol{y}^\top]^\top$

**Location**
Please provide the 
1. version 2020-04-04
2. Chapter 6
3. page 199
4. line 3 above equation (6.64)

**Proposed solution**
as described in the mistake description

**Additional context**

**Comment by mpd37** [comment]
Thanks for finding this. Will be fixed in the next revision.
