### ISSUE TITLE
(Minor) Wrong Vector Referenced

### ISSUE THREAD

**Issue by RobMcH** [mml-book/mml-book.github.io#514]
**Describe the mistake**
On page 108-110 (Graphical Intuition in Two Dimensions) there are multiple transformation matrices given and their impact on a square grid of points. The text accompanying the last matrix (5) states:

> It stretches space along the (blue) eigenvector of λ2 by a factor 1.5 and compresses it along the orthogonal (blue) eigenvector by a factor 0.5

The picture shows one blue and one red vector, not two blue ones.

**Location**
Please provide the 
1.  (2020-04-04)
2. 4
3. 110
4. A5 = [...]

**Proposed solution**
The stretching eigenvector is red. Therefore, it should say "It stretches space along the (red) eigenvector [...]".

**Comment by mpd37** [comment]
Thanks a lot! I'll fix this with the next pdf update
