### ISSUE TITLE
Doubts about mu in 11.55 (EM algorithm)

### ISSUE THREAD

**Issue by vatai** [mml-book/mml-book.github.io#515]
**Is your feature request related to a problem? Please describe.**
I am not sure if the mu in eq 11.55 on pg 361 is the updated mu or the old mu. My hunch is that it is not important (i.e. it would converge in either way) but I guess it'd be nice to be clear on this.

**Describe the solution you'd like**
Add a note one the margin saying that the mu in eq 11.55 is the new (or the old) one.

**Describe alternatives you've considered**
If the mu is the old mu, then an alternate solution would be to switch the order of 11.54 and 11.55.

**Comment by mpd37** [comment]
Yes, they are the new ones - that's why we wrote it in that order. The idea of a note is very good. What about something like this:

<img width="448" alt="Screen Shot 2020-04-18 at 08 45 12" src="https://user-images.githubusercontent.com/5500569/79631400-156cb000-8151-11ea-9166-56aec6ed025b.png">

**Comment by mpd37** [comment]
"are" is probably better...
