### ISSUE TITLE
Equation symbol typo

### ISSUE THREAD

**Issue by dj-zhou** [mml-book/mml-book.github.io#516]
**Describe the mistake**
The symbol "d" in equation (6.68) should be a text d, not an italic d.

**Location**
Please provide the 
1. version 2020-04-16
2. Chapter 6
3. page 199
4. equation number (6.68)

**Proposed solution**
The integral:
\int p(\boldsymbol{x},\boldsymbol{y}) \text{d} \boldsymbol{y}

**Comment by mpd37** [comment]
Good catch!. I'll update this with the next pdf version.
