### ISSUE TITLE
Lost bracket in equations 

### ISSUE THREAD

**Issue by dj-zhou** [mml-book/mml-book.github.io#517]
**Describe the mistake**
In equation (6.83b) and (6.84b), the bracket for the integrand are lost.

**Location**
Please provide the 
1. version 2020-04-16
2. Chapter 6
3. page 202
4. line number/equation number equation (6.83b) and (6.84b)

**Proposed solution**
add bracket for the integrand.

**Comment by mpd37** [comment]
Agree: brackets clearly contribute to readability. Will be fixed with the next update.
