### ISSUE TITLE
Typesetting error for margin text

### ISSUE THREAD

**Issue by nschmeller** [mml-book/mml-book.github.io#518]
**Describe the mistake**
On page 319 (of the current PDF version), there is margin text on both sides of the body text. Since the body text is oriented on each side, the margin text on the left side is cut off by the end of the page. 

**Location**
Please provide the 
1. Draft 2020-04-16
2. 10.1
3. 319
4. middle of page left margin

**Proposed solution**
Move the cut-off margin text to the right side (where there is another correctly formatted text)

**Comment by mpd37** [comment]
Will be fixed
