### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by axelstram** [mml-book/mml-book.github.io#519]
Describe the mistake
On page 35 of the current PDF version, there is a small typo: it says "the Gauß-Seidel method", when it should say "the Gauss-Seidel method"

Location
Please provide the
    version 2020-04-16
    Chapter 2
    page 35
    middle of page, a couple of lines before ec. 2.60

Proposed solution
Replace "the Gauß-Seidel method" with "the Gauss-Seidel method".

**Comment by mpd37** [comment]
Gauß is a German name, and we chose to spell it as it is spelled in German.
https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss
