### ISSUE TITLE
Wording suggests you're giving examples of groups as opposed to simply operations.

### ISSUE THREAD

**Issue by SyxtonPrime** [mml-book/mml-book.github.io#52]
**Describe the mistake**

The wording in lines 920, 921 directly after the definition of a groups seems to suggests that R, N, Z are groups with \otimes = +, \cdot and P(B) is a group under \cap, \cup, \. 

Of those pairs, only (R, +) and (Z, +) actually form groups.

**Location**
Please provide the 
1. version (bottom of page): 2018-05-28
2. Chapter: 2
3. page: 31
4. line number/equation number: 920 - 921

**Proposed solution**

Just delete these lines. You give examples of these things directly below anyway.

**Comment by mpd37** [comment]
done
