### ISSUE TITLE
Mising superscript 3 in Exercise 2.20 part c.

### ISSUE THREAD

**Issue by vatai** [mml-book/mml-book.github.io#520]
**Describe the mistake**
It says "vectors of R^3 defined in the standard basis of R", it should be "standard basis of R^3".

**Location**
1. version: (2020-04-21)
2. Chapter **2**
3. page **69**
4. line number: **Exercise 2.20 part c**, line 4, just above c_1= [..] c_2 = [..] c_3 = [..]

**Proposed solution**
Add missing ^3 superscript.

**Comment by mpd37** [comment]
Thanks! I'll fix this.
