### ISSUE TITLE
Minor typo and omission

### ISSUE THREAD

**Issue by Pealie** [mml-book/mml-book.github.io#522]
I've bought the book and really enjoy reading it. I’m noting a minor typo and also a minor omission.
Kind Regards
Neil Thomson

**Location**
Please provide the 
1. version - paperback
2. Chapter 12
3. page 356.
4. line number 35

**Proposed solution**
In the book is the following sentence -
'From the training perspective, there are many related probabilistic approches.'  
It should be spelled - '...probabilistic approaches.'

Also -
**Location**
Please provide the 
1. version - paperback
2. Chapter 4
3. page 101.
4. line number 9, (4.63b)

**Proposed solution**
In the book, there is an equation labelled (4.63b) that has capital pi (Π) in it.  Capital pi should be listed in the List of Symbols page on page ix, with the typical meaning defined.

Kind Regards
Neil Thomson

**Comment by mpd37** [comment]
I'll add the two lines to the list of symbols in the beginning.

Regarding the issue in chapter 12, can you give me page number etc. in the electronic version? I don't have a printed version around at the moment.

**Comment by Pealie** [comment]
Hi Marc

Thank you for replying. In the paperback, it’s the last page of the main content, and in the PDF, it’s page 399 (second last page).

“The SVM is a binary classifier that does not naturally lend itself to a probabilistic interpretation. There are several approaches for converting the raw output of the linear function (the score) into a calibrated class probability estimate (P(Y = 1|X = x)) that involve an additional cal- ibration step (Platt, 2000; Zadrozny and Elkan, 2001; Lin et al., 2007). From the training perspective, there are many related probabilistic ap- proches. We mentioned at the end of Section 12.2.5 that there is a re-“

Kind Regards
Neil

**Comment by mpd37** [comment]
Thanks, got it! I'll fix this with the next update.
