### ISSUE TITLE
Example 2.1

### ISSUE THREAD

**Issue by unspam** [mml-book/mml-book.github.io#523]
**Describe the mistake**
Not really a mistake as such, but it occurs to me that the unique solution (if it exists) satisfying the system of linear equations (2.3) might contain negative values which wouldn't make sense as a production quantity.

**Location**
1. version 2020-04-25
2. Chapter 2
3. Page 20

**Proposed solution**
A footnote, perhaps, that an applicable solution would have to satisfy non-negativity constraints too?

**Comment by mpd37** [comment]
Technically, this is correct. We didn't want to go into practical details here and talk about constraint settings.
