### ISSUE TITLE
Definition of derivative of vector with respect to scalar comes unexpected.

### ISSUE THREAD

**Issue by JeanLuc001** [mml-book/mml-book.github.io#524]
****Describe** the mistake**
In 5.2.2 the chain rule df/dt implies the derivative of vector with respect to a scalar:
df/dt = df/d**x** d**x**/dt
However, such a derivative  - has d**x**/dt - has not been defined and so comes a bit unexpected.

**Location**
Please provide the 
1. 2020-04-25
2. 5.2.2
3. 148
4. eqn. (5.49)

**Comment by mpd37** [comment]
I'm not sure I understand the issue completely. The chain rule has been defined for vectors (5.48), and a scalar is a special case. What am I missing? It would be great if you could explain a bit more.

**Comment by JeanLuc001** [comment]
I was thinking about stating that the derivative of a vector with respect to a scalar, like d**x**/dt, is defined to be the element-wise derivative of the vector components. Just to have a proper definition. When making the transition from  dx/dt to d**x**/dt, some people might come up with weird definitions of d**x**/dt in their mind incorporating limits of the norms of the difference quotient or something like that, when reading about this topic for the first time, because to them the object d**x**/dt need still to be a scalar, based on their previous knowlegde of what a derivative is.

**Comment by mpd37** [comment]
When we do a more than cosmetic rewriting, I'll change the structure of this chapter and introduce the derivatives in exactly that way. Unfortunately, I can't make changes other than anything related to typos. 
I'll close this issue, but it will be addressed in the future.
