### ISSUE TITLE
Bold f

### ISSUE THREAD

**Issue by JeanLuc001** [mml-book/mml-book.github.io#525]
**Describe the mistake**
"In (5.55), every partial derivative df/dxi is a column vector".
The f in df/dxi should be bold.

**Location**
Please provide the 
1. 2020-04-25
2. 5.3
3. 150
4. 2nd sentence after eqn. (5.55)

**Comment by mpd37** [comment]
Good point. I changed this in the following way, which (I hope) make things clearer:

![image](https://user-images.githubusercontent.com/5500569/80908692-dc6c3800-8d19-11ea-86cb-29506d04c65f.png)
