### ISSUE TITLE
A normed vector space is more general than an inner product space.

### ISSUE THREAD

**Issue by SyxtonPrime** [mml-book/mml-book.github.io#53]
**Describe the mistake**
In the second bullet point for Def 3.3 you state: 

"the pair (V, <>) is called an inner product space, normed vector space or (real) vector space with inner product."

This is not the definition of a normed vector space. As you mention later, not all norms come from inner products and equivalently, not all normed vector spaces admit an inner product.
 
**Location**
Please provide the 
1. version: 2018-02-01
2. Chapter 3
3. page 67
4. line number/equation number - Unknown

**Proposed solution**
Remove the words normed vector space.

**Comment by SyxtonPrime** [comment]
Also, in the remark almost directly after this definition you refer to the induced norm. You should provide a link to equation 3.15 here, (Or move that equation earlier) because you are currently referencing the induced norm a page before you define it.

**Comment by mpd37** [comment]
Addressed the issue by:

1. removing the words "normed vector space" from the definition
2. moving the remark on CS-inequality to the section on norms
3. added a general remark on the relation between norms and inner products:
" Every inner product induces a norm, but there are norms (like the
  l1 norm) without a corresponding inner product."
![image](https://user-images.githubusercontent.com/5500569/41739432-f0ac5116-758c-11e8-8976-557b136a898b.png)
