### ISSUE TITLE
Additional Exercises Chapter 2 Exercise 1a

### ISSUE THREAD

**Issue by Ivo90** [mml-book/mml-book.github.io#530]
**Describe the mistake**
In the first step of the solution, row 1 is added to row 3. Row 1 is [1 2 1], while row 3 is [-1 2 1]. This should result in [0 4 2] and not [0 4 -2] as proposed by the solution.

In the second step of the solution, 1/3th of row 2 is added to row 1. This should result in [1 0 0] instead of [1 0 1/2]

**Location**
Please provide the 
1. version (bottom of page): Last update: 2020-05-01
2. Chapter: 2
3. page: 1
4. line number/equation number: Exercise 1a

**Proposed solution**
A clear and concise description of what you would like to change.

Just a correct solution.

**Additional context**

**Comment by mpd37** [comment]
Thanks. I fixed this.
