### ISSUE TITLE
Inconsistent notations, page 276 to page 277

### ISSUE THREAD

**Issue by lostspirit0** [mml-book/mml-book.github.io#551]
**Describe the mistake**
A clear and concise description of what the mistake is.
While 8.24 and 8.25 write $p(x\vert \theta ,z)$, the first line after equation 8.25, the third to last line of page 276, equation 8.27 and equation 8.28 and the first line after equation 8.28 write $p(x\vert z ,\theta)$ instead.

**Location**
Please provide the 
1. version (bottom of page): Draft (2020-05-24) of “Mathematics for Machine Learning”. Feedback: https://mml-book.com.
2. Chapter: 8
3. page: 276 - 277
4. line number/equation number: equation 8.24, equation 8.25, the first line after equation 8.25, the third to last line of page 276, equation 8.27, equation 8.28, the first line after equation 8.28

**Proposed solution**
A clear and concise description of what you would like to change.
Unify the notation. Change all the notations to either $p(x\vert \theta ,z)$ or $p(x\vert z ,\theta)$.

**Additional context**

**Comment by mpd37** [comment]
Good point. I went for p( x | z, \theta). I hope I caught all of the other ones.
