### ISSUE TITLE
typo? in page 59. (Draft March 17, 2019)

### ISSUE THREAD

**Issue by bigdataman2015** [mml-book/mml-book.github.io#552]
**Describe the mistake**
change R^n with R^m ? cause A belongs to R^(mxn), A = [a1, a2, ,,, an], ai  belongs to R^(m), i = 1, 2, ,,, n.

**Location**
Draft March 17, 2019, in page 59. Details:
The kernel/null space ... ... captures all possible linear combinations of elements in R^n (change R^n with R^m ? )... ...

**Comment by mpd37** [comment]
R^n is correct. If you multiply a vector x in R^n onto an mxn matrix you'll get a vector in R^m. We are looking for all vectors in R^n that produce 0 in R^m
