### ISSUE TITLE
slightly confusing phrasing

### ISSUE THREAD

**Issue by rumata3** [mml-book/mml-book.github.io#556]
**Describe the mistake**
"a symmetric matrix possesses an ONB of eigenvectors" -- slightly confusing in that it's the vector space, not the matrix, that actually "possesses a basis", while the matrix possesses the eigenvectors.

**Location**
Please provide the 
1. version (bottom of page)
Draft (2020-05-24)
2. Chapter
4.5
3. page
123
4. line number/equation number

**Proposed solution**
"a symmetric matrix possesses a list of eigenvectors that form an ONB"?

**Comment by mpd37** [comment]
Good point. I change this to the following:

... the eigenvectors of a symmetric matrix form an ONB ...
