### ISSUE TITLE
Publishing the book in an e-reader compatible format

### ISSUE THREAD

**Issue by P0oOOOo0YA** [mml-book/mml-book.github.io#558]
first of all, I have to thank you for providing this book for free. Are there any plans to publish the book in an e-reader friendly format like epub?

**Comment by mpd37** [comment]
You can get it for kindle from amazon

**Comment by P0oOOOo0YA** [comment]
Indeed but amazon charges you 30$ for the same eBook freely downloadable here, maybe only PDF is supposed to be free:(

**Comment by mpd37** [comment]
Yes, unfortunately, we are only allowed to do PDF.
