### ISSUE TITLE
Non-standard or incorrect notation for row vectors

### ISSUE THREAD

**Issue by rajpanse** [mml-book/mml-book.github.io#560]
**Describe the mistake**
A row vector is denoted as [x1, ..., xn]. This notation is cited in the (external) literature as not standard.

As an endorsement of why this notation is not standard, refer exercise 1.1(b) on page 25 from this book from Professor Stephen Boyd of Stanford University: https://web.stanford.edu/~boyd/vmls/vmls.pdf. Boyd has remarked this notation as non-standard in the ninth line on page 2 of https://see.stanford.edu/materials/lsoeldsee263/Additional3-basic-notation.pdf.

**Location**
1. Version: Draft (2020-06-06)
2. Chapter: 2
3. Page: 39
4. Third bullet from Example 2.12

**Proposed solution**
Use either [x1 ... xn] or (x1, ..., xn).

**Additional context**
This non-standard notation has repeated at other places too. E.g., in the text enclosed between Eqn 9.66 and 9.67 on page 313, in Eqn 10.46 on page 333, in the text following Eqn 10.53 on page 335, in the text before and after Eqn 5.54 on page 149, in the text after Eqn 5.40 on page 146, in the second line after the title of section 6.6.2 on page 210, in the sixth line of example 8.1 on page 259, in the second and the third lines above Eqn 8.6 on page 260, in the first line after Eqn 9.10b on page 194, and many more places.

**Comment by mpd37** [comment]
We decided to use [x_1, x_2, ..., x_N] or [x_1 x_2 ... x_N] to denote row vectors. We use both notations in the book. We use (x_1, ..., x_N) for tuples more generally (e.g., ordered bases).
