### ISSUE TITLE
General solution in 2.47

### ISSUE THREAD

**Issue by joannordille** [mml-book/mml-book.github.io#561]
**Describe the mistake**
Given the previous discussion, I expected the matrix scaled by lambda-1 to have a -1 in it.

**Location**
Please provide the 
1. Printed book, first edition
2. Chapter 2
3. page 20
4. line number/equation number 2.47

**Proposed solution**
Confirm correctness and explain, or correct matrix.

**Additional context**
The book is generally a great read that you can follow.  This is the first place for me where there was a magic equation.

**Comment by mpd37** [comment]
If you determine the reduced row echelon form of that matrix, you'll get [-2, -1, 0, 0, 0] for the corresponding vector (scaled by \lambda_1). So, the solution in the book is correct. 
Does this make sense?
