### ISSUE TITLE
Incorrect reference to empirical risk minimization

### ISSUE THREAD

**Issue by amsaha** [mml-book/mml-book.github.io#563]
**Describe the mistake**
At the bottom of Section  8.3.1, Section 8.2.3 should probably be referenced instead of Section 9.2.3.

**Location**
Please provide the 
1. version Draft (2020-04-16)
2. Chapter 8
3. page 268
4. line number/equation number End of Section 8.3.1

**Proposed solution**
Section 8.2.3 should probably be referenced instead of Section 9.2.3 at the bottom of Section 8.3.1.

**Additional context**
Existing text at the end of Section 8.3.1:
*Maximum likelihood estimation may suffer from overfitting (Section 8.3.3), analogous to unregularized empirical risk
minimization (Section 9.2.3).* 

Section 9.2.3 should probably be Section 8.2.3. Section 9.2.3 is titled "Maximum A Posteriori Estimation" whereas Section 8.2.3 is titled "Regularization to Reduce Overfitting"

**Comment by mpd37** [comment]
Good catch! Will be fixed with the next update of the PDF.

**Comment by mpd37** [comment]
same problem on p. 382
