### ISSUE TITLE
Fig 9.5 has example for M=6 but text refers to M=3,...,5

### ISSUE THREAD

**Issue by amsaha** [mml-book/mml-book.github.io#564]
**Describe the mistake**
Figure 9.5(e) is labelled as *M = 6* whereas following text talks about *M=3,...,5*, i.e., there is no M=5 in the figure but the text refers to that. 

**Location**
Please provide the 
1. version Draft (2020-04-16)
2. Chapter 9
3. page 299
4. line number/equation number Fig 9.5

**Proposed solution**
The text refers to *For degrees M = 3;,,,; 5, the fits look plausible and smoothly interpolate the data.* Either Figure 9.5(e) should be showing graph for M=5 or the text needs to be changed. I think Fig 9.5(e) is labelled incorrectly.

**Additional context**
Fig 9.5 is titled "Maximum likelihood fits for different polynomial degrees M."

**Comment by mpd37** [comment]
Figure captions are correct, but text does not match. I'll change the text to 3, ..., 6
