### ISSUE TITLE
Typo on page 319, last paragraph

### ISSUE THREAD

**Issue by andreaswachowski** [mml-book/mml-book.github.io#565]
**Describe the mistake**

I stumbled while reading
> Based the motivation of thinking of PCA as a data compression technique, ..."

Is there a word missing?

**Location**

1. Draft (2020-07-01)
2. Chapter 10
3. 319
4. 8th line from the bottom

**Proposed solution**

I'd suggest replacing "Based the motivation ..." with "Based on the motivation ..." (disclaimer: I am not a copy editor).

**Additional context**

N/A

**Comment by mpd37** [comment]
thanks!
