### ISSUE TITLE
A better notation for probability mass function (in Example 6.1 and following after it)

### ISSUE THREAD

**Issue by LugoBlogger** [mml-book/mml-book.github.io#567]
When I read Eq. 6.8. I stumbled over several guesses what does it mean when the argument of P is changed. Then I read back Example 6.1, suddenly I realized a better notation for the argument of probability mass function in that example (and maybe for the notation following after it).

Since X is a mapping, it would rather be good to use the notation P( X ( · ) in S) where S in T, e.g. P( X( · ) = 1) in Example 6.1, to make an emphasis that we equate the image of X instead the map X itself and provide a placeholder (·) to explicitly express the argument that satisfy the given condition. In my opinion this notation not so concise, but intuitively easy to understand and consistent notation to the meaning of X.

**Comment by chengsoonong** [comment]
Your suggestion is a good one, that is to explicitly show that the random variable X is a mapping. However, most of the machine learning literature does not explicitly show that, and hence we may confuse a reader who has read other material already. One reason for the choice of not showing X(.) is to align the common notation.

Another reason is that the extra brackets start getting quite heavy when we have multiple random variables, and when we start looking at things like conditional probabilities.
