### ISSUE TITLE
Margins are not consistent between odd and even pages

### ISSUE THREAD

**Issue by netw0rkf10w** [mml-book/mml-book.github.io#569]
**Describe the mistake**
In the current version, the margins are not consistent between the odd and the even pages. 

**Proposed solution**
Making the margins consistent, i.e. the **left** margin on the **odd** pages should be the same as the **right** margin on the **even** pages, and vice-versa.

**Additional context**
Nothing to say, just thanks for making the book freely available.

**Comment by mpd37** [comment]
can you point me to a page where that's the case?

**Comment by netw0rkf10w** [comment]
@mpd37 All the pages have this issue. Please see the attached figure.

![mml_margins](https://user-images.githubusercontent.com/8569515/88483982-9830b280-cf6b-11ea-96c6-4354e2e247b7.jpg)

**Comment by chengsoonong** [comment]
This is by design. We have broader margins on the outer edges of the book, to provide space for margin notes.

**Comment by netw0rkf10w** [comment]
@chengsoonong You don't get it. I'm surprised because it's clear from the figure. Never mind then.

**Comment by chengsoonong** [comment]
Revisiting this. The book paper size is not A4, and the PDF does not indicate where the pages get cut. In the printed book (double sided of course), the two lengths you mentioned are equal. You are right, I misunderstood your figure in my previous comment.

**Comment by netw0rkf10w** [comment]
@chengsoonong Thanks for getting back.
The two pages are printed on the same sheet (each on one side), so the text on the two sides will not be aligned regardless of the (physical) page cut. I guess your publisher had to edit the PDF (e.g. cropping the pages) before printing it.
Anyway, this is just a very minor issue and shouldn't affect the reading experience of a regular user. The draft already looks great. Thanks a lot!
