### ISSUE TITLE
4.2.1 Graphical Intuition in Two Dimensions

### ISSUE THREAD

**Issue by Davide95** [mml-book/mml-book.github.io#571]
**Location**
Chapter 4, page 93 of the printed version (printed value)

**Describe the mistake**
During all the chapter, ![formula](https://render.githubusercontent.com/render/math?math=\lambda_i) is used to indicate eigenvalues. 
In the explanation of the matrix ![formula](https://render.githubusercontent.com/render/math?math=A_4), ![formula](https://render.githubusercontent.com/render/math?math=\lambda_2) is a scaling factor.

**Proposed solution**
I suggest to rephrase it in this way:
"![formula](https://render.githubusercontent.com/render/math?math=A_4%20=%20\dots) represents a mapping in the standard basis that collapses a two-dimensional domain onto one dimension. Since one eigenvalue is 0, the space in direction of the (blue) eigenvector corresponding to ![formula](https://render.githubusercontent.com/render/math?math=\lambda_1%20%20=%200) collapses, while the orthogonal (red) eigenvector stretches space by a factor of ![formula](https://render.githubusercontent.com/render/math?math=\color{red}{\lambda_2%20=}\color{black}{%202})"

NB: the red part should be deleted.

**Comment by mpd37** [comment]
can you please give me the corresponding page in the online version? i don't have the printed version at hand.

**Comment by Davide95** [comment]
> 
> 
> can you please give me the corresponding page in the online version? i don't have the printed version at hand.

Sure, it's page 110 on https://mml-book.github.io/book/mml-book.pdf

**Comment by mpd37** [comment]
The \lambda_i in that section are the eigenvalues of the corresponding matrices (and the scaling factors). Therefore, we would keep it that way.

**Comment by Davide95** [comment]
Understood. Thank you for your time
