### ISSUE TITLE
Chapter 7 pg. 235: Max of Affine Functions

### ISSUE THREAD

**Issue by andwgu** [mml-book/mml-book.github.io#573]
**Describe the mistake**
The book states "The reason is that the outer problem (maximization over λ) is a maximum over a set of affine functions, and hence is a concave function...". 

Affine functions are both convex and concave. The maximum of convex functions is a convex function, while the minimum of concave functions is a concave function. As such, I wonder if the book should say "hence is a convex function" instead of "hence is a concave function" when describing the maximization over λ. 

**Location**
1. version (bottom of page): 2020-07-03
2. Chapter: 7
3. page: 235
4. line number/equation number: the first full paragraph after equation 7.27

**Proposed solution**
Change "hence is a concave function" to "hence is a convex function".

**Additional context**
None.

**Comment by chengsoonong** [comment]
Thanks for raising this, the phrasing of the paragraph was not clear. Here is an updated version that shows that the dual lagrangian is a concave function. Does this clarify things?

![dual-lagrangian-concave](https://user-images.githubusercontent.com/709424/89236765-c893e300-d634-11ea-8d7e-0fd90d41db40.png)

**Comment by andwgu** [comment]
Yes, this clarifies things. I appreciate it!
