### ISSUE TITLE
Chapter 4, page 124,  subscript r

### ISSUE THREAD

**Issue by shengxue** [mml-book/mml-book.github.io#574]
**Describe the mistake**
where does the subscript ```r``` in page 124 come from? is it supposed to be subscript ```n```?

**Location**
Please provide the 
1. version:  2020-07-03
2. Chapter:  4
3. page: 124
4. all page

**Proposed solution**
A clear and concise description of what you would like to change.

**Additional context**

**Comment by mpd37** [comment]
It comes from here:
![image](https://user-images.githubusercontent.com/5500569/89120061-eaf9f500-d4aa-11ea-91fc-c04cc078865e.png)

**Comment by shengxue** [comment]
yes, thanks!
