### ISSUE TITLE
Potential Typo

### ISSUE THREAD

**Issue by mhfwx** [mml-book/mml-book.github.io#575]
**Describe the mistake**
A clear and concise description of what the mistake is.

In the remark, Distribution is used for continuous probability density functions. I think you may want to refer cumulative density functions since in last paragraph, "To muddy things even further, the cumulative distribution function P (X 6 x) is often also referred to as the “distribution”. 

**Location**
Please provide the 
1. version (bottom of page) 2020-07-01
2. Chapter 6.2.3
3. page 183
4. line number/equation number  in the remark part

**Proposed solution**
A clear and concise description of what you would like to change.
replace the continuous probability density functions with cumulative density functions. 
**Additional context**

**Comment by chengsoonong** [comment]
I don't think "cumulative density functions" is a correct phrase. In fact Wikipedia points out that "cumulative" and "density" contradict each other.
https://en.wikipedia.org/wiki/Cumulative_density_function
