### ISSUE TITLE
Possible errata for figure 4.6 caption

### ISSUE THREAD

**Issue by yangc22** [mml-book/mml-book.github.io#578]
**Describe the mistake**
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version (bottom of page): Draft(2020-03-28)
2. Chapter: 4
3. page:113
4. line number/equation number: Figure 4.6 caption

**Proposed solution**
A clear and concise description of what you would like to change.
In the current errata, it is said "p. 113, caption of Figure 4.6, last sentence: ... circumference changes by a factor \add{of} $2(|\lambda_1| + |\lambda_2|)$".
However, I think the original circumference is $2$ and the circumference should change by a factor of  $(|\lambda_1| + |\lambda_2|)$, which meets Theorem 4.17 the computation of the trace as the sum of the eigenvalues.

**Additional context**

**Comment by mpd37** [comment]
The original perimeter is 4, the change should be a factor of ( |\lambda_1| + |\lambda_2| )/ 2
The perimeter is 2*(|\lambda_1| + |\lambda_2|). 

Does this make sense?

**Comment by yangc22** [comment]
Thanks for the explanation!
