### ISSUE TITLE
Circumference of unit square, page 113, Section 4.2

### ISSUE THREAD

**Issue by fbrundu** [mml-book/mml-book.github.io#579]
**Describe the mistake**
It is probably not a mistake but isn't the circumference used to define the perimeter of circles (for example), while the more general term perimeter is used for rectangles? I tried to see if the [circumference](https://en.wikipedia.org/wiki/Circumference) is used in a more general way to define perimeter but I couldn't find a good definition.

**Location**
Please provide the 
1. 2020-07-03
2. 4
3. 113
4. Second paragraph after equation 4.43

**Proposed solution**
Should the right term here be "perimeter"?

**Additional context**

**Comment by mpd37** [comment]
Agree. I'll fix this soon.
