### ISSUE TITLE
Error/typo, page 216, Equation 6.132

### ISSUE THREAD

**Issue by Kirill-Kravtsov** [mml-book/mml-book.github.io#580]
**Describe the mistake**
Probability integral transform theorem: there should be not x (not the value from the target space) but X (actual random variable) as an argument of the cdf function in the Equation 6.132. Currently Y is defined just as cdf of X. 

**Location**
Please provide the 
1. 2020-07-03
2. 6
3. 216
4. Equation 6.132

**Proposed solution**
Replacing argument of the cdf: x (value from the target space) by X (random variable).

**Additional context**

**Comment by chengsoonong** [comment]
Thank you. Also fixed Exercise 6.13.
