### ISSUE TITLE
Possible errata on Page 125

### ISSUE THREAD

**Issue by yangc22** [mml-book/mml-book.github.io#582]
**Describe the mistake**
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version (bottom of page) Draft (2020-03-28).
2. Chapter 4.5.
3. page 125.
4. line number/equation number The second paragraph starting from line 3.

**Proposed solution**
A clear and concise description of what you would like to change.

To my understanding, the mathematical signs are wrong maybe?
The original graph is 
`
For n > m, (4.79) holds only for i <= m and (4.79) says nothing about the u_{i} for i > m. However, we know by construction that they are orthonormal. Conversely, for m > n, (4.79) holds only for i <= n. For i > n, we have Av_{i} = 0 and we still know that the v_{i} form an orthonormal set. This means that the SVD also supplies an orthonormal basis of the kernel (null space) of A, the set of vectors x with Ax = 0 (see Section 2.7.3).
`
I think u_{i} is in R^{m} and v_{i} is in R^{n}, so maybe the graph should be 
`
For n < m, (4.79) holds only for i <= n and (4.79) says nothing about the u_{i} for i > n. However, we know by construction that they are orthonormal. Conversely, for m < n, (4.79) holds only for i <= m. For i > m, we have Av_{i} = 0 and we still know that the v_{i} form an orthonormal set. This means that the SVD also supplies an orthonormal basis of the kernel (null space) of A, the set of vectors x with Ax = 0 (see Section 2.7.3).
`
Not sure whether my understanding is right. Thanks!

**Additional context**

**Comment by mpd37** [comment]
Thanks for catching this. What you are saying here is correct. I'll fix this in the next update.

**Comment by yangc22** [comment]
Glad it is correct. Thanks for your response! @mpd37
