### ISSUE TITLE
More detailed description of final part of section 4.5.2

### ISSUE THREAD

**Issue by fbrundu** [mml-book/mml-book.github.io#583]
I don't know if others had the same problem, but probably a more detailed description of the last part of section 4.5.2 may be useful. For example, it is written (just before equation 4.77):

> To reach this goal, we use the fact the images of the v_i under A have to be orthogonal, too.

I'm not sure what I'm missing here but aren't the right singular vectors computed by the SPD matrix A^T A, therefore they should be ONB for the SPD matrix. How can we use this result to show that their images under the A matrix are orthogonal?

Thanks

**Comment by mpd37** [comment]
Assume matrix A has eigenvectors x_i, x_j (x_i and x_j are orthonormal). 
Then it holds that Ax_i is orthogonal to Ax_j because
(Ax_i)^T * (Ax_j) = \lambda_i\lambda_j * x_i^T * x_j = 0 (because x_i, x_j are ONB).

**Comment by fbrundu** [comment]
It makes sense, thanks.
