### ISSUE TITLE
Typo on page 1 (Foreword)

### ISSUE THREAD

**Issue by nthrDvlpr** [mml-book/mml-book.github.io#588]
**Describe the mistake**
A clear and concise description of what the mistake is.

**Location**
Please provide the 
1. version (bottom of page): 2020-08-16
2. Chapter: 1
3. page: 1

**Proposed solution**
Therefore, these books only spend one or two chapters **of** background mathematics

Change "of" to "on".

**Comment by mpd37** [comment]
thanks
