### ISSUE TITLE
Equation 4.77

### ISSUE THREAD

**Issue by roatienza** [mml-book/mml-book.github.io#589]
**Describe the mistake**
Since i != j, generally eigenvalues sigma_i != sigma_j. Eq 4.77 combined the 2 eigenvalues as lambda_j = sigma_i * sigma_j. 

**Location**
Please provide the 
1. version : 2020-8-16
2. Chapter: 4
3. page: 124
4. line number/equation number: 4.77

**Proposed solution**

Eq 4.77 should have been:  sigma_i * sigma_j * Transpose(v_i) *v_j = 0

**Additional context**
None.

**Comment by mpd37** [comment]
We used the fact that v_j is an eigenvector of A^T * A, so that (A^T*A)*v_j = \lambda_j v_j

Does this make more sense now?

**Comment by roatienza** [comment]
If we used the fact that v_j is an eigenvector of A^T * A, so that (A^T*A)*v_j = \lambda_j v_j, it implies that i=j in Equation 4.75. This goes against the given that i != j.
