### ISSUE TITLE
Typos on chapter 10

### ISSUE THREAD

**Issue by vincentadam87** [mml-book/mml-book.github.io#59]
I am here reporting typos on chapter 10 (based on a printed version on 25/06/2018)

Abstract : the set .... are 
L. 4444 : The labels [are] often referred to as
L. 4561 : .. by making [the] observation that
L. 4583 : .. we argues that (no s)
L. 4610 : alternative parameterizations of [this] regularization
L. 4613 : w is regularized by b is not regularized (???)
L. 4748 : ... a the practitioner will

**Comment by chengsoonong** [comment]
Thanks for your careful reading.
