### ISSUE TITLE
Errata for printed book

### ISSUE THREAD

**Issue by elbersb** [mml-book/mml-book.github.io#593]
Hi,
I bought a physical copy of the book, and wanted to go through the errata. It seems that there are only errata for the online version of the book, which is a bit unfortunate. Right now, I would have to find the page of the online book, find the change, and then browse around in the physical book to see where the change applies. Given that the errata are mostly relevant for people who have the physical copy, are you planning to release a corresponding version of the errata?

Ben

**Comment by mpd37** [comment]
Hi Ben,

We are not planning to write errata for the printed version as page numbers will change with every new print, and we don't have an efficient way to keep track of this. We are really sorry, but you probably need to do the matching manually. 

Marc

**Comment by elbersb** [comment]
Hi,
thanks for your reply.

Obviously, it's your choice - but that seems to defeat the purpose of having errata around at all (for the updated PDF, by definition, the errata are no longer required).  And, honestly, it makes me regret getting a physical copy at all, instead of printing out the PDF. Here's how others solve the problem of having multiple printings: http://www.stat.columbia.edu/~gelman/book/errata_bda3.txt Clearly, more work, but arguably also more useful.

Ben
