### ISSUE TITLE
Angles and Orthogonality - Example 3.7 Calculation

### ISSUE THREAD

**Issue by kanm05** [mml-book/mml-book.github.io#598]
In Example 3.7 (Orthogonal Vectors), there seems to be a mistake in the calculation while calculating the cosine of the angle between the vectors when the latter definition of the inner product is taken.

Example 3.7, Page 77-78
1. Version - Draft (2020-09-12) of “Mathematics for Machine Learning”
2. Chapter 3 - Analytic Geometry
3. Page 77-78
4. Equation number - 3.28

Correct Calculation:
cos w = <x, y>/||x|| ||y|| = -1/2  => w =~ 2.09 rad =~ 120 degrees

**Comment by mpd37** [comment]
The calculation is correct because ||x|| = x^T * A * x and ||y|| = y^T * A * y. Please double check.

**Comment by kanm05** [comment]
Yes right. Closing this issue.

**Comment by kanm05** [comment]
Yes right. Closing this issue.
