### ISSUE TITLE
Wrong spelling for GitHub

### ISSUE THREAD

**Issue by fxn** [mml-book/mml-book.github.io#599]
**Describe the mistake**
The name "github" is spelled incorrectly.

**Location**
 
1. Draft (2020-09-12)
2. Foreword
3. Page 5
4. There are two occurrences

**Proposed solution**
Replace "github" with "GitHub".

**Comment by mpd37** [comment]
Thanks. I'll fix that.

**Comment by fxn** [comment]
Hey! I just downloaded the new PDF and in

> Contributors through GitHub, whose real names were not listed on their github profile, are

on page 5, there's a remaining mispelling: _not listed on their **github** profile_.

**Comment by mpd37** [comment]
I thought I got all of them.... It's fixed now. Thanks for checking
