### ISSUE TITLE
Solutions to the chapter-wise theoretical math exercises

### ISSUE THREAD

**Issue by glennDittmann** [mml-book/mml-book.github.io#601]
**Is your feature request related to a problem? Please describe.**
I (and probably others too) would like to assess the correctness of the calculations, proofs, ... I / we made for the nice exercises that finish up the chapters.

**Describe the solution you'd like**
Well, since this document already exists, but Cambridge University Press grants access only to those who are lecturers, I would suggest to make the solution publicly available.

**Describe alternatives you've considered**
Maybe granting access to people that can assure they actually did the exercises. But that would probably be rather tricky and involve too much overhead.

**Additional context**
I can understand that this does give the possibility to "cheat" for getting the solution, but then for people doing this, the reason of the exercises is lost anyways.

**Comment by mpd37** [comment]
We are not allowed to make solutions publicly available. However, we started on an additional set of exercises for which we have solutions available:

https://www.overleaf.com/read/jvnwngmkpckc

**Comment by glennDittmann** [comment]
Thanks for clarifying and for making extra exercises with solutions available.
Much appreciated.
