### ISSUE TITLE
GitHub link is broken

### ISSUE THREAD

**Issue by stephsamson** [mml-book/mml-book.github.io#602]
**Describe the mistake**
The GitHub link in the foreword redirects to `https://mml-book.github.io/book/github.com` because a URL without the protocol is provided (i.e., `https://` is not prefixed).

**Location**
Please provide the 
1. Draft (2020-09-12)
2. Foreword
3. 4
4. Line no. 9

**Proposed solution**
github.com -> https://github.com/mml-book/mml-book.github.io

**Additional context**

**Comment by mpd37** [comment]
will fix. thanks
