### ISSUE TITLE
Extend more dense sections in Chapter 6 such as 6.5.1

### ISSUE THREAD

**Issue by fbrundu** [mml-book/mml-book.github.io#603]
**Is your feature request related to a problem? Please describe.**
The first 5 chapters are very clear to follow and to study step by step. In my view, Chapter 6 might need to be extended to provide a similar experience. I think the authors acknowledged that in the Chapter 6's Further Reading section "This chapter is rather terse at times." However, using different textbooks is not always smooth since different authors can write for different audiences and consider different pre-requisites. Therefore juggling between different textbooks is surely a useful journey, but might be recommended for more experienced audiences, which if I understand correctly are not the target of this book:

> We wrote a book on Mathematics for Machine Learning that motivates people to learn mathematical concepts. The book is not intended to cover advanced machine learning techniques because there are already plenty of books doing this. Instead, we aim to provide the necessary mathematical skills to read those other books.

**Describe the solution you'd like**
I think this book is fundamental for the community, and I'd really like to see more of it. Some parts, in my opinion, might benefit for additional extension and explanation with this book's notation (for example in Section 6.5.1 with the derivation of the conditional distribution of Gaussian).

**Describe alternatives you've considered**
I read some parts of the linked references (e.g. Bishop's Section 2.3 - referenced in Section 6.5.1) but I am not sure they provide the same level of clarity that this book has for its target audience.

**Comment by fbrundu** [comment]
Hi all!

Are there updates on this issue? I have been going through several books to fill the gap needed (in particular for the attached section), but I haven't found one with the same level of clarity of this book.

In particular, the referenced Bishop's book does probably require more previous knowledge to fully understand the derivation. In case you have recommendations on how to prepare (pre-requisites or recommended companion books) to approach this section, please let us know.

Thanks

<img width="1026" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/697622/116901746-4c045400-ac08-11eb-8fa7-a98591ceda2f.png">

**Comment by chengsoonong** [comment]
Thanks for your kind words about the clarity of our book.

We had to make some hard decisions about what to leave out of the book, and the derivation of a conditional distribution of a Gaussian was one of them. The following stackoverflow discussion provides several ways to derive it.
https://stats.stackexchange.com/questions/30588/deriving-the-conditional-distributions-of-a-multivariate-normal-distribution

**Comment by fbrundu** [comment]
I understand, thank you. I will follow the linked discussion.
