### ISSUE TITLE
SVD: singular values and eigenvalues

### ISSUE THREAD

**Issue by nfzd** [mml-book/mml-book.github.io#609]
**Describe the mistake**
p. 127 states: "The nonzero singular values of A are the square roots of the nonzero eigenvalues  of A A^T and  are  equal  to  the  nonzero  eigenvalues  of A^T A."

But: above it says that the singular values are the square roots of both the eigenvalues of A^T A  (p.123 Eq. 4.75) and of the eigenvalues of A A^T (p. 124 below Eq. 4.78).

**Location**
1. version 2020-09-12
2. Chapter 4
3. page 127
4. last second-level bullet point

**Proposed solution**
Rewrite the bullet point in the summary on p. 127: "The nonzero singular values of A are the square roots of the nonzero eigenvalues of both A A^T and  A^T A." (or a better formulation)

**Notes**
Confirmed via [Wikipedia](https://en.wikipedia.org/wiki/Singular_value_decomposition#Relation_to_eigenvalue_decomposition).

**Comment by mpd37** [comment]
Thanks. That's a good suggestion.
