### ISSUE TITLE
Small typo in introduction

### ISSUE THREAD

**Issue by gingertom** [mml-book/mml-book.github.io#61]
**Describe the mistake**
You mean to say that you can represent gender by a 1 and 0 to represent male and female. Instead you say "1 and 1".

**Location**
Please provide the 
1. version : "Draft (2018-07-10)"
2. Chapter: Introduction
3. page: 12
4. line number: 672 & 673

**Proposed solution**
Change "1 and 1" to "1 and 0". 

**Additional context**
I'm starting to read your book, do you want this level of feedback in terms of typo's and stuff or only more serious issues/suggestions?

**Comment by chengsoonong** [comment]
All feedback is welcome. 

If you find chapters with many typos it would be more convenient for us if you grouped them before submitting a single issue.

**Comment by chengsoonong** [comment]
<img width="608" alt="screen shot 2018-07-11 at 11 14 07 pm" src="https://user-images.githubusercontent.com/709424/42573656-1020b1d0-8560-11e8-8910-d8a61ec1728c.png">

I assume you mean this sentence. It is correct. The numbers are -1 and +1

"we encode sex as the numbers −1 and 1 for male and female, respectively"

**Comment by gingertom** [comment]
Hello. 
 Ah, that makes much more sense. I guess as most previous examples I'd seen coded at 0 and 1 I was expecting that and didn't parse the sentence properly. I read that as:

`Long sentence with a description - hyphenated bit - rest of sentence.`
or
`Since we assume that our data is numerical, we encode sex as the numbers - 1 and 1 - for male and female, respectively`. 

Now I read it back with your explanation, I see I was wrong. Sorry for wasting your time, I'll pay more attention before reporting anything in the future. Many thanks for the quick reply and the great book. :)
