### ISSUE TITLE
Notation of Matrix Dimensions

### ISSUE THREAD

**Issue by JeanKaddour** [mml-book/mml-book.github.io#610]
For consistency, instead of $\mat{A}^{m \times n}$ it should be $\mat{A} \in \mathbb{R}^{m \times n}$.

**Location**
Please provide the 
1. 2020-09-12
2. 4.5
3. 119
4. Theorem 4.22

![image](https://user-images.githubusercontent.com/11850255/104365642-272c8980-5510-11eb-9543-b7aade5f5374.png)

**Comment by mpd37** [comment]
Thanks. Good catch.
