### ISSUE TITLE
Words Swapped For Matrices

### ISSUE THREAD

**Issue by PranavS-1999** [mml-book/mml-book.github.io#611]
**Describe the mistake**
The words invertible and noninvertible have been swapped.

**Location**
 
1. Draft (2021-01-14) of “Mathematics for Machine Learning”
2. Chapter 2
3. Page 24
4. Line 2 below Definition 2.2

**Proposed solution**
The word invertible should be used for singular matrices and noninvertible for nonsingular matrices.

**Comment by mpd37** [comment]
A singular matrix is a non-invertible matrix. 

https://en.wikipedia.org/wiki/Invertible_matrix
