### ISSUE TITLE
distinction between column and row vector

### ISSUE THREAD

**Issue by skabaw** [mml-book/mml-book.github.io#614]
I would suggest that the clarification of the distinction between the row and the column vector goes before the definition of outer and dot products. Before, it is unclear that a standard vector is a column vector.

**Location**
1. Draft (2021-01-14) of “Mathematics for Machine Learning”. Feedback: https://mml-book.com
2. chapter 2.4
3. page 38
4. line number/equation number: 3, 2.64

**Proposed solution**
Put the remark on vector multiplication below

**Comment by skabaw** [comment]
accidentally closed

**Comment by mpd37** [comment]
We are fairly explicit about this in chapter 2:
![image](https://user-images.githubusercontent.com/5500569/106360069-60d20280-630e-11eb-8f8a-5d8c705bb1b9.png)
