### ISSUE TITLE
Added tutorial on Bayesian linear regression (chapter 9.3)

### ISSUE THREAD

**Issue by zotroneneis** [mml-book/mml-book.github.io#615]
I used chapter 9 of the book to work through Bayesian linear regression and created a jupyter notebook including the most important theoretical knowledge and code: https://github.com/zotroneneis/machine_learning_basics/blob/master/bayesian_linear_regression.ipynb. You can run the notebook online using Binder: https://mybinder.org/v2/gh/zotroneneis/machine_learning_basics/HEAD?filepath=bayesian_linear_regression.ipynb

I used the MML book as the only resource for creating the notebook, it was extremely helpful. Thank you for creating such a great book! I'm confident that the Python code will help others, too. Therefore, I would like to ask if you would add the notebook to your list of resources/tutorials.

**Comment by mpd37** [comment]
That's really great! I linked the notebook from the "external sources" page.

**Comment by zotroneneis** [comment]
@mpd37 I wanted to work through the chapter on SVMs next and saw that you're already working on a tutorial notebook. Is there a chance to take a look at that notebook, even if it's incomplete? Otherwise I will create one myself :)

**Comment by chengsoonong** [comment]
Please create a notebook. Would be happy to also include an SVM notebook.

**Comment by zotroneneis** [comment]
@mpd37 @chengsoonong The notebook on SVMs is ready: https://github.com/zotroneneis/machine_learning_basics/blob/master/support_vector_machines.ipynb

It can be [run interactively in the Browser with Binder](https://mybinder.org/v2/gh/zotroneneis/machine_learning_basics/HEAD?filepath=support_vector_machines.ipynb).

Could you add it to your list of resources, like the one on BLR?
