### ISSUE TITLE
calculation mistake

### ISSUE THREAD

**Issue by yun-cheng** [mml-book/mml-book.github.io#62]
**Describe the mistake**
calculation mistake.

**Location**
Please provide the 
1. Draft (2018-07-09) from Mathematics for Machine Learning
2. Chapter 11
3. page 322
4. line number/equation number (11.30)

**Proposed solution**
In the description below, N1 = 1.0 + 1.0 + 0.057 + 0.001 = 2.058  and N2 = 0.943 + 0.999 + 0.066 = 2.008

**Additional context**
mistake

**Comment by mpd37** [comment]
thanks for double-checking; will be fixed in next revision
