### ISSUE TITLE
Typo: "subsituting", missing "the"

### ISSUE THREAD

**Issue by st--** [mml-book/mml-book.github.io#625]
**Describe the mistake**
Chapter 6.7.2, p. 217
Line 8 from bottom: "subsituting" -> "substituting"
Line 2 from bottom: "that random variable" -> "that the random variable"

Another missing "the" in "We introduced preceding three distributions" a bit earlier on p. 207.

(Version 2021-01-14)

**Comment by mpd37** [comment]
- substituting error fixed
- disagree with the necessity of adding "the" in front of random variable
- fixed error on p. 207
