### ISSUE TITLE
Typo: double space

### ISSUE THREAD

**Issue by st--** [mml-book/mml-book.github.io#630]
**Describe the mistake**
`We assume that the reader is already familiar with  computing probabilities`
has a double space (perhaps due to a silent TeX command in between)?

(Also, the comma-separated list in the line just before has the comma inside the quote signs, not sure if that's consistent with the rest of the book.)

**Location**
1. version 2021-01-14
2. Chapter 6
3. page 176
4. first line of Example 6.1

**Proposed solution**
Remove reason for double space

**Comment by mpd37** [comment]
good catch! fixed in next revision
