### ISSUE TITLE
Misleading part in Example 2.8 (Minus-1 Trick)

### ISSUE THREAD

**Issue by ZhenghaoXiao32** [mml-book/mml-book.github.io#635]
**Describe the mistake**
In the first line of Example 2.8:
"Let us revisit the matrix in (2.49), which is already in REF:"
The last word should be "Reduced REF" instead of "REF" given the Minus-one Trick can only be applied on Reduced REF.

**Location**
Please provide the 
1. version (bottom of page)
Draft (2021-01-14)
2. Chapter
Chapter 2.3 Solving Systems of Linear Equations
3. page
33
4. line number/equation number
The first line of Example 2.8

**Proposed solution**
Replace "REF" to "Reduced REF"

**Additional context**
When I was trying to solve the exercises, this line misled me to use the Minus-one Trick on REF and led to wrong solutions.

**Comment by mpd37** [comment]
thanks. that's correct. will fix it with the next revision
