### ISSUE TITLE
Missing a closing parenthesis in Ch5, pg 146

### ISSUE THREAD

**Issue by rasbt** [mml-book/mml-book.github.io#64]
**Describe the mistake**

Minor typo: Missing a closing parenthesis

**Location**
Please provide the 
1. version: 2018-07-02
2. Chapter: 5
3. page: 146
4. line number: 2732

**Proposed solution**

Add a closing parenthesis ( ")" ) at the end of the sentence.

**Additional context**

Full sentence context:

If we multiply the factors together, multiplication is defined (the dimensions of ∂ f match, and ∂ f “cancels”, such that ∂g/∂x remains.

**Comment by mpd37** [comment]
well spotted. will be fixed with next update.
