### ISSUE TITLE
ch2 - Inverse and Transpose

### ISSUE THREAD

**Issue by cprasad111** [mml-book/mml-book.github.io#640]
**Describe the mistake**
Superscript to denote matrix inverse should be -1. Instead -T is used

**Location**
Definition 2.5
(A<sup>-1</sup>)<sup>T</sup> = (A<sup>T</sup>)<sup>-1</sup> := A<sup>-T</sup>

**Proposed solution**
Should the right most expression be A<sup>-1</sup> instead of A<sup>-T</sup>
i.e. 
(A<sup>-1</sup>)<sup>T</sup> = (A<sup>T</sup>)<sup>-1</sup> := A<sup>-1</sup>

**Comment by AlbertoGuastalla** [comment]
In a symmetric matrix A, the inverse and the transpose operations are commutatives.
Therefore this superscript denoting transpose and inverse or inverse and then transpose is correct.

**Comment by cprasad111** [comment]
I agree on the inverse and transpose are commutative. I don't understand what A<sup>-T</sup> means. 
T means transpose and -1 means inverse. What does -T in the superscript means

**Comment by AlbertoGuastalla** [comment]
It's a shortcut meaning the composition of transpose and inverse operations.
