### ISSUE TITLE
Equations 5.137 and 5.141

### ISSUE THREAD

**Issue by sophoi** [mml-book/mml-book.github.io#649]
**Describe the mistake**
Both equations 5.137 and 5.141 on page 163 should have a minus sign in front of the first term of the right hand side.

**Location**
1. version: online PDF Draft (2021-01-14)
2. Chapter 5
3. page 163
4. equation number 5.137 and 5.141

**Proposed solution**
(5.137) should be
`
∂f/∂a = - ∂f/∂b ∂b/∂a + ∂f/∂c ∂c/∂a
`
and therefore (5.141) should have a similar change:
`
∂f/∂a = - ∂f/∂b exp(a) + ∂f/∂c * 1
`

**Additional context**
(5.137) is based on (5.125) c = a + b, by which we know a = -b + c, therefore the first term on the right hand side of (5.137) that's related to b should have a minus sign in front.

**Comment by mpd37** [comment]
Equation looks good to me as it is: (5.137) is a generic expression, i.e., this is how the chain rule is defined. If there are any minus signs, they need to come through the partial derivatives, which we don't spell out in that particular equation.
