### ISSUE TITLE
Missing "and" on page 94 of Hardback book

### ISSUE THREAD

**Issue by sophoi** [mml-book/mml-book.github.io#652]
**Describe the mistake**
"and" missing from hardback book on page 94

**Location**
Please provide the 
1. version: Hardback book (ISBN 978-1-108-47004-9)
2. Chapter 4
3. page 94
4. In definition 4.13: 
Current online PDF has "with an algebraic multiplicity
m > 1 and a geometric multiplicity of less than m."
However, the "and" before "a geometric" is missing from the hardback book

**Proposed solution**
update the errata to mark this for Hardcopy book

**Additional context**
Without the "and", it took me several times to read and understand that part

**Comment by mpd37** [comment]
this will be fixed in the next printing
