### ISSUE TITLE
Minor typo with closing bracket on exercise 2.16(e)

### ISSUE THREAD

**Issue by Htermotto** [mml-book/mml-book.github.io#657]
**Describe the mistake**
On exercise 2.16(e), page 55 in the print copy and page 68 in the ebook, there is an opening bracket where there should be a closing one.

![image](https://user-images.githubusercontent.com/9905056/117558759-f687d700-b04d-11eb-9d7c-bafb61c8086c.png)

**Location**
1. Draft (2021-01-14) of “Mathematics for Machine Learning” and the print book.
2. Chapter 2, Linear Algebra
3. page 55 in print, 68 on ebook
4. 2.16(e)

**Proposed solution**
End opening bracket should be a closing bracket, meaning [0,2pi]

**Comment by mpd37** [comment]
That's actually correct: that notation excludes 2\pi. An equivalent way of writing this is [0, 2\pi).

**Comment by Htermotto** [comment]
Ok, thanks. I hadn't seen that open left bracket notation before, only the parenthesis to indicate non-inclusivity.
