### ISSUE TITLE
Spectral theorem: assumption of real entries of matrix

### ISSUE THREAD

**Issue by sritee** [mml-book/mml-book.github.io#659]
**Describe the mistake**
**Book statement**
A direct implication of the spectral theorem is that the eigendecomposition of a symmetric matrix A exists (with real eigenvalues), and that we can find an ONB of eigenvectors so that A = P DP >
, where D is diagonal and the columns of P contain the eigenvectors.

**Location**
Please provide the 
1. Version - 2021 M. P. Deisenroth, A. A. Faisal, C. S. Ong. Published by Cambridge University Press (2020).
2. Chapter - 4.2
3. page - 111
4. line number/equation number - Theorem 4.15, below that

**Proposed solution**
It would be worthwhile to emphasize that matrix A needs to have real entries. If A has complex entries, the eigen-values are still real, but eigenvectors sometimes cannot be chosen to be orthonormal (additional assumption needed that A = A conjugate transpose).  It is already emphasized in a subtle way by having A belongs to R(nxn) in the theorem heading, but making the statement more explicit could be helpful. Reading the quoted lines alone could be a little mis-leading.

**Additional context**
Thanks for the great book!

**Comment by mpd37** [comment]
I'd leave it as it is. We pretty much exclusively focus on real-valued vector spaces/matrices etc. (that's also stated upfront), and the R^{nxn} case should also clarify this. 

If we add that information here, we will need to add it throughout the book for consistency reasons, and I don't think this will be helpful.
