### ISSUE TITLE
Add option to get notification when book is for sale

### ISSUE THREAD

**Issue by mdcallag** [mml-book/mml-book.github.io#67]
I want to buy this book. Sometimes books are listed on Amazon before they are published and I can pre-order. This book is not listed there yet. I ended up creating a calendar entry to remind myself to check for it again in a few months. The alternative is for the publisher to let me sign up to get a notification when the book is for sale.

Regardless, thanks for sharing the content at https://mml-book.github.io/

**Comment by mpd37** [comment]
Unfortunately, Cambridge University Press doesn't offer anything like this. We expect the book to be published in Q1/2019.
