### ISSUE TITLE
Largest versus Smallest AIC

### ISSUE THREAD

**Issue by bioatmosphere** [mml-book/mml-book.github.io#672]
**Describe the mistake**
A tiny mistake about AIC in model selection, which should be "smallest" instead of "largest"

**Location**
Please provide the 
1. version 2021-05-08
2. Chapter 8.6.4
3. page 288
4. line number/equation number two lines above equation 8.48

**Proposed solution**
Change from "largest" to"smallest" value.

**Comment by mpd37** [comment]
You want to maximize the AIC, not minimize. (Similarly, you would maximize the log-likelihood, not minimize)
