### ISSUE TITLE
If and only if sign is used (<=>). The correct sign should be (=>).

### ISSUE THREAD

**Issue by AftabHussain** [mml-book/mml-book.github.io#677]
**Describe the mistake**
If and only if sign is used (<=>). The correct sign should be (=>).

**Location**
1. version : Draft (2021-05-08)
2. Chapter : 2. Linear Algebra
3. page : 22
4. line number/equation number : 2.10

**Proposed solution**
The correct sign should be (=>).

**Additional context**
There relationship between equations 2.9 and 2.10 is not based on "if and only if". The correct relationship is implies.

**Comment by mpd37** [comment]
<=> is correct. Both expressions are equivalent.
