### ISSUE TITLE
Example 2.23 (Basis Change)

### ISSUE THREAD

**Issue by FarzadMinooei** [mml-book/mml-book.github.io#697]
Hi,

Regarding example 2.23 (version 2021-07-29, chapter 2, page 53-54), here is a complete answer using python:

As question said, we have:

`import numpy as np`
`A = np.array([[2, 1], [1, 2]])`
`B = np.array([[1, 1], [1, -1]])`

So the transformation matrix based on equation 2.105, would be:

T_inv * A_phi * S = 
`T_inv @ A @ S`

`S = B`
`T_inv = np.linalg.inv(B)`

which results in:

`array([[3., 0.],
       [0., 1.]])`

**Comment by farid-moradi** [comment]
We have two bases: _B_ and _E_. _B_ is the new basic and E is the old one (_R2_ canonical).

We can think about the transformation algorithmically as follows:

1- First, we take every vector from _B_ to _E_ using the matrix _B_. For example, (1, 0) with respect to _B_ becomes (1, 1) with respect to _E_. Both of these coordinates represent the same vector.

2- Next, we perform the transformation using the matrix _A_. Now every vector of _B_ is transformed, but their coordinate representations are based on _E_. 

3- Finally, we return to the world of our new basic _B_. For this, we need to have the reverse matrix of _A_. The resulting matrix transforms the vector space in the same way _A_ does but with respect to our new basis.

Your solution didn't perform the last step.
