### ISSUE TITLE
Small typo in Chapter 2, page 58

### ISSUE THREAD

**Issue by acartamersoy** [mml-book/mml-book.github.io#698]
**Describe the mistake**
Small typo

**Location**
1. version (bottom of page): Draft (2021-07-29)
2. Chapter: 2
3. page: 58
4. line number/equation number: N/A

**Proposed solution**
"We also call V and W also the domain..." -> "We call V and W also the domain..." [One of the "also"s is extra]

**Additional context**

**Comment by mpd37** [comment]
Thanks! Will be fixed with next revision.

**Comment by reneederer** [comment]
Hello,
this typo is actually not fixed in the current version of the book.
