### ISSUE TITLE
Parentheses missing in formula 5.6c

### ISSUE THREAD

**Issue by k2pctdn** [mml-book/mml-book.github.io#699]
Problem: parentheses missing in formula.
1. Version: 2021-07-29
2. Chapter: 5
3. page: 142
4. equation number: 5.6c
Correction:
It should have outer parentheses in the limit 5.6c: 
<img src="https://render.githubusercontent.com/render/math?math=\displaystyle\lim_{h\to 0}\left(\binom{n}{1}x^{n-1}%2B\sum_{i=2}^{n}\binom{n}{i}x^{n-i}h^{i-1}\right)">

**Comment by mpd37** [comment]
I'll add the parentheses for clarity. Will be fixed with next update of PDF.
