### ISSUE TITLE
Small typo in Chapter 4, page 129

### ISSUE THREAD

**Issue by acartamersoy** [mml-book/mml-book.github.io#700]
**Describe the mistake**
Small typo

**Location**
Please provide the 
1. version (bottom of page): Draft (2021-07-29)
2. Chapter: 4
3. page: 129
4. line number/equation number: N/A

**Proposed solution**
In the second bullet point that starts with "It is possible to define the SVD of a rank-r", it is stated that "V an r × n matrix". V should be of size (n, r) so that V^T can multiply with \Sigma of size (r, r).

**Comment by mpd37** [comment]
Good catch. I'll update this with the next revision.
