### ISSUE TITLE
Can two planes intersect in a point?

### ISSUE THREAD

**Issue by alikaraali** [mml-book/mml-book.github.io#703]
It is stated in the book that "When we intersect these planes, i.e., satisfy all linear equations at the same time, we can obtain a solution set that is a plane, a line, a point or empty (when the planes have no common intersection).". 

I am doubting that it is a correct statement: "**we can obtain a solution set that is a point**". As it is discussed many other places before
- https://www.quora.com/Can-two-planes-meet-in-exactly-one-point
- https://math.stackexchange.com/questions/219233/can-two-planes-intersect-in-a-point

<img width="625" alt="Screen Shot 2021-12-08 at 14 16 53" src="https://user-images.githubusercontent.com/22373469/145223608-70302553-4fa3-4aa6-b472-1e00b7a859a1.png">

1. 2021 M. P. Deisenroth, A. A. Faisal, C. S. Ong. Published by Cambridge University Press (2020
2. Chapter 2
3. page 21
4. Just before the last paragraph

**Comment by chengsoonong** [comment]
Thanks for reporting it. You are correct for two planes in three dimensions (variables). The intent here is the more general case, which is three equations with three unknowns, which can result in those cases.
