### ISSUE TITLE
Example 5.11

### ISSUE THREAD

**Issue by yannis1962** [mml-book/mml-book.github.io#711]
**Describe the mistake**

On page 154, Example 5.11 you first define y = Φθ (5.75) and then e(θ):=y-Φθ (5.77). Something is missing here
since if (5.75) holds then, according to definition (5.77), e(θ) must be always zero.

**Location**
Please provide the 
1. version (bottom of page) 2021-07-09
2. Chapter  5
3. page  154
4. line number/equation number  5.75 and 5.77

**Proposed solution**
Explain what (5.75) exactly means since obviously it is not an equation (otherwise in 5.77 e would be identical to zero).

**Additional context**

**Comment by mpd37** [comment]
For the correct parameters, that is correct. When we start learning, we initialize the parameters in some (random) way, and then use the gradient signal to find the 'correct' ones.
