### ISSUE TITLE
New paper edition?

### ISSUE THREAD

**Issue by AndreaPi** [mml-book/mml-book.github.io#714]
Hi, 

compliments for your book! It's really great! I'd like to buy the paperback edition, but it's missing quite a few of the improvements [the current draft](https://mml-book.github.io/book/mml-book.pdf) has. Are you planning to publish a second edition? That would be fantastic, and I'd probably buy two copies (one as a gift 😀 ). Please let me know, thanks!

**Comment by mpd37** [comment]
Thanks! There's currently no concrete plan to do a 2nd edition, but we'll reach out to CUP to see whether they can incorporate the changes in a next printing.
