### ISSUE TITLE
Plane intersections - question

### ISSUE THREAD

**Issue by bojanv55** [mml-book/mml-book.github.io#719]
page 21:

```
When we intersect these planes, i.e., satisfy all linear equations at
the same time, we can obtain a solution set that is a plane, a line, a point
or empty (when the planes have no common intersection). 
```

can it actually be `a point`?

**Comment by AnshG714** [comment]
Same question - I don't think 2 planes can intersect at a point if they are infinite?

**Comment by mpd37** [comment]
2 planes (2D subspaces) can intersect in a point when the dimensionality of the vector space is 4D or higher.
