### ISSUE TITLE
Minor typos (Chapter 1 and Chapter 2)

### ISSUE THREAD

**Issue by tbuehler** [mml-book/mml-book.github.io#72]
Chapter 1 (Version 10.07.2018):

- page 13, line 714: "the" too much

Chapter 2 (Version 08.08.2018):

- page 27, line 915: refers to Remark 2.3.1 but remarks are not numbered
- page 28, example 2.6: eq. (2.38) states general solution without explanation how to obtain it (which is then given later in the context of example 2.7, but a reference to the later section is missing)
- page 34, example 2.10: there is a reference to a footnote 1 which does not exist
- page 40, line 1145: “the pivot columns contain the vectors, which are” -> comma too much
- page 43, line 1186: “maximal linearly independent subset” is not defined
- page 48, line 1265: comma missing after “is an ordered basis”
- page 48, figure 2.7: figure is part of the side note column instead of the main column
- page 49, before eq. (2.85): uses image Im but definition comes only later on page 55, Def 2.22

**Comment by mpd37** [comment]
thanks for the detailed comments. will be fixed in the next revision
