### ISSUE TITLE
No indication, that I can find, what the diamond characters mean at the end certain sections.

### ISSUE THREAD

**Issue by raymondj-pace** [mml-book/mml-book.github.io#727]
**Describe the mistake**
There are diamond characters at various points in the book. I do not see any footnotes or anything to indicate their purpose.

**Location**
Please provide the 
1. version - Paperback ISBN 978-1-108-45514
2. Chapter 2
3. Page 12
4. 5th text line from the top of page

**Proposed solution**
An indication as to what these diamond symbols indicate.

**Additional context**

**Comment by chengsoonong** [comment]
The diamond symbols indicate the end of that particular part of text. In the example you pointed out, it "closes" the Remark on geometric systems of linear equations.
