### ISSUE TITLE
Missing mixture weight pi_j in the equation 11.48

### ISSUE THREAD

**Issue by vu-minh** [mml-book/mml-book.github.io#73]
**Describe the mistake**
In the proof of _**Theorem 11.3**_, in the patial derivatives of the Lagrangian expression w.r.t `pi_k`,
in the denominator of the first term, the mixture coefficient `pi_j` is missing.

**Location**
1. version: **Draft (2018-07-09)**
2. Chapter: **11**
3. page: **326**
4. line number/equation number **11.48**

**Proposed solution**
![eq_11.48](https://user-images.githubusercontent.com/38859995/44415328-7a34c900-a570-11e8-9e6a-229c66956363.png)

**Additional context**
Just a little suggestion to make the derivation of `N_k` is more intuitive (but maybe it's not necessary):
![suggest](https://user-images.githubusercontent.com/38859995/44415351-86208b00-a570-11e8-8feb-c9b4465816e7.png)

**Comment by mpd37** [comment]
Thanks for the suggestions. They will be implemented with the next revision.
