### ISSUE TITLE
The "if and only if" and "implies" arrows are not left-aligned in the table of symbols in the Foreword

### ISSUE THREAD

**Issue by johnwickerson** [mml-book/mml-book.github.io#730]
**Describe the mistake**
The "if and only if" and "implies" arrows are not left-aligned with the other entries in the table.

<img width="387" alt="Screenshot 2022-10-05 at 16 07 29" src="https://user-images.githubusercontent.com/4182011/194098898-64cbad00-9dfd-4cc0-9921-c4d8d42aa6f4.png">

**Location**
1. Version 2022-01-11
2. Chapter 0 (Foreword)
3. Page 6
4. Around line 24

**Proposed solution**
This is a LaTeX issue -- those arrows are interpreted as binary operators with their own spacing. Replace `\Longleftrightarrow` with `{\Longleftrightarrow}` and it should be fixed.

**Comment by mpd37** [comment]
Thank you. Will fix this.

We actually used \iff and \implies, but the fix you suggest doesn't work with this; use \Longleftrightarrow etc. now in the foreword.
