### ISSUE TITLE
Typo in exercise 5.9

### ISSUE THREAD

**Issue by tteodorescu0** [mml-book/mml-book.github.io#735]
**Describe the mistake**
- Exercise 5.9 uses the notation g(z, ν) , but function g also depends on x. 
- It's unclear what is the codomain of p and q.

<img width="939" alt="Screen Shot 2023-01-10 at 7 54 44 PM" src="https://user-images.githubusercontent.com/16628089/211693137-3be5ba1b-5e28-4914-b86a-aea0831e387f.png">

**Location**
Please provide the 
1. version: Draft (2022-01-11) of “Mathematics for Machine Learning”
2. Chapter: 5
3. page: 171
4. exercise 5.9

**Proposed solution**

- Replace each of the two occurrences of g(z, ν) with g(x, z, ν)
- Clarify that the codomain of each of p and q is R.

**Comment by mpd37** [comment]
I made the suggested change w.r.t. g (by adding x). For the time being, we need to leave the explicit co-domain out, because it will spill over to the next page, which we can't do before we have a 2nd printing.
