### ISSUE TITLE
Eq 9.26 incorrect symbol

### ISSUE THREAD

**Issue by wjwangames** [mml-book/mml-book.github.io#737]
**Describe the mistake**
To be consistent with eq.9.7 where \theta_{ML} definition,
the ∈ symbol shall be replaced with = symbol in eq 9.26. 

1. 2022 Jan-11 version.
2. Chapter 9.
3. page 301
4. eq.9.26.

**Location**
Please provide the 
1. version (bottom of page)
5. Chapter
6. page
7. line number/equation number

**Proposed solution**
A clear and concise description of what you would like to change.

**Additional context**

**Comment by mpd37** [comment]
Thanks for raising the issue. I'll make it consistent by replacing the "=" in (9.7) with "∈"
