### ISSUE TITLE
Section 5.6.1 Error

### ISSUE THREAD

**Issue by Hrrsmjd** [mml-book/mml-book.github.io#739]
In the opening paragraph of section 5.6.1, function $f_i(\mathbf{x}_{i-1})$ is not a function of $\mathbf{x}_{i-1}$.

**Comment by mpd37** [comment]
The text reads:
$f_i(x_{i-1}) = \sigma(A_{i-1} x_{i-1} + b_{i-1})$

and it explicitly mentions x_{i-1}?

**Comment by Hrrsmjd** [comment]
> The text reads: fi(xi−1)=σ(Ai−1xi−1+bi−1)
> 
> and it explicitly mentions xi−1?

The physical book doesn't mention $x_{i-1}.$

**Comment by mpd37** [comment]
Got it. Thanks for raising this. It's corrected in the online version, but apparently I forgot to add it to the errata list, which I have done now.
