### ISSUE TITLE
11.2.3 updating the covariance

### ISSUE THREAD

**Issue by sili12** [mml-book/mml-book.github.io#746]
Derivative of sigma may refer to 5.103 not 5.106. 

**Location**
Please provide the 
1. Cannot find
4. Chapter 11
5. 322
6. 11.34

**Proposed solution**
A clear and concise description of what you would like to change.

**Additional context**

**Comment by mpd37** [comment]
This had been corrected previously: https://www.overleaf.com/read/gskfhtxdwtmh#86801a
