### ISSUE TITLE
Figure numbers not increasing

### ISSUE THREAD

**Issue by comines** [mml-book/mml-book.github.io#751]
**Describe the mistake**
Figure numbers do not increase in most chapters. For example, chapter 2 has three figures with number 2.1 . Chapter 5 has seven figures with number 5.1 .

**Location**
Please provide the 
1. version (bottom of page) : Draft (2023-02-15)
3. Chapters: all
4. page
5. line number/equation number

**Proposed solution**
A clear and concise description of what you would like to change.
Number figures consecutively.

**Additional context**

**Comment by kir0ul** [comment]
Got confused by that too.

**Comment by mpd37** [comment]
Thanks for reporting this. We are looking into it.

**Comment by mpd37** [comment]
this should be fixed now, but (honestly) I have no idea what the issue is/was
