### ISSUE TITLE
Mistake: Example 4.11, step 1, the computation of the Characteristics Polynomial of A

### ISSUE THREAD

**Issue by AI-Ahmed** [mml-book/mml-book.github.io#756]
**Describe the mistake**
There is a computation error of the **eigenvalue** and the **eigenvector** (Step 1).

**Location**
Please provide the 
1. version (bottom of page): **Draft (2023-02-15)**
2. Chapter: **Chapter 04**
3. page: **pp.117-118**
4. line number/equation number: **4.11**

**Proposed solution**
I computed the characteristic polynomial online if you want to get back to it: [Step 01: Characteristic Polynomial of Example 4.11](https://www.symbolab.com/solver/matrix-characteristic-polynomial-calculator/characteristic%20polynomial%20%5Cbegin%7Bpmatrix%7D2.5%26-1%5C%5C%20%201%262.5%5Cend%7Bpmatrix%7D?or=input)

The Quadratic function should be $\lambda^2-5\lambda + 7.25$ Instead of $\lambda^2-5\lambda + \frac{21} 4$.
Therefore, $\lambda_1 \approx 1.5389$ and $\lambda_2 \approx 4.7110$

**Additional context**
This issue will affect the whole example's solution, so the entire model needs to be recomputed again.

**Comment by mpd37** [comment]
You computed the eigenvalues of the wrong matrix: Entry [2,1] should be -1, not +1. If you change this (I did that in the link you provided), you'll get the same answer that we have.
