### ISSUE TITLE
Figure 6.1 size mismatch

### ISSUE THREAD

**Issue by davidoj** [mml-book/mml-book.github.io#76]
Figure 6.1 on page 167 features a lot of text overlapping other text.

July 4 2018, Chapter 6, page 167 at top.

I suggest making the picture taller, or making the text smaller if size constraints are an issue.

**Comment by chengsoonong** [comment]
We're tweaking the mindmaps some more. Have a look at the version on ab2f03527c40f9ea68a63c04f72605671b80652f
