### ISSUE TITLE
The last bullet point on page 60 is wrong

### ISSUE THREAD

**Issue by razeghi71** [mml-book/mml-book.github.io#763]
**Describe the mistake**
The last consequence that has been listed at the end of page 60 is that: if $dim(v) = dim(w)$ then $\Phi$ is injective and surjective and bijective. but I think the right version should be: If $dim(v) = dim(Im(\Phi))$ then $\Phi$ is injective and surjective and bijective.

**Location**
Please provide the 
1. 2023-10-18 
2. 2.7.3
3. 60
4. descriptions under formula (2.129)

**Proposed solution**
Change  $dim(v) = dim(w)$ to $dim(v) = dim(Im(\Phi))$

**Comment by mpd37** [comment]
I believe the statement is correct as it is: If dim(V) = dim(W) then it holds that 

injective <=> surjective <=> bijective

Assume dim(V) = 1, dim(Im(\Phi)) = 1, dim (W) = 2

We can have an injective mapping, but that wouldn't be surjective or bijective. 

I may miss something, though.

**Comment by razeghi71** [comment]
That's true, what I wrote instead was also wrong, but lets say $V = W = R^2$ and $\Phi$ is a function that maps all vectors in $V$ say $[x, y]^T$ to $[x, 0]^T$ in $W$, here $Im(\Phi) \subseteq W$ but $\Phi$ is not surjective, injective.

**Comment by mpd37** [comment]
OK. Then I'll close this issue
