### ISSUE TITLE
was it now out of date？

### ISSUE THREAD

**Issue by Leeei-ZS** [mml-book/mml-book.github.io#764]
i am a fresh in ML, and want to improve my math skill in this area.
i want to know is this project a good choice?
Your help will be appreciated!

**Comment by Him188** [comment]
It is currently taught as a third-year or fourth-year course "Mathematics for Machine Learning" at Imperial College London, so it can be a good choice for you. *However, many of my colleagues say that this course is interesting but hard. Good luck to you!*

**Comment by Leeei-ZS** [comment]
> It is currently taught as a third-year or fourth-year course "Mathematics for Machine Learning" at Imperial College London, so it can be a good choice for you. _However, many of my colleagues say that this course is interesting but hard. Good luck to you!_

thanks a lot >_<
