### ISSUE TITLE
The Difference Between Affine Transformation and Affine Mapping

### ISSUE THREAD

**Issue by ckwastra** [mml-book/mml-book.github.io#765]
**Describe the mistake**
Unlike *linear mapping* and *linear transformation*, it seems that *affine transformation* (AT) and *affine mapping* (AM) are different concepts.[^1] That is, an AT is an *automorphism* while an AM is a generalization of the former as defined in the book. It follows that ATs preserve the dimension and parallelism but AMs don't need to. So I believe that the following text actually refers to ATs:

> * Affine mappings keep the geometric structure invariant. They also preserve the dimension and parallelism.

**Location**
1. Draft (2023-10-18)
2. Chapter 2
3. Page 63
4. Lines 11-12

**Proposed solution**
A possible revision of the above text is:
* An *affine transformation*, which is a bijective affine mapping that maps a space onto itself, keeps the geometric structure invariant. It also preserves the dimension and parallelism.

[^1]: Wikipedia contributors. (2023, August 4). Affine transformation. In Wikipedia, The Free Encyclopedia. Retrieved 02:57, December 17, 2023, from https://en.wikipedia.org/w/index.php?title=Affine_transformation&oldid=1168715119

**Comment by mpd37** [comment]
Thanks for pointing this out. Would it be OK to say (in the last bullet point) that if $\phi$ is bijective, then the geometric structure is preserved? (That's kind of what you suggested above, if I understand correctly).

I would like to avoid introducing the concept of an affine transformation.

**Comment by mpd37** [comment]
Thank you. Will fix this now.
