### ISSUE TITLE
Typo in Example 6.12 (Beta-Bernoulli Conjugacy)

### ISSUE THREAD

**Issue by ckwastra** [mml-book/mml-book.github.io#766]
**Describe the mistake**
Regarding the following equation:

> $$p(\theta|x,\alpha,\beta)=p(x|\theta)p(\theta|\alpha,\beta)$$

I believe that the intent here was to use symbol $\propto$ but not $=$ since 

$$p(\theta|x,\alpha,\beta) = \frac{p(x|\theta)p(\theta|\alpha,\beta)}{p(x|\alpha,\beta)}$$

according to Bayes' theorem.

**Location**
1. Draft (2023-12-19)
2. Chapter 6
3. Page 209
4. Equation (6.105a)

**Proposed solution**
Change the above equation to

$$p(\theta|x,\alpha,\beta) \propto p(x|\theta)p(\theta|\alpha,\beta)$$

**Comment by artkpv** [comment]
This is the case when you struggle to understand but it turns out that it was a mistake in the book :confused: Thanks for posting this
