### ISSUE TITLE
Concatenated Random Variable States (2)

### ISSUE THREAD

**Issue by ckwastra** [mml-book/mml-book.github.io#767]
**Describe the mistake**
In the provided text:

> ... To consider the effect of applying the sum rule of probability and the effect of conditioning, we explicitly write the Gaussian distribution in terms of the concatenated states $[\boldsymbol{x}^\top, \boldsymbol{y}^\top]$, ...

I believe it maintains greater consistency to employ ${[\boldsymbol{x}^\top, \boldsymbol{y}^\top]}^\top$ as the notation for the concatenated states. In this context, we concatenate two column vectors to create a new column vector. While this notation was suggested in #513, the notation $[\boldsymbol{x}^\top, \boldsymbol{y}^\top]$ (without the transpose of the row vector) was ultimately adopted. Any clarification on this matter is appreciated.

**Location**
1. Draft (2023-12-19)
2. Chapter 6
3. Page 199
4. Line 3

**Proposed solution**
Change $[\boldsymbol{x}^\top, \boldsymbol{y}^\top]$ to ${[\boldsymbol{x}^\top, \boldsymbol{y}^\top]}^\top$ in the above text.

**Comment by mpd37** [comment]
Thanks. #513 was insufficiently resolved. That was a typo at our end. Will fix this now.
