### ISSUE TITLE
Chapter 6 minor changes

### ISSUE THREAD

**Issue by davidoj** [mml-book/mml-book.github.io#77]
July 4, 2018 version.

2965: The example doesn't clearly illustrate a case where P(B|~A)<P(B) implies P(A|B) > P(A). Suggested modification: [...] We are waiting for a friend, and consider three possibilities; H1: she is on time, H2: she has been delayed by traffic and H3: she has been abducted by aliens. When we observe our friend is late, we must logically rule out H1. We also consider H2 to be more likely, though we are not logically required to do so. Finally, we may consider H3 to be more likely, but we continue to consider it quite unlikely. How do we conclude H2 is the most plausible answer? [...]

2996: Repeated text: 

> The frequentist interpretation The frequentist interpretation considers probability to be the relative frequencies of events, in the limit when one has infinite data.

3087: 
> We can think of a probability distribution as filling out a multidimensional array of numbers.

Suggest a reference to example 6.1 at the end of this sentence.

3122: Suggest to refer to equation 6.4 and contrast terms probability density and probability mass

3133: _Less than or equal to_

Further suggestion, same section:
> the probability mass function must be in the interval [0,1] for each state. However the analogous requirement for continuous random variables (Equation (6.14)) does not imply that the value of the density is less than or equal to 1 for all values.

3144: unidimensional and multidimensional? (can you have a multivariate variable? I'm not sure)

3162: For example (a camera sensor introduces random error in the value of each pixel it records).

3169: Maybe explain connection between probability distribution and probabilistic model. 

E.g. A model of a set of variables {x} describes relationships between those variables (e.g. simultaneous equations). A probabilistic model describes relationships between random variables {x}, and can be completely described by the probability distribution P(\mathbf{x}). This means that probabilistic models can be manipulated with the same basic rules we use to manipulate distributions.

**Comment by chengsoonong** [comment]
Thanks for the suggestions.

**Comment by chengsoonong** [comment]
Fixed in 3fa732f8b4890d35ff8c777c89449b43c798a0d3
