### ISSUE TITLE
Chapter 12 feedback

### ISSUE THREAD

**Issue by cdawei** [mml-book/mml-book.github.io#79]
First sentence of p332. "... predictor to predict one of a number of outcomes". need to rephrase.
7th line of p332. missing comma after "that is".
Line 5923 of p333. missing comma after "In contrast".
Line 5933 of p333. missing comma after "Intuitively".
Line 5943 of p334. "the two equivalent ways ...". remove "the".
First sentence below Eq (12.2). need to rephrase.
Second sentence below Eq (12.3). "that w is normal vector" -> "that w is a normal vector".
Line 5965,5966. missing comma after "That is" and "In contrast".
First sentence above Eq (12.7). "points with the negative labels". remove "the".
Line 5983 of p335. "(x_n, y_n)" -> "(x_N, y_N)".
Last paragraph of p336. make it clear that x_a is the closest point to hyperplane.
Eq (12.29). align it with Eq (12.28).
Line 6065. "this is one called the ..." -> "this one is called the ...".
Line 6068. missing comma after "parameter".
Line 6075. text overflow.
Line 6078. "w is regularized by b is not ..." -> "w is regularized but b is not ...".
Line 6082. missing comma after "Furthermore".
Line 6106. missing comma after "In other words".
Line 6110. (Remark), technically, Eq (12.34) is an optimization of hinge loss, not the hinge loss itself.
Line 6122. remove "will".
Line 6124. "more features than number of data" -> "more features than the number of data".
Eq (12.35), Eq (12.38). "gamma_i" -> "gamma_n".
Line 6134. "alpha_n" -> "alpha_N".
Last sentence above Eq (12.46). seems redundant.
First sentence below Line 6155. missing comma after "Second".
Last line above Eq (12.62). "positive class" -> "positive class distribution".
Eq (12.63). I guess it's "argmin" instead of "min".
First paragraph below Line 6232. 2nd to 5th sentence described the same thing twice.

**Comment by chengsoonong** [comment]
Thanks for the careful reading. These bugs will be fixed in the next version.
