### ISSUE TITLE
Definition 2.9: which + and \cdot? and "R-vector space" ?

### ISSUE THREAD

**Issue by chriswebers** [mml-book/mml-book.github.io#8]
There is no precise explanation that the vector space operations + and \cdot are inherited from space V.
Furthermore, the term "R-vector space" seems to be not defined.

**Comment by mpd37** [comment]
Made the operations more explicit. R-vector space was defined earlier when we introduced vector space. We consider removing it in a later version - it doesn't add much.

**Comment by mpd37** [comment]
removed R-vector spaces from the book. not useful.

![image](https://user-images.githubusercontent.com/5500569/41740342-9ab97402-758f-11e8-9895-942d5ba2372b.png)
