### ISSUE TITLE
Matrix in example 2.42 generates wider range of possibilities than described

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#80]
**Describe the mistake**
Description "reduced row echelon form without any rows that just contain zeros" does not seem to match general form of presented below matrix (latter in my opinion is not correct). Row 3 of matrix could have pivot which is an "arbitrary real number" which seems to conflict with definition of reduced row echelon form.

**Location**
1. version 2018-08-23
2. Chapter 2
3. page 31
4. line 972, example 2.42

**Proposed solution**
Rows 3 forwards should follow pattern introduced in rows 1 and 2.

**Additional context**
N/A

**Comment by mpd37** [comment]
All the rows below row 2 contain exactly one 1-entry. I'm not sure how to make this visible in another way. There are no rows with only zeros (see text above eq (2.42)). I'll add a bit more of an explanation, but if you have another suggestion, please let me know.

**Comment by mpd37** [comment]
![image](https://user-images.githubusercontent.com/5500569/44957944-25327480-aed9-11e8-9010-e431d627785a.png)
Does this make more sense to you (changed the * in the last row to 0)?

**Comment by mpd37** [comment]
We assume the matrix is in RREF (example 2 you give above is in REF, but we assume RREF). This requires the first non-zero entry in a row to be 1 and all other entries in that column to be 0.  Example 1 is in RREF. I believe what is needed is an explicit explanation that the first non-zero entry per row is 1. You definitely found something that didn't make much sense, so there needs to be some iteration on this.

I'm giving this another shot.

![image](https://user-images.githubusercontent.com/5500569/44958441-accfb180-aee0-11e8-9587-f043a3b86ade.png)

**Comment by Antymon** [comment]
Ah, sorry. In both cases I was thinking of RREF, which was contradiction in example no 2.

Indeed, new phrasing would have been probably clearer for me.

With being explicit about constraints I think original matrix is just fine.

**Comment by mpd37** [comment]
Great! I'll fix this with the next update. Thanks for the feedback. That was very helpful.
