### ISSUE TITLE
Linear independence example inconsistent with given algorithm

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#81]
**Describe the mistake**
Linear independence check algorithm, starting at line 1148 states what follows: "Write all vectors as columns of a matrix A. Gaussian elimination yields a matrix in (reduced) row echelon form...". Example at 1159, figure 2.61. makes conclusion based on matrix in REF but not RREF form.

If writing "(reduced)" signifies optionality then there is technically no inconsistency although if that's the intent then I would say it's rather confusing. Especially since, first, text-inlined example is actually RREF.

**Location**
1. version 2018-09-03
2. Chapter 2
3. page 42
4. figure 2.61

**Proposed solution**
Remove "(reduced)" if REF is sufficient or make figure 2.61 RREF. Alternatively any form of being more explicit about RREF being optional would improve the situation.

**Comment by mpd37** [comment]
Good point. Should be fixed now:
![image](https://user-images.githubusercontent.com/5500569/45203458-96c54680-b27c-11e8-96fb-97e576730984.png)

**Comment by Antymon** [comment]
Looks great.
