### ISSUE TITLE
Matrix addition

### ISSUE THREAD

**Issue by bumptiousmonkey** [mml-book/mml-book.github.io#82]
Hi,

On line 859 ch2 it says "now we have defined matrix multiplication, matrix addition and the identity matrix"

You have not, as far as I can tell, defined matrix addition. If you search the pdf that line is the first hit. I've read word for word up to that point and it isn't there explicitly.

Thanks for all the good work.

Tim.

**Comment by mpd37** [comment]
Good catch! I added a few lines about matrix addition. I believe this resolves this issue?

![image](https://user-images.githubusercontent.com/5500569/45203961-1acbfe00-b27e-11e8-9cd6-68961764678d.png)
