### ISSUE TITLE
Sum index incorrect

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#83]
**Describe the mistake**
In equation 2.100, middle sum (after using identity 2.99), first sigma should have index named k, not l. 

**Location**
Please provide the 
1. version 2018-09-03
2. Chapter 2 
3. page 52 (chapter's 37)
4. line 1324, equation 2.100

**Proposed solution**
Rename index pointed out in description from l to k.

**Additional context**
N/A

**Comment by mpd37** [comment]
Thanks for careful reading. This should fix it:

![image](https://user-images.githubusercontent.com/5500569/45204076-726a6980-b27e-11e8-8acd-797fa46aaa5b.png)
