### ISSUE TITLE
Inconsistency in a figure

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#84]
**Describe the mistake**
Figure 2.9 first mentions transformation {\Phi}_\widetilde{B}\widetilde{C} and then shows inverse transformation {\Phi}_\widetilde{C}\widetilde{B} as a composition of other transformations.

**Location**
Please provide the 
1. version 2018-09-07
2. Chapter 2
3. page 53 (chapter's 38)
4. figure 2.9

**Proposed solution**
Change reference to be uniform with the example.

**Comment by mpd37** [comment]
Well done spotting this. Will be fixed with next revision.
