### ISSUE TITLE
Unclear reference 

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#85]
**Describe the mistake**
Line indicated below states what follows: "Remark. Consider vector spaces V, W, X. From Remark 2.7.3 we already...", however remarks are not numbered and it remains unclear what number 2.7.3 could refer to otherwise.

**Location**
Please provide the 
1. version 2018-09-07
2. Chapter 2 
3. page 54 (chapter's 39)
4. 1341

**Proposed solution**
Correct or remove reference.

**Comment by mpd37** [comment]
Thanks for catching this. Will be fixed.
