### ISSUE TITLE
Request for clarification on homogeneous equations systems solution vs affine subspaces 

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#86]
**Describe the mistake**
Perhaps I am misunderstanding something but according to given definitions it would seem to me that every vector subspace is also an affine subspace translated by zero vector. If that assumption is true then statement in the indicated line is at least confusing. Prefixed line reads as follows: "[Recall that for homogeneous equation systems Ax = 0] the solution was a vector subspace (not affine)".

**Location**

1. version 2018-09-08
2. Chapter 2
3. page 60 (chapter's 45)
4. line 1435

**Proposed solution**
Clarify the relationship of vector subspaces with respect to affine subspaces.

**Comment by mpd37** [comment]
will be fixed in next update
