### ISSUE TITLE
a minor mistake in Chapter 2

### ISSUE THREAD

**Issue by andywenzhi** [mml-book/mml-book.github.io#95]
**Describe the mistake**
> with respect to $B$ onto coordinates with respect to $\tilde{B}$, and $T \in \mathbb{R}^{m \times m}$ is the transformation matrix of $id_W$ that maps coordinates with respect to $C$ onto coordinates with respect to $\tilde{C}$.

The position of $B$ and $\tilde{B}$ is reversed. So does $C$ and $\tilde{C}$.

**Location**
Please provide the 
1. Draft 2018-09-14
2. Chapter 2
3. Page 52
4. 1325-1327

**Comment by mpd37** [comment]
[basis_change.pdf](https://github.com/mml-book/mml-book.github.io/files/2387586/basis_change.pdf)
I made a few changes in this section. There was definitely something fishy. Would you mind having a look at it again?

**Comment by andywenzhi** [comment]
I read it twice and just found three minor typos.

Page: 53

Line: 1333
"the coordinate representation*s*" should be “the coordinate representation”.

Line: 1334
“the $j$th column of $T$” should be "the $k$th column of $T$".
"representation of $\tilde{c_j}$" should be "representation of $\tilde{c_k}$".

**Comment by mpd37** [comment]
Great - yes, they were typos. It seems the algebra makes more sense to you now. I'm going to close this issue when I update the pdf next time. Thanks for the help!
