### ISSUE TITLE
Small issues with exercises for chapter 2

### ISSUE THREAD

**Issue by Antymon** [mml-book/mml-book.github.io#96]
**Describe the mistake**
1) Exercise 2.14.5: closing square bracket incorrect
2) Exercise 2.20.6, line 1530: index of 2nd column vector b should be 2, not 3
3) Exercises 2.18 and 2.19.2 are redundant as their requests are repeated in exercise 2.20

**Location**
Please provide the 
1. version 2018-09-17
2. Chapter 2
3. last few pages of the chapter

**Comment by andywenzhi** [comment]
Also,
Exercise 2.4.1: the shape of the left and right matrix is not match.

**Comment by mpd37** [comment]
Bracket should be OK. We mean that 2pi is not included in the interval. We could also write [0, 2pi) instead of [0, 2pi[ 
What is more intuitive?

Fixed 2.20.6 and removed 2.18 and 2.19, but left 2.20, which contains 2.18 and 2.19 as sub-questions.

Fix will appear in next revision.

**Comment by Antymon** [comment]
I wasn't aware the outwards-pointing square bracket conforms to some notation that is actually in use, thought it is a typo. I would use whichever notation is used in the rest of the book as a base line. I cannot recall other usages of this notation throughout chapters 1-6, but maybe those chapters just did not have any intervals to mention. If there is no other usages, then I would go with whatever is most common in English-speaking education. I have only encountered regular brackets for exclusive range ends, but I don't find my experience being representative example.
