### ISSUE TITLE
Too much conditions on definition 2.15

### ISSUE THREAD

**Issue by tondji** [mml-book/mml-book.github.io#98]
**Describe the mistake**
In the definition 2.15 from the page 31, I think there is too much condition about the definition of a map to be injective

**Location**
Please provide the 
1. version (bottom of page) 2018-09-17
2. Chapter 2
3. page 31
4. line number/equation number : 1251

**Proposed solution**
For me I think, we do not need to have an if and only if condition because the if ... then condition is enough
 
**Additional context**

**Comment by mpd37** [comment]
correct. good catch!
